### ISSUE TITLE
Clean Local Datastore

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1000]
There should be a cleanup routine that cleans up the state persisted by the local data store.

**Comment by zalokhan** [comment]
### Update:
#### Setup:
3 node cluster running for 9 days with nodes frequently shutting down and recovering causing layout changes. This caused the epoch to increment to 25134. This created 65554 local datastore files.
This calls for a cleanup of the older epoch metadata.

```
/var/log/corfu# du -sh /tmp/corfu --exclude=/tmp/corfu/log
259M	/tmp/corfu
/var/log/corfu# ll /tmp/corfu | wc -l
65554
```
