### ISSUE TITLE
Bug in Layout Commit

### ISSUE THREAD

**Issue by annym** [CorfuDB/CorfuDB#1015]
Problem: when randomly killing a node in a 3-Node Cluster, the system sometimes hangs and client gets stuck, apparently because the servers are not able to move to the new layout.

(Possible) Cause: After debugging this, we have found that the commit layout logic in the LayoutView waits for the number of responses indistinct of the server actually responding. In this case, we might have a case in which the active servers (not killed) are slow and we count the timed-out server ‘responses’ (NetworkExceptions) as 3 responses and decide to get out, then we invalidate the layout and get back to the old one. We should have unique responses from each of the servers in the commit list.

**Comment by zalokhan** [comment]
Fixed by #972
