### ISSUE TITLE
Uncaught InterruptedException

### ISSUE THREAD

**Issue by annym** [CorfuDB/CorfuDB#1033]
## Overview

**Bug Report**

We have observed a case in which a client is not able to terminate whenever requested to shutdown on checkpointing. 

If the client is in the middle of checkpointing, and is requested to terminate---while all server nodes are killed--it fails to terminate and remains stuck in an infinite loop which fails on connection (NetworkException, as server nodes are down). This is a consequence of not handling the InterruptedException.

**Comment by no2chem** [comment]
Is the client thread coming from within Corfu, or from the external application? 

One solution would be to make the checkpointer thread a daemon thread, but that doesn't seem to solve the actual problem, (not actually handling the InterruptedException).

Were you able to pinpoint where the exception was being caught (and not rethrown)?

**Comment by no2chem** [comment]
This was closed by #1060.
