### ISSUE TITLE
AddNode sometimes fail to add it to the cluster

### ISSUE THREAD

**Issue by rogermichoud** [CorfuDB/CorfuDB#1035]
## Overview

I run a test workfow that does the following:
1. bootstrap a 6 nodes cluster
2. kill the primary sequencer
3. kill a randomly picked logunit
4. Add node 

- **Bug report.** 
The layout received by layout servers doesn't include the new node. This happens 1 time in 4 and looks like a race condition.

**Comment by zalokhan** [comment]
Depends on #1026 for a better detector and avoid flapping and also #1046 for client router epoch setting on Network Exceptions.

**Comment by zalokhan** [comment]
The test now passes and the new failure detector has been checked in.
