### ISSUE TITLE
Force Configuration (HOG)

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1047]
## Overview
The ability to force layout configuration without consensus.

- (x) **Feature request.**
## Deliverables
- A workflow to for force layout configurations

**Comment by no2chem** [comment]
Is this blocking something? Can you add it if it is? Also provide a complexity estimate and more detailed description. It's hard to tell if this is necessary for anything without it.

**Comment by zalokhan** [comment]
Resolved by #1158
