### ISSUE TITLE
Bug in transactions implementation

### ISSUE THREAD

**Issue by medhavidhawan** [CorfuDB/CorfuDB#105]
I need to understand this as my tests are failing with Transactionaborted:

Tx1:
Read(A)
Write(B)

Tx2:
Read(A)
Write(C)

Now the intersection is caused by A which is only in the readset of TX1 and TX2. Should one of them still abort ?

Concrete example:
1. I created swithing profiles before I ran any transactions
2. In two sequential transactions I create switch 1( transaction does a get for switching profile) and switch2.
The second transaction fails saying there was mutation detected on the switching profiles stream ! Not sure why ?

So a read in a transaction goes through the Accessor , which in turn ends up calling the following method in TransactionContext.

   /** Open an object for reading. The implementation will avoid creating a copy of the object
     * if it has not already been done.
     *
     * @param proxy     The SMR Object proxy to get an object for reading.
     * @param <T>       The type of object to get for reading.
     * @return          An object for reading.
     */
    @SuppressWarnings("unchecked")
    public <T> T getObjectRead(CorfuSMRObjectProxy<T> proxy)
    {
        return (T) objectMap
                .computeIfAbsent(proxy, x -> new TransactionalObjectData<>(proxy))
                .readObject();
    }

....
    ​public T readObject() {
                readTimestamp = proxy.timestamp;
                return (T) (smrObjectClone == null ? proxy.smrObject : smrObjectClone);
        }

This ends up adding the readObject to the ObjectMap of the TxEntry.

During resolution Two transactions that read A but did not ​mutate it , would end up conflicting.

 public boolean isAborted(CorfuRuntime runtime, long timestamp) {
        for (Map.Entry<UUID, TXEntry.TXObjectEntry> e : txMap.entrySet())
        {
            // If the last timestamp was MIN_VALUE, the object was never read from
            // This is the case if only pure mutators were used.
            if (e.getValue().getLastTimestamp() != Long.MIN_VALUE)
            {
                // We need to now check if this object changed since the tx proposer
                // put it in the log. This is a relatively simple check if backpointers
                // are available, but requires a scan if not.
                // Currently backpointers aren't available so we must scan.
                for (long i = e.getValue().getLastTimestamp() + 1; i < timestamp; i++)
                {
                    ILogUnitEntry rr = runtime.getAddressSpaceView().read(i).getResult();
                    if (rr.getResultType() ==
                            LogUnitReadResponseMsg.ReadResultType.DATA &&
                            ((Set<UUID>) rr.getMetadataMap().get(IMetadata.LogUnitMetadataType.STREAM))
                                    .contains(e.getKey()) && e.getValue().getLastTimestamp() != i)
                    {
                        log.debug("TX aborted due to mutation on stream {} at {}, tx is at {}, object read at {}", e.getKey(),
                                i, timestamp, e.getValue().getLastTimestamp());
                        return true;
                    }
                }
            }
        }
        return false;
    }

**Comment by no2chem** [comment]
Thanks for reporting this! I'm working on a pull request to address this issue now.

**Comment by no2chem** [comment]
It turns out that the issue was due to TXEntry putting the readset into the writeset. I fixed that with pull #107 and it will merge once tests are successful.
