### ISSUE TITLE
ITs are printing output when they shouldn't

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#1074]
## Overview

**Bug report.** Integration tests are printing to System.out when they should not be.

See example output:

```
unning org.corfudb.integration.ServerRestartIT
sequencerTailsRecoveryTest                                  [PASS]
discardTokenReceivedInPreviousEpoch                         [PASS]
testSingleNodeRecoveryTransactionalClientNested             SEED = dfa026782112e687
[PASS]
testSingleNodeRecoveryTransactionalClient                   SEED = 9e61ef048a3a35d8
[PASS]
testCorfuTableIndexReconstruction                           [PASS]
testRandomizedRecovery                                      SEED = 54028b07ae6091f4
Iteration #0
Iteration #1
Iteration #2
Iteration #3
```

**Comment by zalokhan** [comment]
@no2chem Most of these are required.
The `SEED` helps to reproduce the randomized behavior deterministically and reproduce the failure if needed.
The `Iteration` was initially put as this test was very long running and would take around 8-10 mins. Travis aborts the build if there is inactivity for 10 mins. So some sort of output logging was required.
I can remove atleast this for now as its just 4 iterations and doesn't take that long.

**Comment by no2chem** [comment]
I see. Instead of calling System.print, append to testStatus. See SMRMapTest::bulkReads for an example.

**Comment by zalokhan** [comment]
Sounds good I'll make the change.
