### ISSUE TITLE
BatchedWriter should write in batches, not just batch sync.

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#1104]
## Overview

**Bug report/Feature Request.** After looking into the functionality of BatchedWriter, it appears that it batches by making multiple calls to append, finally followed by a sync. This seems to be more expensive than making a single call to append and flushing a single large write down the FileChannel.

**Comment by Maithem** [comment]
I've tested this two months ago (in branches batchChannelWrites3 and batchChannelWrites), but it's not clear that a single large write is less costly than multiple calls. I've tested on multiple ssds and hard drives  on ubuntu 16.04. It seams that writing multiple buffers is faster. You can run the following test:

`    @Test
    public void writeTest() throws Exception {
        final int batchSize = 100;
        final int writeSize = 4000;

        final String path1 = "/tmp/log1.dat";
        FileChannel fc = FileChannel.open(FileSystems.getDefault().getPath(path1),
                EnumSet.of(StandardOpenOption.APPEND, StandardOpenOption.WRITE,
                        StandardOpenOption.CREATE, StandardOpenOption.SPARSE));
        // Single write
        byte[] payload1 = new byte[batchSize * writeSize];
        ByteBuffer buf1 = ByteBuffer.wrap(payload1);

        long st1 = System.nanoTime();
        fc.write(buf1);
        fc.force(true);
        long et1 = System.nanoTime();
        double time1 = (et1 - st1) / 1e6;
        System.out.println("Single buffer write " + time1 + "ms");

        final String path2 = "/tmp/log2.dat";
        FileChannel fc2 = FileChannel.open(FileSystems.getDefault().getPath(path2),
                EnumSet.of(StandardOpenOption.APPEND, StandardOpenOption.WRITE,
                        StandardOpenOption.CREATE, StandardOpenOption.SPARSE));

        byte[][] payload2 = new byte[batchSize][writeSize];

        long st2 = System.nanoTime();
        for (int x = 0; x < batchSize; x++) {
            fc2.write(ByteBuffer.wrap(payload2[x]));
        }

        fc2.force(true);
        long et2 = System.nanoTime();
        double time2 = (et2 - st2) / 1e6;
        System.out.println("Multi-buffer write " + time2 + "ms");
    }`

The writes are "async" anyways, they go into the page cache, from what I see, the fsync cost dominates the syscall overhead costs.

**Comment by no2chem** [comment]
First, you do realize your conclusion runs against every OS textbook, right? Eventually NIO's internal buffers will become full, and your small writes will result in a write syscall, which is (relatively) expensive. Going into the page cache, which you claim is cheap because they are "async", is going to involve a syscall (potentially lots). Besides that, you also have to call write 40x times more than the single buffer implementation, which, unless calling write with a large buffer is nonoptimal, is going to cost more regardless.

So of course, we have to analyze the benchmark to match up to this extraordinary claim. 
First of all, your benchmark has a bug. 
It doesn't seem to check if the full buffer writes, but that should swing things in favor of the single buffer. Nevertheless, when calling ```fc.write()```, you need to check if the buffer still has data by calling ```hasRemaining()```.

Second, I didn't run your benchmark because I'm not sure it properly calculates timing. I wrote another benchmark (see code [here](https://gist.github.com/no2chem/ac83f748ea2c63d3ccfd5ba8ae78192c)) and got the following results, using 128 byte chunks and 10MB writes:

```
Benchmark              (CHUNK_SIZE)  (NUM_BYTES)   Mode  Cnt    Score   Error  Units
writeBench.write                128     10485760  thrpt   20  103.361 ± 1.698  ops/s
writeBench.writeSmall           128     10485760  thrpt   20    8.287 ± 0.250  ops/s
```
Suggesting that writing small chunks is 12x slower.
Using a 100MB buffer:
```
Benchmark              (CHUNK_SIZE)  (NUM_BYTES)   Mode  Cnt   Score   Error  Units
writeBench.write                128    104857600  thrpt   20  14.888 ± 0.680  ops/s
writeBench.writeSmall           128    104857600  thrpt   20   0.789 ± 0.046  ops/s
```
We see a 18x slowdown.

**Comment by no2chem** [comment]
To add to this, chunking is expensive too, but not the dominating cost here. I broke down the benchmark:

```
Benchmark                     (CHUNK_SIZE)  (NUM_BYTES)   Mode  Cnt    Score   Error  Units
writeBench.sliceBuffer                 128    104857600  thrpt   20  505.214 ± 4.133  ops/s
writeBench.write                       128    104857600  thrpt   20   15.754 ± 0.223  ops/s
writeBench.writeSmall                  128    104857600  thrpt   20    0.876 ± 0.014  ops/s
writeBench.writeSmallNoChunk           128    104857600  thrpt   20    2.330 ± 0.023  ops/s
```

sliceBuffer only measures the cost of chunking (which you have to do, and your benchmark omits by allocating a pre-chunked buffer). writeSmallNoChunk writes the same number of bytes as write, but writes the same buffer repeatedly. The code is below.

```
    @Fork(value = 1, warmups = 0)
    @Benchmark
    @BenchmarkMode(Mode.Throughput)
    public void sliceBuffer(ExecutionPlan plan) throws IOException {
        for (int i = 0; i < plan.NUM_BYTES; i += plan.CHUNK_SIZE) {
            ByteBuffer slice = plan.large.slice();
            slice.position(i);
            slice.limit(i + plan.CHUNK_SIZE);
        }
    }

    @Fork(value = 1, warmups = 0)
    @Benchmark
    @BenchmarkMode(Mode.Throughput)
    public void writeSmallNoChunk(ExecutionPlan plan) throws IOException {
        for (int i = 0; i < plan.NUM_BYTES; i += plan.CHUNK_SIZE) {
            while (plan.small.hasRemaining()) {
                plan.fc.write(plan.small);
        }
        plan.fc.force(true);
    }
```

**Comment by Maithem** [comment]
It seems like you are not paying attention. I am sharing experimental results and no claims/conclusions have been made.

I understand that there are syscall overhead and I'm not trying to benchmark general syscall performance. What I am trying to investigate here is if the overhead is significant for the specific case of an avg write size of 4k and batch size of 50 (i.e. approximation of the generated workload by the BatchWriter). To better compare the results, I suggest you rerun your test with the same parameters and report your results.
