### ISSUE TITLE
Layout should have a unique Id (cluster Id)

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#1110]
## Overview

- **Feature request.** In order to prevent clients from connecting to the wrong cluster (or layout), layouts should contain a unique identifier which is persistent for the lifetime of the layout (across epoch changes). This unique identifier should be referred to as the cluster Id. 

Runtime users should be able to set the cluster Id of the cluster they wish to connect to. If the user does not set one, the runtime will adopt the cluster Id of the first cluster we connect to.

The runtime checks the Id of the layout it obtains. If it is incorrect, then the runtime should disconnect and refuse to service requests until it connects to a cluster with the correct Id.

## Deliverables

- [x] Layout should contain cluster id
- [x] Client should check to make sure cluster id does not change
- [x] Client should be able to set cluster id or adopt on first connection.

**Comment by zalokhan** [comment]
Deliverables completed.
