### ISSUE TITLE
getRouterFunction Race

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1114]
## Overview

**Bug report.** 
getRouterFunction is not thread safe, it can be called by multiple threads resulting in creating more than one router per endpoint. This can cause inconsistencies when invalidateLayout tries to update the epoch on each endpoint. One side effect that I observe is unexpected wrong epoch exceptions.

**Comment by zalokhan** [comment]
This has now been fixed.
- We no more update the router epochs in the CorfuRuntime invalidateLayout loop.
- getRouter is an atomic operation now.  It only creates if its absent in the ConcurrentHashMap in the nodeRouterPool.
Please reopen if you still feel this is not fixed.
