### ISSUE TITLE
Netty routers are not cleaned up/shutdown on router 

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#1132]
## Overview

- ( ) **Bug report.** Routers which are removed from a layout are not automatically removed on reconfiguration. If many servers are added/removed from the layout, this results in a too many open files error (due to too many EventLoopGroups being created), and furthermore the routers are not shutdown until the CorfuRuntime is shutdown.

**Comment by zalokhan** [comment]
Cleans the connections after the node is removed from the layout on invalidation.
