### ISSUE TITLE
Cluster ID Issue

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1134]
## Overview

**Bug report.**
checkClusterId breaks the corfu runtime in the management server on cluster reconfiguration. For example, in a setup where there are two nodes, one starts in single mode (node A) and the other starts as not bootstrapped (node B).  If B is added to A's cluster, then the runtime that runs on B fails with WrongClusterException when fetchLayout is called. This seems to happen because the client keeps an in memory cluster ID, that doesn't changed based on the current layout. This is a reasonable behavior for "external" clients, but for clients that run on the servers, we might want a different behavior (i.e. track the cluster id from the layout since that's the source of truth) .

**Comment by no2chem** [comment]
I can see the need for ignoring the clusterId, but I don't see how the scenario you describe could happen.

A runtime adopts the cluster Id of the first cluster it connects to. 
In the scenario you describe, B's runtime should obtain a clusterId when it for connects to A.
That clusterId should be A's clusterId. Since B was never bootstrapped, it should not have a clusterId.

Can you provide a test case that generates this behavior?

**Comment by Maithem** [comment]
Yes. Checkout the syncOrch branch and run AddRemoveNodeTestIT. 

Note, you need to uncomment  "//throw new WrongClusterException(clusterId, layout.getClusterId()); "
in the CorfuRuntime class.

**Comment by no2chem** [comment]
This seems to be a bug because the management server wants to connect with the wrong cluster ID. I'm not sure where this cluster ID is coming from (perhaps the server was restarted with -s)? I'm looking into it.

**Comment by zalokhan** [comment]
In the IT tests,
```
        new CorfuServerRunner()
                .setHost(host)
                .setPort(n2Port)
                .runServer();
```
If we do not provide the option ```.setSingle(false)```, the default option is ```single = true```

**Comment by no2chem** [comment]
Yeah, that seems like the issue.

This is correct behavior it seems like, the WrongClusterException is preventing you from connecting two disjoint clusters together. If someone connected to server 2 already (and server 2 served its own layout) and wrote some data, add node from another cluster should not be able to add it in.

Upon further inspection, it seems that addNode does not properly bootstrap a server which has not yet been bootstrapped. It needs to do that (and fail on servers which don't belong to the correct cluster).

**Comment by Maithem** [comment]
The other part of the problem is. MP starts nodes as single node clusters and merges clusters. Maybe we need to talk about the semantics and if we should adopt a new cluster id on a "Merge"

**Comment by no2chem** [comment]
Regardless of what MP is doing, you shouldn't start with -s unless you intend to start a new cluster. A potential client could connect to it, write to it, and it could suddenly lose all of its state. That's a configuration error on MP's part.

I would strongly discourage trying to override the clusterId mechanism, I'm not sure why we have not mechanism in the first place if we're just going to override it.

**Comment by Maithem** [comment]
I see the problem. This seems to stem from the fact that a layout has a mandatory cluster id field and nodes always have start with a cluster id. Maybe we need an explicit create cluster operation.

**Comment by no2chem** [comment]
That's what bootstrapping with a layout is (it's the whole point of bootstrap, really).

The problem is that -s bootstraps the node, so you are effectively creating three clusters.
Just don't start nodes with -s and bootstrap them as you add them in.

**Comment by no2chem** [comment]
In the testFramework1 branch, I was able to fix the issue in the addNode test by setting single to false and bootstrapping each node manually. Perhaps a later version of orchestrator not in master fixes the behavior, but the bootstrapping done by the orchestrator fails for some reason.

**Comment by Maithem** [comment]
For this particular problem, -s will fix this problem. I get that. There's another related problem, which is nodes cannot start without being a cluster, I'll discuss that on a different thread.
