### ISSUE TITLE
Invalidate Layout Parameters

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1135]
**Feature request.**

For some code paths we don't want fetchLayout to spin indefinitely. For instance, if a user specifies incorrect TLS params connect() will spin indefinitely. Maybe we can pass a timeout/retry parameter.

**Comment by no2chem** [comment]
And what should we do if connect fails after X retries? throw an Error?...

**Comment by no2chem** [comment]
Also, this functionality is already implemented in ```registerSystemDownHandler```.

**Comment by Maithem** [comment]
Yea fail with a timeout exception. Let me look into registerSystemDownHandler, I'm not sure if it can be used to specify different behavior for different code paths.

**Comment by Maithem** [comment]
outdated.
