### ISSUE TITLE
Create Cluster API

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1138]
## Overview

**Feature request.**
Provide a create cluster API to populate the cluster id on a node that was bootstrapped as a single node. 

## Deliverables
- API to create a cluster from from a single node instance.

**Comment by no2chem** [comment]
A single node already has a cluster ID. This api doesn't make sense and is dangerous to provide.

**Comment by Maithem** [comment]
superseded by https://github.com/CorfuDB/CorfuDB/pull/1141
