### ISSUE TITLE
wrong default-server in LogUnitServerTest

### ISSUE THREAD

**Issue by dahliamalkhi** [CorfuDB/CorfuDB#117]
Shouldn't the follows instantiate and return a new LogUnitServer instead of LayoutServer ?

```
public class LogUnitServerTest extends AbstractServerTest {
    @Override
    public IServer getDefaultServer() {
        return new LayoutServer(defaultOptionsMap());
    }
```

**Comment by no2chem** [comment]
Thanks. It seems that getDefaultServer is not being used in this test, so the error never surfaced.
