### ISSUE TITLE
Layout::moveServersToEpoch only moves a quorum of servers to the new epoch

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#1171]
## Overview

The Layout::moveServersToEpoch function only waits for a quorum of servers (defined as n/2+1) to move to the new epoch, even though the javadoc suggests otherwise.

This is very bug prone and not well defined (for example, if there is only one server in the epoch).

## Deliverables

- [x] Either fix Layout::moveServersToEpoch documentation or rename the function to Layout::moveQuorumToEpoch.

**Comment by zalokhan** [comment]
Fixed documentation.
