### ISSUE TITLE
Correctness Issue in KillNode/AddNode scenarios

### ISSUE THREAD

**Issue by rogermichoud** [CorfuDB/CorfuDB#1172]
## Overview
There is a ghost inconsistency issue that happens very seldom during run of KillNode/AddNode sceanrios. I am investigating if it is a False Positive or not.

- ( ) **Bug report.** KillNode/AddNode scenario

**Comment by Maithem** [comment]
When you kill a node, do you remove it and then re-add it?

**Comment by rogermichoud** [comment]
On kill, we wipe out the container. Add node spawn a new container and add it to the cluster.

**Comment by zalokhan** [comment]
Resolved.
