### ISSUE TITLE
Leaking Stream Data

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1190]
## Overview
 **Bug report.** 

It seems like a stream can read another stream's data, which breaks the stream isolation abstraction and can produce inconsistencies in upper layers that consume the stream. The problem happens when current() is called right after a seek to a global address that doesn't belong to the stream. 

This is demonstrated with the test case below:

`    
@Test
    public void canSeekOnStream()
        throws Exception
    {
        CorfuRuntime r = getDefaultRuntime().connect();
        IStreamView sv = r.getStreamsView().get(
                CorfuRuntime.getStreamID("stream  A"));
        IStreamView sv2 = r.getStreamsView().get(
                CorfuRuntime.getStreamID("stream  B"));

        // Append some entries
        sv.append("a".getBytes());
        sv2.append("a1".getBytes());
        sv.append("b".getBytes());
        sv.append("c".getBytes());

        // Seeking to the middle
        sv.seek(2);

        // Calling Current on "Stream A" will return an entrie
        // that was written to "Stream B"
        assertThat(sv.current().getPayload(r))
                .isEqualTo("a1".getBytes());
    }`

**Comment by no2chem** [comment]
Seems to be a bug? I guess current doesn't correctly filter if the logentry belongs to the stream.

**Comment by Maithem** [comment]
Yes, seek can "desync" the stream pointer and current() just reads the address that the current pointer points to.

**Comment by Maithem** [comment]
outdated.
