### ISSUE TITLE
ManagementView.waitForWorkflow ArithmeticException: / by zero

### ISSUE THREAD

**Issue by zjohnny226** [CorfuDB/CorfuDB#1200]
**Bug report.**

In ManagementView.waitForWorkflow(), if the pollPeriod is less than second (say 100 ms), you'll get a / by zero at line: long tries = timeout.getSeconds() / pollPeriod.getSeconds().

Also, I think you should add some context in your exceptions in that class, ie TimeoutException(), WorkflowResultUnknownException().

**Comment by Maithem** [comment]
Yes, this seems like a bug, the pollPeriod has to be at least 1 second (1000ms). The division should use operands after converting them to the smallest unit (i.e. nanos).

For timeout we can pass a string (wait time?) with the exception, but as for WorkflowResultUnknownException i'm not sure what kind of context you are looking for?(its an unknown exception)

**Comment by zjohnny226** [comment]
For the exceptions, it was just a suggestion to put in some information. From a user perspective, when I see a stacktrace that was caused by "SomeException: null", it doesn't tell me much. If you feel that the name of the exception is sufficient, then sure.

**Comment by Maithem** [comment]
What contextual information would improve your debugging experience?
