### ISSUE TITLE
Bug found in scenario with addnode+killsequencer fault

### ISSUE THREAD

**Issue by corfudb-performance** [CorfuDB/CorfuDB#1231]
**TEST(s) FAILED**:

**CORFU VERSION**: 7322831 (2018-03-16)
- **SERVERS : CLIENTS**: 3 : 3
- **MODE**: Disk ; **CLIENT APP**: LoadGenerator
- **FAILED COUNT / TOTAL COUNT**: 5 / 8
- **Failed Scenario ID(s)**: 
[('66fd206f091d49a67c2ea21e0f923490d91ee615ed3aaee42a8ef819db6fb4d1', ''), ('66fd206f091d49a67c2ea21e0f923490d91ee615ed3aaee42a8ef819db6fb4d1', ''), ('66fd206f091d49a67c2ea21e0f923490d91ee615ed3aaee42a8ef819db6fb4d1', ''), ('66fd206f091d49a67c2ea21e0f923490d91ee615ed3aaee42a8ef819db6fb4d1', ''), ('c2f878694ba546f0d0d9bdd2b84cb975ac9a12245376875d1f5d53c7a4b6d96e', '')]

**Comment by zalokhan** [comment]
Not reproducible.
