### ISSUE TITLE
Corfu Client Public API Breakage

### ISSUE THREAD

**Issue by bitmingw** [CorfuDB/CorfuDB#1233]
Is it possible to provide a backward compatible public API?

Here is one example:

https://github.com/CorfuDB/CorfuDB/blob/3f016fb351edfbbd03cd62f1b5b1dde3632c887e/runtime/src/main/java/org/corfudb/runtime/clients/BaseClient.java#L34

The default constructor for LogUnitClient, ManagementClient, LayoutClient and SequencerClient are also removed.

**Comment by zalokhan** [comment]
Why do we require client creation? What is the RPC call we are making?

**Comment by bitmingw** [comment]
@zalokhan We are using embedded corfu server for maven test.

I am not asking for a fix since we are already overloaded. But keep API compatible will help automation pipeline work smoothly.

I will close this issue after the next delivery of corfu.
