### ISSUE TITLE
IllegalArgumentException was thrown when adding 2nd corfu server

### ISSUE THREAD

**Issue by mat-vmware** [CorfuDB/CorfuDB#1242]
## Overview

_Replace the text below with your issue description, after answering yourself: 
IllegalArgumentException No matching method found: setRuntime for class org.corfudb.runtime.view.Layout  clojure.lang.Reflector.invokeMatchingMethod (Reflector.java:53)

I build a corfu with TOT of master.
Follow the project welcome page, execute the following commands
First, ./CorfuDB/bin/corfu_server -m -M localhost:9000 9001
Then ./CorfuDB/bin/corfu_layouts -c localhost:9000 edit
Got the error message as above.

**Comment by zalokhan** [comment]
@mat-vmware Thanks for pointing this out.
There have been a few changes in adding a node. Can you perform the following steps:
Assuming you have already instantiated a Corfu Server instance on localhost:9000 using the following command: `./CorfuDB/bin/corfu_server -ms 9000`
Start the second server on 9001: `./CorfuDB/bin/corfu_server -m 9001`
Now add the second server to the first cluster: `./CorfuDB/bin/corfu_add_node -c localhost:9000 -n localhost:9001`

I'll make the change in the Readme.

**Comment by mat-vmware** [comment]
@zalokhan Thank you for the info. It works. Saw the following output, nit is a little bit confusing.

mat@mat-workspace:~/Repos$ ./CorfuDB/bin/corfu_add_node -c localhost:9000 -n localhost:9001
WARNING: cat already refers to: #'clojure.core/cat in namespace: net.cgrand.parsley.fold, being replaced by: #'net.cgrand.parsley.fold/cat
2018-03-29 10:07:38,178 ERROR [nREPL-worker-0] o.c.u.MetricsUtils - Extracting metricsInterval VM property failed. Metrics collection and reporting will be disabled
 nil

**Comment by zalokhan** [comment]
@mat-vmware Yes, that will be fixed by a more descriptive output by #1238

**Comment by zalokhan** [comment]
Readme changes tracked by #1266
