### ISSUE TITLE
Error thrown when running mvn test

### ISSUE THREAD

**Issue by redbrick9** [CorfuDB/CorfuDB#1261]
## Overview

**"What kind of issue is this?"**_
compiling/testing error

On master branch, in test folder, run "mvn test", saw the following error.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project test: Failed during checkstyle execution: Unable to find configuration file at location: /home/mat/Repos/CorfuDB/test/test_checks.xml: Could not find resource '/home/mat/Repos/CorfuDB/test/test_checks.xml'. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by zalokhan** [comment]
Hi @redbrick9 
You can run the tests from the parent directory rather than running them from the test directory.

**Comment by zalokhan** [comment]
Closing this issue.
Please reopen if you still have trouble running the tests.
