### ISSUE TITLE
CorfuTable index may need to emit multiple values per key, value pair

### ISSUE THREAD

**Issue by jamesachn** [CorfuDB/CorfuDB#1285]
## Overview

Currently CorfuTable#IndexFunction is a `BiFunction<K, V, I>`, allowing 1 value to be emitted per {K, V} pair. In some cases, the {K, V} being indexed may need to emit multiple index mappings, requiring an index function of the signature: `BiFunction<K, V, Iterable<I>>`.

- **Feature request:**
  Allow multi-value index function to be specified in addition to the current index function specification. So each CorfuTable#Index may establish the association of a `CorfuTable#IndexName` to either a `CorfuTable#IndexFunction` or `CorfuTable#MultiValueIndexFunction`.

## Deliverables

- [ ] Allow an index to specify a multi-value index generation function, where each generated index key may be used to perform index-based lookup via `CorfuTable#getByIndex()`.

**Comment by zalokhan** [comment]
Merged.
