### ISSUE TITLE
regressTokenCountToValidDispatchedTokens bug

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#1287]
https://github.com/CorfuDB/CorfuDB/blob/bbe6fe5f49c7d2987307f51041aab9f271494658/test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java#L1388

Shouldn't this line read         assertThat(server0.getLogTail()).isEqualTo(expectedServer0Tokens);?

**Comment by zalokhan** [comment]
@no2chem No, this is correct.
Server0 had dispatched extra tokens in its own epoch (1) while Server 1 was dispatching tokens in its own epoch (2). When moving to epoch 3, Server0 has to reset its token count to match Server1.
Please see test description for details and let me know if you still have questions.

**Comment by no2chem** [comment]
Ok, good to know. I think the names probably could have been better but will close.
