### ISSUE TITLE
Stream Layer: Free Resolved Addresses

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1327]
**Bug report.** 
Currently, the stream layer doesn't have any mechanism to free resolved addresses that are no longer used. As time progresses the resolved stream addresses container keeps growing, we can use a sliding window to free old addresses that are not likely to be used. This is a problem because on long running systems, this can manifest as a memory leak.

**Comment by zalokhan** [comment]
Yes, this is fixed.
