### ISSUE TITLE
Move from UnrecoverableCorfuInterruptedError to Exception

### ISSUE THREAD

**Issue by zalokhan** [CorfuDB/CorfuDB#1360]
## Overview

Throwing Errors on Interrupted Exception causes clients to crash as none of the applications would expect Errors to be thrown by the client library. We should either resurface the InterruptedException as it is or wrap it in a Runtime Exception and expose it as an UnrecoverableCorfuInterruptedException.

**Comment by medhavidhawan** [comment]
Interrupted exception, if possible please surface it as InterruptedException. We have use cases where this functionality will be desired.

**Comment by Hagar2272** [comment]
The base bug in Bugzilla that we have close is Bug 2091186.
https://bugzilla.eng.vmware.com/show_bug.cgi?id=2091186
