### ISSUE TITLE
Dirty Transactions In ThreadLocal

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1366]
**Bug report.**
Its possible for transactions to be nested, where each transactional context refers to a different CorfuRuntime. For example, an executor thread that abruptly fails before clearing the thread local stack, a new job uses the same thread and starts a transaction with a new CorfuRuntime. This will cause the new Txn to be nested and the parent will refer to previously failed transaction (which refers to the old runtime). This can cause consistency issues and perpetually fail subsequent transactions on that thread (if that runtime is shutdown).

I think we should only nest transactions that belong to the same runtime. For example, If a transaction has a parent with a different Runtime, then we can pop all the transactional contexts and replace them with the more recent (with the new runtime) transaction context, or we can just throw a unrecoverable exception.

**Comment by zalokhan** [comment]
Merged.
