### ISSUE TITLE
Not checking for null arguments in HealNode and WorkflowRequest

### ISSUE THREAD

**Issue by StrikingThirteen** [CorfuDB/CorfuDB#1369]
## Overview
Need to check for null argument in the following:

HealNode:
-sendRequest
-verifyRequest

WorkflowRequest:
-getOrchestrator

**Comment by Maithem** [comment]
Its not clear which part is the bug, can you elaborate.

**Comment by StrikingThirteen** [comment]
Mentioned methods do not check whether the argument passed to them are not null. They should do such checks similar to for example how AddNode guards against null arguments. Not very significant, but it is good not to assume the arguments are non null.
