### ISSUE TITLE
how do I make it distributed?

### ISSUE THREAD

**Issue by FlyingXI** [CorfuDB/CorfuDB#1370]
how do i make it distributed on different computer?

**Comment by Maithem** [comment]
Read this https://github.com/CorfuDB/CorfuDB#cool-it-works-but-how-do-i-make-it-distributed

**Comment by Maithem** [comment]
You can re-open this if the steps in that link don't work.

**Comment by FlyingXI** [comment]
I run this ./CorfuDB/bin/corfu_server -ms 9000, 
then run ./CorfuDB/bin/corfu_server -m -M localhost:9000 9001, but  has a error:Error in initialization task: {}....what i should do?

**Comment by zalokhan** [comment]
@FlyingXI The steps are a little outdated.
Can you follow these steps to set up the cluster?
https://github.com/CorfuDB/CorfuDB/issues/1242#issuecomment-376955961
Re-open this if you're still facing issues.

**Comment by FlyingXI** [comment]
@zalokhan thanks very much. i got it..
