### ISSUE TITLE
Segments Don't Get Merged

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1390]
**Bug report.**
The fault detector never merges the segmented address space after add node

root@nsx-manager:/var/log/cbm# cat /config/corfu/LAYOUT_CURRENT.ds 
ohW{
  "layoutServers": [
    "address1:9000",
    "address2:9000"
  ],
  "sequencers": [
    "address1:9000",
    "address2:9000"
  ],
  "segments": [
    {
      "replicationMode": "CHAIN_REPLICATION",
      "start": 0,
      "end": 162562,
      "stripes": [
        {
          "logServers": [
            "address1:9000",
            "address2:9000"
          ]
        }
      ]
    },
    {
      "replicationMode": "CHAIN_REPLICATION",
      "start": 162562,
      "end": -1,
      "stripes": [
        {
          "logServers": [
            "address1:9000",
            "address2:9000"
          ]
        }
      ]
    }
  ],
  "unresponsiveServers": [],
  "epoch": 2,
  "clusterId": "e9f4e79d-79e3-4c8c-be83-89adbbde76eb"
}

**Comment by zalokhan** [comment]
This is not a bug. This is the expected behaviour. Merging segments event is only triggered during the healing workflow.

**Comment by Maithem** [comment]
I understand. I'm meant that "way after" the node has been added, the fault detectors are still not merging the segments.

**Comment by zalokhan** [comment]
Unless there is a failure detected and the node recovers triggering the HEAL_NODE workflow, the segments stay divided. So if there are no failures throughout the lifetime of the cluster, the layout will continue to have 2 segments.

**Comment by zalokhan** [comment]
As discussed we should have a janitor daemon job to detect and merge segments.
