### ISSUE TITLE
Corfu Version Check on Handshake 

### ISSUE THREAD

**Issue by annym** [CorfuDB/CorfuDB#1408]
## Overview

Current handshake exchanges both the ID and the Corfu Version. This means we can totally remove the check version from the CorfuRuntime.connect(). However, during handshake corfu version exchange is also only informational, so we should decide if we will allow connection despite version mismatch or continue to be only for informational purposes.   

**"What kind of issue is this?"**_
Repeated functionality/

**Comment by Maithem** [comment]
When the handshake fails or auth fails, we should send back an error so that it can be logged instead of just closing the connection which just shows as "channel closed".

**Comment by Maithem** [comment]
Re-open if needed.
