### ISSUE TITLE
Stream Log Analysis Tool

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1411]
**Feature request.**
We need a tool that analyzes the raw log and report information like size distributions, checkpoints and tables.

**Comment by xnull** [comment]
Graphana could be a good candidate

**Comment by Maithem** [comment]
This is more about analyzing the binary data logs and printing stats about size distribution, number of streams and checkpoint information.

**Comment by Maithem** [comment]
This will be part of a different effort for client side diagnostic tools.
