### ISSUE TITLE
Add CATCH_UP state to NodeStatus in ClusterStatusReport.

### ISSUE THREAD

**Issue by zalokhan** [CorfuDB/CorfuDB#1416]
## Overview

The clusterStatusReport should also have a field describing the stateTransfer/transient/catch up state of the node. This provides visibility to the consumer of the cluster status

**Comment by apavan** [comment]
This will bring in lot of value for automation testing to be able to adhere to our specifications.

**Comment by zalokhan** [comment]
Merged.
