### ISSUE TITLE
who can give me a hellow-world can run.....thanks.

### ISSUE THREAD

**Issue by FlyingXI** [CorfuDB/CorfuDB#1428]
## Overview

_Replace the text below with your issue description, after answering yourself: 
**"What kind of issue is this?"**_

- ( ) **Question.** This issue tracker is not the place for questions.
If you want to ask how to do something, or to understand why
something isn't working the way you expect it to, send the development
group an e-mail:
corfudb-dev@googlegroups.com

- ( ) **Bug report.** Please provide us the version of CorfuDB you are
using and, if possible, a failing unit test with your bug report. Don't
forget to describe the rationale for this issue (e.g. expected vs.
actual behavior).

- ( ) **Feature request.** Start by telling us what problem you’re trying
to solve or what you think can be improved.

## Deliverables

- [ ] ...

**Comment by zalokhan** [comment]
@FlyingXI Take a look at the samples module in the repository.
Reopen this if you have further questions.

**Comment by FlyingXI** [comment]
the type SMRMap is deprecatedthe in HelloCorfu.java of the samples module, so it can't run.

**Comment by zalokhan** [comment]
You can use `CorfuTable.class` instead of the `SMRMap`.
```
Map<String, String> table = runtime.getObjectsView()
                .build()
                .setType(CorfuTable.class)
                .setStreamName("test")
                .open();
```
