### ISSUE TITLE
Parallel fetching of layouts from layout servers

### ISSUE THREAD

**Issue by StrikingThirteen** [CorfuDB/CorfuDB#1443]
## Overview
Currently, the fetchLayout goes through the shuffled layout servers sequentially. As a result if the the layout server which are queried for layouts are unresponsive, no layout is fetched until next layout server will be queried and so on. Querying multiple layout servers in parallel can enable faster response. Additionally, this can also be helpful if a timeout is added to fetching layouts so this enhancement decreases the likelihood of a timeout by increasing the chance of fetching a layout from a responsive layout server.

**Comment by zalokhan** [comment]
In an ideal case, with the current code, we can proceed with just 1 RPC request and response as compared to n times the RPC cost.
In case of slow nodes with high CPU and memory utilization, where the servers are struggling, we might make the condition worse by broadcasting the layout requests.

However, we need the quorum layout fetch in some cases. For example please refer #1156

**Comment by Maithem** [comment]
Re-open if needed.
