### ISSUE TITLE
can't mvn install

### ISSUE THREAD

**Issue by FlyingXI** [CorfuDB/CorfuDB#1444]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project test: There are test failures.
[ERROR] 
[ERROR] Please refer to /opt/CorfuDB/test/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :test

**Comment by zalokhan** [comment]
@FlyingXI There are a couple of intermittently failing tests and we have fixes lined up to resolve these. You can skip the tests for now in order to test your functionality.
