### ISSUE TITLE
Sequencer Cache Eviction Policy vs. Overflow Criteria

### ISSUE THREAD

**Issue by annym** [CorfuDB/CorfuDB#1451]
## Overview

To determine sequencer overflow we strongly rely on the assumption that cache eviction is ordered, which happens to be wrong.

In other words, if a TX Snapshot timestamp is lower than the last evicted entry we throw a SEQUENCER_OVERFLOW exception meaning that we are not able to complete conflict resolution for this snapshot (assuming it was also evicted). But this is not true, given Caffeine eviction policy there is no guarantee that entries are evicted in order (this can be easily reproduced by sizing the cache to 10 entries, attempting to do 25 appends within a TX for instance and if you look into the cache eviction it goes something like: 2, 3, 4, 14, 15 ... We would currently abort any transaction in the range 5-13 (while entries are still in the cache). This assumption will lead to a higher TX abort rate, while we could actually resolve it. One potential solution to this is to check the cache before throwing sequencer_overflow exception.

**Comment by Maithem** [comment]
Re-open if needed.
