### ISSUE TITLE
fetchQuorumLayout fetches majority of LAYOUT_REQUEST responses.

### ISSUE THREAD

**Issue by zalokhan** [CorfuDB/CorfuDB#1461]
## Overview
`fetchQuorumLayout` in `ManagementAgent` currently requests layouts from all layout servers and then chooses the layout responded by a majority. This is incorrect as the commit phase in the layout consensus is a best-effort phase and does not rely on the majority responses.

Proposed Solutions:
- Get maximum epoch layout from all the requested layouts.
- Apply quorum fetch on phase 2 data from the Layout servers.

**Comment by Maithem** [comment]
Re-open if needed.
