### ISSUE TITLE
append is very slow.....

### ISSUE THREAD

**Issue by FlyingXI** [CorfuDB/CorfuDB#1464]
List<NodeLocator> layoutServers = new ArrayList<NodeLocator>();
layoutServers.add(NodeLocator.parseString("192.168.123.117:9000"));
CorfuRuntimeParameters parameters =
             CorfuRuntime.CorfuRuntimeParameters.builder().build().setLayoutServers(layoutServers);
CorfuRuntime rt = CorfuRuntime.fromParameters(parameters).connect();
UUID streamId = CorfuRuntime.getStreamID("file");
StreamsView sv = rt.getStreamsView();
IStreamView isv = sv.get(streamId);
		
long start = System.nanoTime();
		
ByteBuf b = Unpooled.buffer(8);
ByteBufOutputStream bbos = new ByteBufOutputStream(b);
ObjectOutputStream oos = new ObjectOutputStream(bbos);
oos.writeObject(fl);
long seq = isv.append(b.array());

i use this append, but very slowly...

**Comment by zalokhan** [comment]
@FlyingXI 
How much time does the append take?
Did you check if your server is running and bootstrapped on `192.168.123.117:9000`?

**Comment by zalokhan** [comment]
Yes, the plain append is slow as its throughput is throttled by the fsync.
To increase the throughput you will need to use batching and transactions using the CorfuTable.
The transactions can support large writes.

**Comment by Maithem** [comment]
@FlyingXI 

- Do you have a single writer?
- Are you running on a hard driver or an SSD ? 
- To check if the drive is the bottleneck try running the server without fsync (start the server with --no-sync)

**Comment by Maithem** [comment]
@FlyingXI you can reopen this if you still see the issue.

**Comment by FlyingXI** [comment]
@Maithem 
if I start the server with --no-sync, first one client append, then there is error when another client append.
org.corfudb.runtime.exceptions.AppendException
	at org.corfudb.runtime.view.stream.BackpointerStreamView.append(BackpointerStreamView.java:125)
	at org.corfudb.runtime.view.stream.IStreamView.append(IStreamView.java:109)

**Comment by Maithem** [comment]
@FlyingXI I can write with that option fine, I can't reproduce. Can you provide your driver code and the git commit that you're building with.

**Comment by FlyingXI** [comment]
@Maithem 
I start CorfuDB on two computer..then i append 50 times on one and when i run './corfu_sequencer -c pc3:9000 latest', i get message that is 'Token 0x792add48 Token(tokenValue=50, epoch=2)]'. but i run './corfu_sequencer -c pc3:9000 latest'  on another, i get message that is 'Token 0x2ea91120 Token(tokenValue=11, epoch=2)]'......the tokenValue on first computer  not equals on second computer.  So when i append data on second computer, get this error....
