### ISSUE TITLE
corfu_ping gets confused when its server restarts

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#147]
Found on master at commit ee47f10ea05dcadb68ef9d7dd571510034b1ea6a

corfu_ping gets confused when its server restarts: it logs `TimeoutException` after its monitored server stops & restarts.

Output:

    PING localhost:8000:
    PONG from localhost:8000: seq=0 time=66.779ms
    PONG from localhost:8000: seq=1 time=2.133ms
    Kill 17435, ping output stops
    Restart server on port 8000, ping output claims TimeoutException
    ERROR pinging localhost:8000: seq=2 error=TimeoutException
    ERROR pinging localhost:8000: seq=3 error=TimeoutException
    ERROR pinging localhost:8000: seq=4 error=TimeoutException
    ERROR pinging localhost:8000: seq=5 error=TimeoutException
    ERROR pinging localhost:8000: seq=6 error=TimeoutException
    ERROR pinging localhost:8000: seq=7 error=TimeoutException
    ERROR pinging localhost:8000: seq=8 error=TimeoutException
    ERROR pinging localhost:8000: seq=9 error=TimeoutException
    OK, enough. Stop the test server and the pinger

Script:

    ./bin/corfu_server -ms 8000 > /dev/null 2>&1 &
    spid0=$!
    sleep 1
    ./bin/corfu_ping corfu_ping localhost:8000 &
    ppid=$!
    
    sleep 2
    echo Kill $spid0, ping output stops
    pkill -P $spid0
    
    sleep 3
    echo Restart server on port 8000, ping output claims TimeoutException
    ./bin/corfu_server -ms 8000 > /dev/null 2>&1 &
    spid0=$!
    
    sleep 10
    echo OK, enough.  Stop the test server and the pinger
    pkill -P $spid0
    pkill -P $ppid

**Comment by no2chem** [comment]
Appears to be fixed by #156, as the client router now reestablishes the connection.

**Comment by slfritchie** [comment]
Agreed: the shell script above confirms the fix.
