### ISSUE TITLE
Layout servers in wrong epoch

### ISSUE THREAD

**Issue by qintoko** [CorfuDB/CorfuDB#148]
When starting two servers, it seems that the layouts command doesn't set the correct epoch for the new server added via the add_layout command.

**Comment by no2chem** [comment]
Hi there,

Did you run the second server with the -s flag? It seems that might cause the problem, since the second server would have rejected the bootstrap command. 

Additionally, it seems that the cmdlet should report when a bootstrap fails, which it currently does not. Working on that now.

**Comment by qintoko** [comment]
Hi, I did run it with -s. That might be the reason.

By the way, does it mean that within the cluster only ONE node should run with -s?

**Comment by no2chem** [comment]
Usually, -s should only be used in a single server configuration. Otherwise, only one server should be ever run with the -s.
