### ISSUE TITLE
NullPointerException leading to TXAbort Cause UNDEFINED 

### ISSUE THREAD

**Issue by annym** [CorfuDB/CorfuDB#1499]
## Overview

If the getByIndex API is used by a client in the context of a transaction, but this index has never been specified (does not exist for the current table) a NullPointerException is thrown which leads to a TransactionAbortedException with cause UNDEFINED. We should properly take an action in any of these directions:

DIRECTION 1: Have a fallback mechanism, i.e., fallback to scanAndFilter if no index is present and log a message warning the client that a secondary index lookup is not possible due to missing specification. Which is actually consistent with a trace message that we currently have for a CorfuTable created with no index which states: "CorfuTable: Creating a table without secondary indexes! Secondary index lookup will DEGRADE to a full scan"

DIRECTION 2: Leave the behavior as it is, but properly report the cause of abort. Here we also have two flavors of it:
      (a) Add a TransactionAbortException Cause  of the type NOSECONDARYINDEX (or something similar)
      (b) Change the cause of Abort to UNSUPPORTED (currently available) (meaning that getByIndex is not supported in the absence of an index), which leads to the need of adding a message field for the TransactionAbortedException, which actually adds value to the client.

**Comment by Maithem** [comment]
please close this issue if #1511 addresses this issue.
