### ISSUE TITLE
Improve debuggability to cover for scenarios like data loss in CorfuDB

### ISSUE THREAD

**Issue by apavan** [CorfuDB/CorfuDB#1506]
## Overview

_Replace the text below with your issue description, after answering yourself: 
Logging/Debugging to cover for scenarios questioning data loss by CorfuDB

- ( ) **Feature request.** Start by telling us what problem you’re trying
to solve or what you think can be improved.
I think we could come up with some kind of rolling logs to capture all the deletes and updates processed by CorfuDB as I do see a need for native logging to help us be efficient in debugging issues.

## Deliverables

- [ ] ...

**Comment by Maithem** [comment]
Re-open if needed.
