### ISSUE TITLE
Epoch Aware Layers

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1513]
## Overview
Investigate and Replace the timestamp with an (epoch,snapshot) tuple in the object, stream and address space.

**Comment by zalokhan** [comment]
Fixes #1321

**Comment by Maithem** [comment]
@annym can you go through the AddressSpaceView and StreamView and see where this transformation is appropriate.

**Comment by annym** [comment]
@Maithem I'm already looking into that, I'll update in this thread...
