### ISSUE TITLE
WriteAfterWrite Transactions vs. Optimistic Transactions

### ISSUE THREAD

**Issue by annym** [CorfuDB/CorfuDB#1519]
## Overview

WriteAfterWrite Transactions start time is determined on the constructor, instead of being set on the first access like is the case for Optimistic Transactions.  Is this how it is meant to be (what is the reason) or should they be consistent in this sense and only differ during commit for writes.

**Comment by Maithem** [comment]
#1247 . I don't think it matters, try removing it for the sake of uniformity.

**Comment by Maithem** [comment]
Re-open if needed.
