### ISSUE TITLE
Properly Seal Servers

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1528]
**Bug report.**

We have logic that depends on the seal to flush all pending requests on the system from previous epochs. Since the seal only sets the epoch on the router, but not flush requests requests from an older epoch can interleave with requests from the new epoch resulting in undesired behavior. 

To be more concrete, when the the faster loader will request the log tail from the logging units after a seal operation. If a write operation from an older epoch executes after the seal and before the tail request happens, then the faster loader will build state based on an incorrect tail. We need to make sure to flush operations on a seal. Lets focus on the logging unit and think about this can apply to other servers.

**Comment by WenbinZhu** [comment]
Addressed in #1545
