### ISSUE TITLE
Docker test framework disconnect() failed because of clusterParams.getNodesParams() not returning correct node.

### ISSUE THREAD

**Issue by WenbinZhu** [CorfuDB/CorfuDB#1570]
## Overview

 **Bug report:**

Cannot use disconnect() in testing framework:

`Request error: GET unix://localhost:80/containers/qkglhh-corfu-node56374/json: 404, body: {"message":"No such container: qkglhh-corfu-node56374"}`.

However from `docker pa -a` the three container endpoints are:
- `qkglhh-corfu-node64769`
- `qkglhh-corfu-node64770`
- `qkglhh-corfu-node64771`

I don't know how `clusterParams.getNodesParams()` gets this endpoint `qkglhh-corfu-node56374` that is not a node in cluster. I suspect that we are creating redundant Node instances and passing the wrong ones in clusterParams.

@xnull Can you take a look at it? You can checkout this branch: https://github.com/CorfuDB/CorfuDB/tree/partialPartitionIT 
I cleaned up the disconnect() method in this branch so you can better test and triage.

**Comment by WenbinZhu** [comment]
The problem could have been there for a while since all the tests using `disconnect()` are being ignored in maven with @ignore annotation.

**Comment by zalokhan** [comment]
@WenbinZhu  Is this fixed?

**Comment by WenbinZhu** [comment]
Fixed
