### ISSUE TITLE
Cleanup: set object properties during construction

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#158]
There are a couple of instances where objects are constructed then some of their members are set. This process can be error-prone. For example:
https://github.com/CorfuDB/CorfuDB/blob/master/src/main/java/org/corfudb/runtime/CorfuRuntime.java#L217

The Layout's CorfuRuntime should be passed through the constructor. Since some of the serialized objects have transient fields, setting all the objects fields during construction is not straightforward, so we need to think about it.

**Comment by slfritchie** [comment]
This task feels stale.  Thoughts, @Maithem?

**Comment by Maithem** [comment]
@slfritchie Yes, lets close this.
