### ISSUE TITLE
Travis CI History

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1616]
**Bug report.** 
After checking in the Travis related changes, we are no long able to spawn separate CI jobs for branches and as a consequence we can't accumulate history on failed jobs (because restart a job erases the history of that branch).

**Comment by Maithem** [comment]
Resolved.

**Comment by Maithem** [comment]
@xnull  I can no longer spawn builds for branches, please look into this its becoming a blocker.

**Comment by xnull** [comment]
I temorary disabled `build branches`
![image](https://user-images.githubusercontent.com/314292/50376798-6b662d80-05c7-11e9-834b-d70a1f6d4c35.png)

Reenable it again
