### ISSUE TITLE
Duplicate entries in the layout manager

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#162]
The layout manger should reject duplicate entries for stripes and segments. For example,

  "segments": [
    {
      "replicationMode": "CHAIN_REPLICATION",
      "start": 0,
      "end": -1,
      "stripes": [
        {
          "logServers": [
            "localhost:9000",
            "localhost:9000",
            "localhost:9000",
            "localhost:9000",
            "localhost:9000",
            "localhost:9000"
          ]
        }
      ]
    }
  ],
  "epoch": 5
}

**Comment by Maithem** [comment]
@zalokhan You were looking at this sometime back, is this still the case?

**Comment by zalokhan** [comment]
Yes, this would still be the case.
Although lot of logic has changed, the user can add a same server twice.
A trivial solution to avoid this would be to convert the lists of servers in the Layout to sets.
Would that be fine ?

**Comment by Maithem** [comment]
@zalokhan I think using sets to store the nodes is a good idea.

**Comment by slfritchie** [comment]
Mid-June issues review: @zalokhan We should keep topic alive, right?

**Comment by zalokhan** [comment]
Yes @slfritchie 
Using sets instead of lists is a major change and will require refactoring throughout the code. We can investigate other options too.

**Comment by no2chem** [comment]
Let's try to address this before the v1.0 milestone.

**Comment by zalokhan** [comment]
Add node workflow verifies that a node is added to the layout only once. #1103
