### ISSUE TITLE
Batch read is not aware of multiple stripe 

### ISSUE THREAD

**Issue by lixinchengdu** [CorfuDB/CorfuDB#1644]
https://github.com/CorfuDB/CorfuDB/blob/6fcdb65a9cde56cdcddb87639cb590f63d05271a/runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java#L79-L105

https://github.com/CorfuDB/CorfuDB/blob/6fcdb65a9cde56cdcddb87639cb590f63d05271a/runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java#L107-L132

Both functions assume that there is only one stripe.

**Comment by Maithem** [comment]
Hey Xin, any status on this ?
