### ISSUE TITLE
LayoutServer response to LAYOUT_REQUEST during reconfiguration is bad

### ISSUE THREAD

**Issue by dahliamalkhi** [CorfuDB/CorfuDB#165]
server needs to handle LAYOUT_REQUEST during configuration-changes. LayoutServer needs to save the "currentLayout" when a proposal arrives, and maintain it until replaced with a new committed. Then it will be safe to respond with currentLayout.

**Comment by slfritchie** [comment]
Resolved by @medhavidhawan's layout service work.
