### ISSUE TITLE
sonarqube not working

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1652]
**Bug report.**
sonarqube doesn't seem to be working anymore

**Comment by xnull** [comment]
It works for [master branch](https://sonarcloud.io/dashboard?id=org.corfudb%3Acorfu).
 - I don't see big value to have it for PR-s.
 - Sonar can show warnings on github for a PR, it's a useful feature. Sonar uses findbugs for that, so let's bring findbugs checks in maven, if the PR has a critical warning, then the build will be failed. That's more reliable than comments in github which are mostly ignored or can be ignored.

Anyway, let's discuss it, it is a very important feature.

**Comment by zalokhan** [comment]
@xnull Can you enable this on PRs too.
It is really helpful to have those checks before we push the code. It has more value before the code is pushed in.
Can you also coordinate with @hisundar as he has some good ideas for this too?

**Comment by hisundar** [comment]
One of the suggestions was to integrate with Fortify since the commercial license is already available.

**Comment by Maithem** [comment]
outdated.
