### ISSUE TITLE
Container IP Changes On Restart

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1653]
**Question.**
In many of our tests the containers are restarted, if the ips change when the container starts, it will cause weird behavior. Looking at the it code it couldn't find any code/configuration to guard against this, do we need to make some changes to prevent this from happening?

**Comment by xnull** [comment]
In our tests (testing framework), we don't use IP addresses, we use DNS names. 
Even if IP address is changed after restart it will not affect anything, the node DNS name will be the same, the DNS name will be resolved to the new IP address after restart, it's guaranteed by docker.
