### ISSUE TITLE
Commit Counters

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1664]
**Feature request.**

When a node is reintroduced to the cluster after it has been marked unresponsive, we reset the data and rebuild the logging units from scratch. This is inefficient. We should periodically figure out to what prefix the log is fully replicated on all logunits and only rebuild the node from the latest replicated prefix.

**Comment by lixinchengdu** [comment]
I have some confusion about what commit counters mean here. I am writing about my thought on this problem below. 

Fully replication means the state of every prefix log address has the same data (same real data, or junk , or not written). 

There are several issues worth our attentions. 

1) How could we compare two prefix logs are identical?

Compare each address takes `O(n)` time where `n` is the length of the prefix log. This method is not scalable. One method to accelerate is to build some index for searching. One simple way is to periodically compute the hash of the prefix log. If two hash values are equal, we could highly assure that the two prefix logs are identical. 

2) When to taken the 'snapshot' of the prefix log?
If it is driven by clocks, i.e. the LogUnit Server periodically compute the hash of the prefix log. The hard part is how to handle the address that has not been written. One possible way is to fill the hole like for all LogUnit Servers.

**Comment by Maithem** [comment]
outdated.
