### ISSUE TITLE
Wrong assumption on the number of segments

### ISSUE THREAD

**Issue by lixinchengdu** [CorfuDB/CorfuDB#1667]
https://github.com/CorfuDB/CorfuDB/blob/967e4c12588929f835ee894a50a3c99b69623bf5/infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/HealNodeWorkflow.java#L82-L96

This snippet of code assumes that there is only one segment when the system is stable.

**Comment by zalokhan** [comment]
In what case would you want multiple segments?
