### ISSUE TITLE
Efficient State Transfer

### ISSUE THREAD

**Issue by zalokhan** [CorfuDB/CorfuDB#1726]
## Overview

On a node flapping, state transfer is performed repeatedly several times. This causes a CPU spike and a heavy load on the network. We can perform a more efficient state transfer by optimizing the data needed to transfer.

**Comment by lixinchengdu** [comment]
When healing a node, is it necessary to transfer state from scratch?

**Comment by zalokhan** [comment]
@lixinchengdu Yes, it is.
Else there can be branching of data on the same addresses.
Since it is difficult for us to identify this branching, we prefer clearing and restarting.
