### ISSUE TITLE
ManagementAgent shutdown silently when exceptions happen in recovery

### ISSUE THREAD

**Issue by WenbinZhu** [CorfuDB/CorfuDB#1731]
## Overview

When management server is started, it performs a layout recovery and then start failure/healing detectors. The recovery attempt is retried infinitely until success. However the current recovery code does not handle exceptions, so when any exception happens during recovery, e.g. IOException when saving the new management layout, the recovery thread exits and invokes the uncaughtExceptionHandler, which will shutdown the whole managementAgent silently including failure/healing detectors.

**Comment by annym** [comment]
Fixed.
