### ISSUE TITLE
in LayoutServer add API to query the history

### ISSUE THREAD

**Issue by dahliamalkhi** [CorfuDB/CorfuDB#175]

**Comment by slfritchie** [comment]
Keep open.  The `LayoutServer.getLayoutHistory()` exists today, but there's no implementation yet of a remote query.

**Comment by slfritchie** [comment]
Mid-June issues review: @zalokhan please comment on the necessity of this issue.

**Comment by zalokhan** [comment]
I am working on patching up holes in the layout history which introduce a remote query.

**Comment by no2chem** [comment]
Targeted for v1.1.

**Comment by StrikingThirteen** [comment]
I am working on this.

**Comment by xnull** [comment]
outdated
