### ISSUE TITLE
Premature client router shutdown

### ISSUE THREAD

**Issue by zalokhan** [CorfuDB/CorfuDB#1751]
## Overview

The runtime runs the `fetchLayout` whenever a layout is required. With this action, we also piggyback `pruneRemovedRouters`. 
`pruneRemovedRouters` detects all routers which have a connection to nodes which are not present in the layout. These routers are shut down and removed.

In order to access a node outside the layout (example: to bootstrap or reset) we might need to create a router to connect to them. Either the `pruneRemovedRouters` should take care of routers in use or these calls should not be made via the runtime.

**Comment by annym** [comment]
This is the same Issue as #1822 which will be addressed by @WenbinZhu
