### ISSUE TITLE
In corfu README, add 'scripts' directory before refering to corfu_server

### ISSUE THREAD

**Issue by dahliamalkhi** [CorfuDB/CorfuDB#177]

**Comment by slfritchie** [comment]
Hm, the scripts in the `scripts` directory seem designed to be symlinked and take their cmdlet name from $0.  The `bin` dir is already mentioned.  Did you have something else/more in mind?

    The binaries which will be referenced in the following sections will be located in the ```bin``` directory.

**Comment by no2chem** [comment]
Yeah, what is the point of referring to the script directory?

**Comment by dahliamalkhi** [comment]
Hmm in my latest pull, there are no symlinks in bin, and all shell scripts are not runnable and actually not working .

On Wed, Jun 29, 2016 at 9:45 AM, Michael Wei <notifications@github.com> wrote:
Yeah, what is the point of referring to the script directory?

**Comment by no2chem** [comment]
Is your git checkout broken? They have been there since 7 months ago and have not been touched.

https://github.com/CorfuDB/CorfuDB/tree/master/bin

**Comment by slfritchie** [comment]
Ping @dahliamalkhi ... still relevant?

**Comment by no2chem** [comment]
This appears to be a problem with a bad git checkout, closing.
