### ISSUE TITLE
Reduce number of sequencer calls for object read 

### ISSUE THREAD

**Issue by WenbinZhu** [CorfuDB/CorfuDB#1787]
## Overview

When reading an object, there will be multiple RPC calls to sequencer: first call to check if the object has up-to-date version  and if optimistic read is possible. If this check fails, another sequencer call to get address will be made by stream layer to sync the object. We could probably remove the second sequencer call if the stream layer knows that this address is actually a stream tail, not global tail.

**Comment by Maithem** [comment]
You can add a type to the Token object and specify if its a stream tail or global tail. I think this will improve non-transactional reads significantly.
