### ISSUE TITLE
Nested transaction can have different type, which shouldn't be allowed

### ISSUE THREAD

**Issue by WenbinZhu** [CorfuDB/CorfuDB#1796]
## Overview

Currently when starting a nested transaction using  `runtime.getObjectsView().type("TransactionType.XXX").build().begin()` it can bypass the transaction type inherit logic, which ends up in nested transactions with different transaction types. This could violate transaction semantics, though in some cases, the type mismatch will be detected upon txn commit, but in other cases, inconsistency will occur without being noticed.

**Comment by lixinchengdu** [comment]
What is the problem of having different transaction types? For example, it is possible to have a snapshot transaction nested in an optimistic transaction.

**Comment by WenbinZhu** [comment]
@lixinchengdu In your example, yes, but you can't do it vice versa

**Comment by Maithem** [comment]
I think for the sake of simplicity we should just allow transactions of the same type to nest.
Transaction nesting is kind of broken, so I'm guessing that this is just sanity check for now?

**Comment by WenbinZhu** [comment]
@Maithem Yes, for simplicity, just a sanity check and throw an exception if type mismatch.

**Comment by WenbinZhu** [comment]
Addressed in #1797
