### ISSUE TITLE
readAll Calls readRange

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1808]
**Bug report.**
Commit 2ab39da845ba3e40a66e31ad550d54d59e3db103 changed the behavior of readAll to an underlying implementation that uses readRange. Since there's a high probability that the addresses passed to readAll are sparse, then a read range can be inefficient (reads more addresses than it needs) and can pollute the caches. Also, if the cache consumer doesn't filter the addresses by stream id, then this can also turn into a correctness issue (i.e. retrieving other stream's data).

**Comment by Maithem** [comment]
@WenbinZhu is addressing this in his clean up

**Comment by WenbinZhu** [comment]
Addressed in #1855
