### ISSUE TITLE
Tx End and Shutdown Exception

### ISSUE THREAD

**Issue by annym** [CorfuDB/CorfuDB#1822]
## Overview

AbortCause UNDEFINED has a non-deterministic behavior, the data could have been committed or not. 

TXEnd() in ObjectsView.java

catch (Exception e) {
            log.error("TXEnd[{}]: Unexpected exception", context, e);
            TxResolutionInfo txInfo = new TxResolutionInfo(context.getTransactionID(),
                    Token.UNINITIALIZED);
            TransactionAbortedException tae = new TransactionAbortedException(
                    txInfo, AbortCause.UNDEFINED, e, context);
            context.abortTransaction(tae);
            throw new UnrecoverableCorfuError("Unexpected exception during commit", e);
        }

Let's suppose the following scenario:

- A thread initiates an Optimistic TX 
- (performs different operations)
- It attempts to END the TX and actually commits to 2 server nodes successfully and fails on the 3rd node (as this node has been removed). 
- This exception causes to validate if the data was written or not (validateOfTheWrittenEntry) which actually attempts to read from the tail of the chain (node which has been removed from the configuration)... Furthermore a shutdown of that client router  is triggered when the node is detected to be out, which causes this thread to complete exceptionally (ShutdownException). 

This leads in the injection framework to correctness issues, because this thread actually dies, as it is only expecting TxAbortExceptions, and this UnrecoverableCorfuError bubbles up.

**Comment by WenbinZhu** [comment]
I think currently we're not doing a sync after commit, if you mean `tryCommitAllProxies`, that part actually a no-op because no one is registering proxies.

**Comment by annym** [comment]
Yes @WenbinZhu like we discussed offline it is not a sync it is the validateStateOfWrittenEntry for the last write in the chain. I've adjusted the text to properly describe the issue.

**Comment by WenbinZhu** [comment]
@annym Cool, thanks for verifying it. Also this is probably related to a potential bug I just found today, we can discuss that tomorrow.

**Comment by WenbinZhu** [comment]
Fixed in #1843

**Comment by WenbinZhu** [comment]
Fixed in #1843
