### ISSUE TITLE
The number of entries in a log file should be a variable

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#185]
Currently, It's hard coded to 10k entries.

**Comment by no2chem** [comment]
Was this addressed by #198 ?

**Comment by Maithem** [comment]
No, I'll look at it.

**Comment by slfritchie** [comment]
Ping @no2chem @Maithem, still relevant?

**Comment by Maithem** [comment]
@slfritchie  yes

**Comment by slfritchie** [comment]
Mid-June issues review: @Maithem still relevant enough to keep this ticket open?

**Comment by no2chem** [comment]
Moved to 1.1 release

**Comment by Maithem** [comment]
outdated.
