### ISSUE TITLE
Get rid of LogData deserialization dependency on CorfuRuntime 

### ISSUE THREAD

**Issue by WenbinZhu** [CorfuDB/CorfuDB#1880]
## Overview

Seems like we used to serialize the CorfuObject to the global log data, which introduced a dependency on CorfuRuntime when deserializing the payload from log data. We need to remove this dependency as we're not serialize the whole CorfuObject now.

**Comment by Maithem** [comment]
@WenbinZhu please merge the revert and close this.

**Comment by WenbinZhu** [comment]
@Maithem This requires changing production code, but our current production release is no longer accepting changes other than bug fixes. I will do this for next production release branch once it's created.
