### ISSUE TITLE
Unhandled Trimmed Exception 

### ISSUE THREAD

**Issue by lixinchengdu** [CorfuDB/CorfuDB#1883]
## Overview

From corfu users' perspective, they may not be aware of that a simple API call (e.g. get, put, remove, etc) would throw Trimmed Exceptions. The wrapper class (e.g. SMRMap$CORFUSMR.java) inherits existing interfaces (e.g. Map) and therefore it is hard to change the signatures of APIs to throw checked exceptions. Nevertheless, it is possible to add some sample codes to illustrate the issue.

**Comment by Maithem** [comment]
How can it be handled? 

If the MutatorAccessor tries to sync to the mutation's version, but it has been trimmed, then that state cannot be recovered.

**Comment by lixinchengdu** [comment]
> How can it be handled?
> 
> If the MutatorAccessor tries to sync to the mutation's version, but it has been trimmed, then that state cannot be recovered.

Corfu is unable to return correct answer but the client should be aware of this issue. However, the client should be aware of the fact that the corfu backed map may throw unchecked exceptions (e.g. Trimmed Exception). Actually, if corfu map was not using map interface, Trimmed Exception would better be declared as checked exception. 

In summary, I think the user/client should at least be aware of this problem so that they could handle the exception in the callers' program.
