### ISSUE TITLE
Enforce a coding style

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#189]
@no2chem 
We need to add style enforcement as a part of the build, but since there are around 5000 violations we need to do it incrementally. Let's start enforcing this on new patches while we fix the existing code base.

**Comment by no2chem** [comment]
Should we just adopt the default sun style check? Or is there something specific we should pick?

**Comment by Maithem** [comment]
I think the default sun style is reasonable, most of the changes i pushed in were based on it.

If you don't have a strong preference for anything else, then I think we should just go with the default sun style check.

**Comment by slfritchie** [comment]
Mid-June issues review: Corfu code style guide is under review now.  Once discussion reaches rough consensus, enforcement will begin in stages.

**Comment by Maithem** [comment]
outdated.
