### ISSUE TITLE
CorfuDB has a huge memory footprint & fails to operate if dataset is bigger than RAM

### ISSUE THREAD

**Issue by hisundar** [CorfuDB/CorfuDB#1907]
## Overview

Say a key-value database has 10K keys with 1MB values. If the database must be deployed on a machine with 10GB of RAM, CorfuDB cannot be used. This is because the dataset of 10GB needs to be fully memory resident in various layers - Runtime (Object View Cache, Address Space view cache etc), Infrastructure (Log Unit, Sequencer cache etc).

However, given that CorfuDB does have persistence and a way to map user data to persisted disk locations, it is possible to employ value-eviction where only the metadata (keys+stream addresses) needs to be memory resident and the actual values can be paged in on-demand.

This will not only allow Corfu to scale to DGM (dataset greater than Memory) scenarios but can also free up significant resources on the systems that it is deployed.

## Deliverables
Runtime:
- [ ] Split higher level Maps and key-value collections into key, metadata, value triplets where metadata can just be the stream address that points to where the data resides.
- [ ] Allow for memory quotas to be enforced where say a background evictor removes values when memory usage goes above quota
- [ ] Have a fetcher task which can page-in data on demand.

Infrastructure:
- [ ] Split AddressMetadata and Data
- [  ] Use feature like mmap on the address metadata and data segments with binary search to lookup addresses and entries.

**Comment by medhavidhawan** [comment]
+1 I would like to see a design for this.

**Comment by lixinchengdu** [comment]
I have define the a data structure to denote the the location of an SMREntry inside IlogData. Probability you could reuse the data structure as one field of metadata.

**Comment by hisundar** [comment]
Sure will work on a design doc and also reuse the SMREntry location inside ILogData.

**Comment by Maithem** [comment]
I don't think this is a bug. From the read me page:

> CorfuDB objects are **in-memory**, highly available data structures providing linearizable read/write operations and strictly serializable transactions. 

Supporting data structures with DGM can be done today in the object layer (probably using stream composition). From Corfu's POV, I think it would be nice to expose caching hints to the AddressSpace, so that object can drive caching decisions.

**Comment by hisundar** [comment]
> I don't think this is a bug. From the read me page:
> 
> > CorfuDB objects are **in-memory**, highly available data structures providing linearizable read/write operations and strictly serializable transactions.
> 
> Supporting data structures with DGM can be done today in the object layer (probably using stream composition). From Corfu's POV, I think it would be nice to expose caching hints to the AddressSpace, so that object can drive caching decisions.

There are 2 parts to this one is a feature and the other is a bug.
Feature: As you say CorfuDB objects are in-memory so a full DGM support would be a feature.
Bug: Memory bloat is **definitely a bug**. This can be proven in just 2 lines:
`String bigBufStr = new String(new byte[oneMB]);
   for (Integer i = 0; i < 500; i++) { corfuTable.put(i.toString(), bigBufStr+i); }`
If the above test is run on a Mac having 16 GB of RAM the test will hit a 
`java.lang.OutOfMemoryError: Java heap space`
Any database that can't store 500MB worth of user data on a 16 GB system is not going to be very useful for long. It's not just the AddressSpace which is holding up memory, we have to consider the full stack - the mainMap, ObjectView, AddressSpace and also the LogUnit to get a full view of the resource consumption right?

**Comment by WenbinZhu** [comment]
@hisundar I suspect the memory bug might in fact be because of  your JVM xmx configuration?

**Comment by hisundar** [comment]
@WenbinZhu yes, it is because of the JVM xmx configuration which will likely shoot down anything larger than 4GB. But that is still not the answer right? Why should a 500MB dataset refuse to run with xmx 4GB. That is 8X the dataset size right? Even if we claim that data needs to be split in runtime and infrastructure, that would still be 4X the data size which would still unacceptable overhead for several use cases. Please correct me if I am missing something?

**Comment by Maithem** [comment]
So many things are being conflated here. Let's unwrap this.

> There are 2 parts to this one is a feature and the other is a bug.

Create a second issue to track the proposed feature. We can discuss the bug claim on this issue.

> Memory bloat is definitely a bug

False. Merely seeing  `OutOfMemoryError` doesn't imply memory bloat. 

Furthermore, your test is incorrect: It's not creating 500mb of user data, its actually creating 1gb of data (i.e. `new String(new byte[oneMB])` uses 2mb of memory). In java, `String` is internally represented as a `char[]` (see [1]). In other words, you are creating a two megabyte object on each put. 
 
Inserting 500 keys, where each value is 2mb would result in ~1GB of memory overhead. This can be clearly seen by taking a heap dump. For example:

![image](https://user-images.githubusercontent.com/7818642/58754495-55b63780-8486-11e9-8b84-01635fb1ac64.png)

JVM's memory usage:

![image](https://user-images.githubusercontent.com/7818642/58754484-c90b7980-8485-11e9-993e-1e120d07364d.png)


> Any database that can't store 500MB worth of user data on a 16 GB system is not going to be very useful for long. 

Great insight, but this doesn't apply to Corfu. The example you provided can easily run with only 2GB of JVM heap. 

Finally, there could be many other reasons why your test is failing, Xmx might not be insufficient, the server and client might be running inside the smae JVM, the caches might be too large, the unit test infrastructure might be consuming too much memory, the serializer might be inefficient etc. 


[1] https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/java/lang/String.java#L114

**Comment by hisundar** [comment]
> So many things are being conflated here. Let's unwrap this.
> 
> > There are 2 parts to this one is a feature and the other is a bug.
> 
> Create a second issue to track the proposed feature. We can discuss the bug claim on this issue.

Sure @Maithem.  I can create a separate issue to track the DGM feature as you suggest, but perhaps once we are clear that this is not a bug?

> Merely seeing `OutOfMemoryError` doesn't imply memory bloat.

I opened this ticket only because I had accidentally stumbled across this OutOfMemory while testing something unrelated and my test did not seem to be doing anything extraordinary.
 
> Furthermore, your test is incorrect: It's not creating 500mb of user data, its actually creating 1gb of data (i.e. `new String(new byte[oneMB])` uses 2mb of memory). In java, `String` is internally represented as a `char[]` (see [1]). In other words, you are creating a two megabyte object on each put.

I am not sure about your claim. If what you are saying is true then why does the length() of that String constructed from the 1MB byte array print out 1048576 (1MB)? Also as per the java String [docs](https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/java/lang/String.java#L416), _the length may not be equal_ to the byte array. This is true in case of random bytes which cannot be represented in character sets. For a byte array of 0s the String length() does appear to be the same as the byte array right? Moreover I repeated the test with `new char[]` instead of `new byte[]` which is nothing but an `Arrays.copyOf()` function and I still hit the `OutOfMemory` although it is not deterministic.

> Finally, there could be many other reasons why your test is failing, Xmx might not be insufficient, the server and client might be running inside the smae JVM, the caches might be too large, the unit test infrastructure might be consuming too much memory, the serializer might be inefficient etc.

If we are sure that none of those are fixable Corfu issues then I agree that this is not a bug but I think it would be good to rule this out right?

**Comment by hisundar** [comment]
As suggested by @Maithem , let me open a separate feature tracking issue, since this appears to be my test env related.
