### ISSUE TITLE
Introduce a stream create method?

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#194]
@no2chem Create is coupled with a stream write. For example, writing to a stream that doesn't
exist would result in creating and writing to the stream. I think the stream creation should be separated from the write mechanism.

What do you think?

**Comment by no2chem** [comment]
I agree. I'm not sure what the best way to accomplish this is. Currently the object layer does something like check for the presence of a constructor entry - maybe we could do something similar for stream create.

**Comment by Maithem** [comment]
@no2chem this would be addressed by having a stream registry, right?

**Comment by slfritchie** [comment]
Mid-June issues review: comments @Maithem?

**Comment by Maithem** [comment]
This will be part of the metadata store. I have a simple design might be able to sneak it in

**Comment by Maithem** [comment]
We have abandoned the metadata store.
