### ISSUE TITLE
compactTail seems to be broken

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#196]
The streamCache is not being built properly, as a consequence GET_CONTIGUOUS_TAIL and STREAM_READ return incorrect values.

To reproduce, start a logging unit write to a stream and then restart the logging unit. GET_CONTIGUOUS_TAIL is incorrectly calculated. Furthermore, it seems like the cache writer
is never triggered on the streamCache.

**Comment by no2chem** [comment]
The streamCache should be removed (as it is no longer used and probably imposes a significant amount of overhead). GET_CONTIGUOUS_TAIL and STREAM_READ should also be deprecated in favor of log virtualization for replex.
