### ISSUE TITLE
Integration tests are not running with local "mvn clean install"

### ISSUE THREAD

**Issue by WenbinZhu** [CorfuDB/CorfuDB#2012]
## Overview

Looks like a local `mvn clean install` is not triggering integration tests, but travis is correctly triggering it.

**Comment by WenbinZhu** [comment]
@xnull Any thoughts on this?

**Comment by xnull** [comment]
If you mean `universe` tests, then yes, we don't trigger them by default.
See https://github.com/CorfuDB/CorfuDB/blob/382503b78d35b198d8ddf7bbeb0c282a235017d0/.travis.yml#L31

**Comment by WenbinZhu** [comment]
> If you mean `universe` tests, then yes, we don't trigger them by default.
> See
> 
> https://github.com/CorfuDB/CorfuDB/blob/382503b78d35b198d8ddf7bbeb0c282a235017d0/.travis.yml#L31

No, it's not just universe tests, it's all the integration tests, like ServerRestartIT, WorkflowIT

**Comment by WenbinZhu** [comment]
Workaround is to use `-Pit` flag after `mvn clean install`
