### ISSUE TITLE
StreamsView::append uses conflictKey/conflictStream from a stale tokenResponse

### ISSUE THREAD

**Issue by WenbinZhu** [CorfuDB/CorfuDB#2042]
## Overview

On OverwriteException, StreamsView::append will grab a new token and retry, however the current implementation uses the conflict info from the old tokenResponse. In case of transaction, if we encounter an OverwriteException, that means the there was no conflict transactions, and the conflictKey/conflictStream returned from sequencer is empty, however when we grab a new token, there could be a conflict, so using the conflictKey/conflictStream could result in something like this:

```
org.corfudb.runtime.exceptions.TransactionAbortedException: TX ABORT  | Snapshot Time = Token(epoch=388, sequence=1681679) | Failed Transaction ID = 905a3651-2377-4676-8794-XXXXX | Offending Address = 1681732 | Conflict Key =  | Conflict Stream = 00000000-0000-0000-0000-000000000000 | Cause = CONFLICT | Time = 7543 ms
```

The cause  is CONFLICT, but Conflict Key and Conflict Stream are empty, which is because we used the information from a stale response.

**Comment by Maithem** [comment]
Addressed.
