### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by medhavidhawan** [CorfuDB/CorfuDB#209]
The following test fails at times

Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.152 sec <<< FAILURE! - in org.corfudb.runtime.view.AddressSpaceViewTest
cacheMissTimesOut(org.corfudb.runtime.view.AddressSpaceViewTest) Time elapsed: 0.122 sec <<< FAILURE!
org.junit.ComparisonFailure: expected:<[FILLED_HOLE]> but was:<[EMPTY]>
  at org.corfudb.runtime.view.AddressSpaceViewTest.cacheMissTimesOut(AddressSpaceViewTest.java:40)

**Comment by slfritchie** [comment]
November review: I don't think that this error has happened in the last several weeks, please reopen Medhavi if I'm wrong.  Closing.
