### ISSUE TITLE
The tutorial uses outdated pom dependency setup

### ISSUE THREAD

**Issue by giorgioercixu** [CorfuDB/CorfuDB#2121]
In the last section of the tutorial, it goes:
`<dependency>
    <groupId>org.corfudb</groupId>
    <artifactId>runtime</artifactId>
    <version>0.1-SNAPSHOT</version>
    <scope>compile</scope>
</dependency> `

Directly using this setup incurs an error when launching the app,
causing the server unable to deserialize the corfumsg, such as follows: 

io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Attempt to deserialize a message which is not a CorfuMsg, Marker = 0 but expected 0xC0FC0FC0

The fix is to change the pom.xml to latest version:
`<dependency>
    <groupId>org.corfudb</groupId>
    <artifactId>runtime</artifactId>
    <version>0.3.0-SNAPSHOT</version>
    <scope>compile</scope>
</dependency> `

**Comment by WenbinZhu** [comment]
Thanks Giorgio, we have a recent PR for this issue: #2119

**Comment by jostep** [comment]
Thanks. I didn't notice that pull request earlier. Also, the github repo has been difficult to reach from mainland China (unlike apache maven or clojar.org which are mirrored in Alibaba Cloud). Is it possible for CorfuDB mvn repo to be hosted elsewhere? Thanks.
