### ISSUE TITLE
SMRMap vs. FGMap: values() result differs

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#213]
Found using the QuickCheck model at commit https://github.com/slfritchie/CorfuDB/commit/8653852f50efd5e30932c3448dadba60d694df27

Summary:
- The `FGMap` implementation of `values()` appears to list only unique values.
- The `SMRMap` implementation of `values()` appears to list all values.

QuickCheck output:

```
Reason:
  Post-condition failed:
  false
Shrinking xxxxx.x.xx.x.....xxxx..xxx(10 times)
[...]

map_qc:reset({cmdlet0, 'corfu-8000@sbb5'}, "sbb5:8000") -> ["OK"]
map_qc:put({cmdlet5, 'corfu-8000@sbb5'}, "sbb5:8000", 42, fgmap, "b",
    "Another-value") ->
  ["OK"]
map_qc:put({cmdlet3, 'corfu-8000@sbb5'}, "sbb5:8000", 42, fgmap, "a",
    "Another-value") ->
  ["OK"]
map_qc:values({cmdlet8, 'corfu-8000@sbb5'}, "sbb5:8000", 42, fgmap) ->
  ["OK", "[Another-value]"]

Reason:
  Post-condition failed:
  false
```

Tested using:

```
eqc:quickcheck(eqc:testing_time(5*60, map_qc:prop(fgmap, 1))).
```

Example using an `SMRMap` object:

```
(qc@sbb5)15> smrmap_qc:clear({cmdlet2, 'corfu-8000@sbb5'}, "sbb5:8000", 50, smrmap).            
["OK"]
(qc@sbb5)16> smrmap_qc:put({cmdlet2, 'corfu-8000@sbb5'}, "sbb5:8000", 50, smrmap, "key1", "value").
["OK"]
(qc@sbb5)17> smrmap_qc:put({cmdlet2, 'corfu-8000@sbb5'}, "sbb5:8000", 50, smrmap, "key2", "value").
["OK"]
(qc@sbb5)18> smrmap_qc:values({cmdlet2, 'corfu-8000@sbb5'}, "sbb5:8000", 50, smrmap).              
["OK","[value, value]"]
```

**Comment by slfritchie** [comment]
Waiting for an opinion from @no2chem, though he's busy with VMworld events for the next few days.  Ditto for @dahliamalkhi, if she has an opinion.

After discussing with @Maithem, we both agree that preserving duplicate values feels less "destructive", i.e. we'd prefer not to throw away info about duplicate values.  We'd prefer that `FGMap` match `SMRMap`'s behavior ... but we aren't 100% sure if there hidden uses & assumptions of `FGMap` on the current behavior.

**Comment by slfritchie** [comment]
November review: ping @no2chem @dahliamalkhi and @medhavidhawan ... If the API for FGMap.values() (which returns duplicates) to match SMRMap.value() (which does not return duplicates), will the cost be too high to fix app that use FGMap.values()?  Or if we change SMRMap's behavior to match FGMap's?

**Comment by dahliamalkhi** [comment]
I'd wait for the AnnotationProcessor branch for further discussion on this. Generally, I believe there is no longer need for FGMap after it is merged .

**Comment by no2chem** [comment]
This is because FGMap.values() implementation calls toSet(). It seems that the behavior could just be changed to call toList().

**Comment by slfritchie** [comment]
Mid-June issues review: @dahliamalkhi suggested that we drop FGMap.  @medhavidhawan @Maithem @no2chem, thoughts?

**Comment by Maithem** [comment]
+1 Dahlia's suggestion

**Comment by Maithem** [comment]
Re-open if needed.
