### ISSUE TITLE
CorfuGuidGenerator causes many transactional abort-retries

### ISSUE THREAD

**Issue by hisundar** [CorfuDB/CorfuDB#2152]
In a highly multi-threaded CorfuQueue environment, the CorfuGuidGenerator itself creates a new transaction which gets nested. If there are many users of the Queue, then the guid generator becomes a cause of transactional abort since it touches only one key.

Some critical requirements needed to address are:
1. Avoid using a transaction as much as possible
2. Use a singleton class for the generator

**Comment by WenbinZhu** [comment]
Addressed in #2153
