### ISSUE TITLE
Can't Reboot Cluster

### ISSUE THREAD

**Issue by RichardFeynmanCodes** [CorfuDB/CorfuDB#2209]
**Bug report.**
Cluster Can't recover after node restart. Steps to recreate:
1. Create a two node cluster given the steps here [https://github.com/CorfuDB/CorfuDB/blob/master/README.md](url)
2. Restart one of the nodes

**Observation**
The cluster can't process requests and one of the nodes keeps failing with the following exception:

>  | WARN  |                 CorfuRuntime-0 | o.corfudb.runtime.CorfuRuntime | Tried to get layout from localhost:9001 but failed with exception:
java.util.concurrent.ExecutionException: org.corfudb.runtime.exceptions.NoBootstrapException: Layout server not bootstrapped!
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)

**Expected**
The cluster should still be able to accept and process read/write requests after rebooting one of the nodes.

**Comment by Maithem** [comment]
Are you starting the nodes in memory mode?

If a node starts in memory mode, it will lose its configuration on reboot. Try starting the servers with the `-l <path` option
