### ISSUE TITLE
LayoutView: Prepare and Propose Issue

### ISSUE THREAD

**Issue by zhangn49** [CorfuDB/CorfuDB#2312]
## Overview

[CompletableFuture.anyOf](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html#anyOf-java.util.concurrent.CompletableFuture...-) returns a new CompletableFuture, but following logic (line 151 - 154) could remove multiple cfs that completed with exceptions.

## Code Segment
https://github.com/CorfuDB/CorfuDB/blob/671c55568feba427e327bdb89fa1f4409ca5bb2a/runtime/src/main/java/org/corfudb/runtime/view/LayoutView.java#L140-L154

## Explanation 
Let's assume we have prepareList [cf1, cf2, cf3], where cf1 is done normally, cf2 is completed with OutrankedException, cf3 is timeout.

If anyOf returns cf1, the stream operation will remove cf2 and cf3. In this case, it swallows TimeoutException, which makes timeout counter not accurate, and OutrankedException, which makes proposer stuck with a lower rank if OutrankedException is majority.

Besides, if some cfs are not completed yet, the while loop will keep consuming cpu time, because it does not remove completed cf1 from the list, and `CFUtils.getUninterruptibly(CompletableFuture.anyOf(prepareList))` returns immediately.

## More Concerns
For current implementation, we do not catch OutrankedException in prepare and propose. If the anyOf happens to return a cf with OutrankedException, prepare/propose phase will be terminated, which does not comply with Paxos.

**Comment by medhavidhawan** [comment]
I am not sure if I understand this completely. I understand the concerns but removal of anyof makes the implementation susceptible to the slowest responder.
