### ISSUE TITLE
Check pointing / disaster recovery

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#232]
Complete checkpointing for 1.0 release.

**Comment by slfritchie** [comment]
For (partial) background, see https://github.com/CorfuDB/CorfuDB/wiki/Object-checkpointing:-a-proposal-and-QuickCheck-model

**Comment by Maithem** [comment]
fyi: I started working on this

**Comment by no2chem** [comment]
11/29 : need to clarify what happens on a restored log which has diverged from it's previous state. (for example, if restore reverts back to version 100 from version 110). Clients will need to crash.

**Comment by slfritchie** [comment]
Checkpoint & trim (via a prefix trim of global address [0..Prefix]) have now been implemented by #669, #662, and related PRs.
