### ISSUE TITLE
Corfu IT tests are broken on Mac OS X 10.15+

### ISSUE THREAD

**Issue by hisundar** [CorfuDB/CorfuDB#2328]
Starting with Mac OS X version 10.15 the temporary directory returned by `System.getProperty("java.io.tmpdir")` has read-only permissions on the parent filesystem.
LogUnitServer in corfu however fails to come up if the filesystem is read-only.
This prevents CorfuServer from being tested on Mac OS X 10.15+ and it fails with exception like this
`Cannot start Corfu on a read-only filesystem: /var/folders/qx/045nmsxx55575_gqycvvs1480000gp/T/1580163123321-0`
Note that while the parent filesystem indicates that it is read-only, the actual corfu log directories are still writable, so testing the parent filesystem for writability might be a false panic.

**Comment by Maithem** [comment]
Fix merged.
