### ISSUE TITLE
Security for Corfu (> TLS 1.1 and AAA)

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#233]
Complete Security for Corfu (> TLS 1.1 and AAA)

**Comment by sneginhal** [comment]
Proposal:
Client<->Server:
* Use TLS for securing the communication.
* SASL for Authentication, start with PLAIN eventually support Kerberos V5.

Server<->Server:
* Use TLS for securing the communication.
* SASL for Authentication, use Digest-MD5 

TLS:
Netty provides a SslHandler.
Work will involve setting up a SSL context.
We can use a local Java keystore to feed the KeyManager and TrustManager.

SASL:
Netty does not provide a SASL Handler yet:
https://github.com/netty/netty/issues/1966

Work will involve implementing the handlers.

**Comment by no2chem** [comment]
Okay, but is there a way we can keep the encryption flexible? 

Can we: 
1) add a SecurityContext field to NettyClientRouter/NettyServerRouter
2) for each client router the server router keeps a security context
3) a negotiation protocol (please elaborate on this one) sets up the context between the client and the server

Finally, why Digest-MD5? We should avoid using out of date algorithms, or better yet, keep the mechanism flexible so we can add additional crypto as necessary.

**Comment by sneginhal** [comment]
What do you mean by keep encryption flexible? Enable/Disable or do you want more than that?

We can do PLAIN for server-server as well.

I was planning on adding The SASL and SSL handlers to the pipeline in the CorfuServer and the NettyClientRouter.
Once the context is setup, it will be per channel and the SslHandler should take care of the handshake.

**Comment by slfritchie** [comment]
For background, see also:

* https://github.com/CorfuDB/CorfuDB/wiki/Crypto-and-Corfu (including links in the "see also" at the end)
* https://github.com/CorfuDB/CorfuDB/wiki/AAA:-Authentication,-Authorization,-and-Accounting

**Comment by no2chem** [comment]
@sneginhal 

By keep encryption flexible, I mean be able to select other encryption mechanisms, such as picking between different ciphers in TLS. Have you made any progress on the issue?

**Comment by slfritchie** [comment]
Mid-June issues review: implemented by #417
