### ISSUE TITLE
Runtime Metrics/Stats

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#234]
Add runtime metrics / stats

**Comment by medhavidhawan** [comment]
1. Need to figure out the metrics library to use.
Potential candidate is DropWizard.
2. Need to figure out what metrics we need to monitor corfu.
3. Need to figure out a scheme for exposing these metrics to the end user so that they can manage the  cluster.

**Comment by medhavidhawan** [comment]
Rough time estimate would be 2 weeks to come up with a first cut.

**Comment by slfritchie** [comment]
For background, see also: https://github.com/CorfuDB/CorfuDB/wiki/Runtime-Statistics-&-Metrics

**Comment by slfritchie** [comment]
Resolved by #444
