### ISSUE TITLE
Failure Detector

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#237]
Add failure detector for Corfu

**Comment by zalokhan** [comment]
The failure detector will be a part of the Management Server of Corfu.

Completed creating a ManagementServer instance from Corfu Server bootstrapped to initial layout.
Tasks in progress:
Detecting and resolving failed nodes.

**Comment by slfritchie** [comment]
For background, see also:

* https://github.com/CorfuDB/CorfuDB/wiki/Configuration-Manager-notes%3A-failure-detection-%26-reacting-to-failure
* https://github.com/CorfuDB/CorfuDB/wiki/Log-unit-recovery-from-failure
* https://github.com/CorfuDB/CorfuDB/wiki/Chain-Repair-%28lengthening%29-proposal%3A-description-%26-modeling

**Comment by medhavidhawan** [comment]
Please do not merge. I will review it in the next one day or so.

**Comment by Maithem** [comment]
Completed.
