### ISSUE TITLE
Lifecycle Management

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#238]
Add Lifecycle management

**Comment by medhavidhawan** [comment]
1. Research and Design the various corfu lifecycle workflows. What technology to use ?

**Comment by medhavidhawan** [comment]
Need to look at Cello that is being developed inside vmware.
Need to look deeper into policies for reconfiguration, extra nodes, etc.

**Comment by slfritchie** [comment]
For (partial) background, see also:

* https://github.com/CorfuDB/CorfuDB/wiki/Log-replica-placement-policies
* https://github.com/CorfuDB/CorfuDB/wiki/Alarms%2C-Events%2C-and-Alarm-%26-Event-Management

**Comment by slfritchie** [comment]
Mid-June issues review: Implemented by #552, #658, and related PRs.  If there are missing tasks outside of the scope of those PRs, let's open new issues to track them.
