### ISSUE TITLE
systemDownHandler blocks runtime trying in vain to reconnect to WrongCluster

### ISSUE THREAD

**Issue by hisundar** [CorfuDB/CorfuDB#2409]
## Overview

CorfuRuntime will throw a WrongClusterException if it is trying to connect to the cluster with a wrong clusterId. Normally this happens when there is a reconfiguration event and the old cluster is no longer valid. In such circumstances, the systemDownHandler should quickly give up instead of trying to reconnect to the wrong cluster otherwise this will hold up the process and prevent it from restarting.

**Comment by Maithem** [comment]
WrongClusterException is a non-retriable error it should be propagated.
