### ISSUE TITLE
Reproducible Replex + "io.netty.util.IllegalReferenceCountException: refCnt: 0" in 2 ops

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#246]
Found on the `slf/map-qc-with-replex` branch at commit 43f4d741f2804c4ae70c7a45ae82576cd0ea52ec, using Replex + SMRmap.  The deterministic counterexample ... note that two different client runtimes are required (the 1st arg to the `put()` functions, e.g. `cmdlet3` and `cmdlet8`):

    C2 = [[{init,{state,smrmap,"sfritchie-m01:8000",
                        [cmdlet0,cmdlet1,cmdlet2,cmdlet3,cmdlet4,cmdlet5,cmdlet6,
                         cmdlet7,cmdlet8,cmdlet9],
                        false,42,[]}},
           {set,{var,1},
                {call,map_qc,reset,
                      [{cmdlet3,'corfu-8000@sfritchie-m01'},
                       "sfritchie-m01:8000"]}},
           {set,{var,2},
                {call,map_qc,put,
                      [{cmdlet3,'corfu-8000@sfritchie-m01'},
                       "sfritchie-m01:8000",42,smrmap,"a","Another-value"]}},
           {set,{var,3},
                {call,map_qc,put,
                      [{cmdlet8,'corfu-8000@sfritchie-m01'},
                       "sfritchie-m01:8000",42,smrmap,"l","Hello-world!"]}}]].

Run using:

    ./Build.sh proper
    ./Build.sh proper-shell
    [... cut-and-paste the definition of C2 from above ...]
    proper:check(map_qc:prop(), C2).

The result:

    H: [{{state,smrmap,"sfritchie-m01:8000",
                [cmdlet0,cmdlet1,cmdlet2,cmdlet3,cmdlet4,cmdlet5,cmdlet6,cmdlet7,
                 cmdlet8,cmdlet9],
                false,42,[]},
         ["OK"]},
        {{state,smrmap,"sfritchie-m01:8000",
                [cmdlet0,cmdlet1,cmdlet2,cmdlet3,cmdlet4,cmdlet5,cmdlet6,cmdlet7,
                 cmdlet8,cmdlet9],
                true,42,[]},
         ["OK"]},
        {{state,smrmap,"sfritchie-m01:8000",
                [cmdlet0,cmdlet1,cmdlet2,cmdlet3,cmdlet4,cmdlet5,cmdlet6,cmdlet7,
                 cmdlet8,cmdlet9],
                true,42,
                [{"a","Another-value"}]},
         ["ERROR","exception","InvocationTargetException",
          "stack: java.lang.reflect.InvocationTargetException\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.corfudb.cmdlets.corfu_smrobject.main(corfu_smrobject.java:173)\n\tat org.corfudb.cmdlets.CmdletRouter.main2(CmdletRouter.java:52)\n\tat org.corfudb.cmdlets.QuickCheckMode.runErlMbox(QuickCheckMode.java:123)\n\tat org.corfudb.cmdlets.QuickCheckMode.runErlMbox8(QuickCheckMode.java:83)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: io.netty.util.IllegalReferenceCountException: refCnt: 0\n\tat io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1407)\n\tat io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1353)\n\tat io.netty.buffer.UnsafeByteBufUtil.getBytes(UnsafeByteBufUtil.java:509)\n\tat io.netty.buffer.PooledUnsafeDirectByteBuf.getBytes(PooledUnsafeDirectByteBuf.java:131)\n\tat io.netty.buffer.PooledSlicedByteBuf.getBytes(PooledSlicedByteBuf.java:239)\n\tat io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:851)\n\tat org.corfudb.protocols.logprotocol.SMREntry.deserializeBuffer(SMREntry.java:60)\n\tat org.corfudb.protocols.logprotocol.LogEntry.deserialize(LogEntry.java:71)\n\tat org.corfudb.util.serializer.CorfuSerializer.deserialize(CorfuSerializer.java:34)\n\tat org.corfudb.protocols.wireprotocol.LogData.getPayload(LogData.java:45)\n\tat org.corfudb.runtime.object.CorfuSMRObjectProxy.lambda$sync$8(CorfuSMRObjectProxy.java:413)\n\tat java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)\n\tat java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)\n\tat java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)\n\tat java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)\n\tat java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)\n\tat java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)\n\tat java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)\n\tat java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n\tat java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)\n\tat org.corfudb.runtime.object.CorfuSMRObjectProxy.sync(CorfuSMRObjectProxy.java:414)\n\tat org.corfudb.runtime.object.CorfuSMRObjectProxy.interceptMutatorAccessor(CorfuSMRObjectProxy.java:250)\n\tat org.corfudb.runtime.collections.SMRMap$ByteBuddy$g2GQ00Sv.put(Unknown Source)\n\t... 9 more\n",
          "cause: io.netty.util.IllegalReferenceCountException: refCnt: 0"]}]
    S: {state,smrmap,"sfritchie-m01:8000",
              [cmdlet0,cmdlet1,cmdlet2,cmdlet3,cmdlet4,cmdlet5,cmdlet6,cmdlet7,
               cmdlet8,cmdlet9],
              true,42,
              [{"a","Another-value"}]}
    R: {postcondition,
           {exception,error,
               {case_clause,
                   ["ERROR","exception","InvocationTargetException",
                    "stack: java.lang.reflect.InvocationTargetException\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.corfudb.cmdlets.corfu_smrobject.main(corfu_smrobject.java:173)\n\tat org.corfudb.cmdlets.CmdletRouter.main2(CmdletRouter.java:52)\n\tat org.corfudb.cmdlets.QuickCheckMode.runErlMbox(QuickCheckMode.java:123)\n\tat org.corfudb.cmdlets.QuickCheckMode.runErlMbox8(QuickCheckMode.java:83)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: io.netty.util.IllegalReferenceCountException: refCnt: 0\n\tat io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1407)\n\tat io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1353)\n\tat io.netty.buffer.UnsafeByteBufUtil.getBytes(UnsafeByteBufUtil.java:509)\n\tat io.netty.buffer.PooledUnsafeDirectByteBuf.getBytes(PooledUnsafeDirectByteBuf.java:131)\n\tat io.netty.buffer.PooledSlicedByteBuf.getBytes(PooledSlicedByteBuf.java:239)\n\tat io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:851)\n\tat org.corfudb.protocols.logprotocol.SMREntry.deserializeBuffer(SMREntry.java:60)\n\tat org.corfudb.protocols.logprotocol.LogEntry.deserialize(LogEntry.java:71)\n\tat org.corfudb.util.serializer.CorfuSerializer.deserialize(CorfuSerializer.java:34)\n\tat org.corfudb.protocols.wireprotocol.LogData.getPayload(LogData.java:45)\n\tat org.corfudb.runtime.object.CorfuSMRObjectProxy.lambda$sync$8(CorfuSMRObjectProxy.java:413)\n\tat java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)\n\tat java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)\n\tat java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)\n\tat java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)\n\tat java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)\n\tat java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)\n\tat java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)\n\tat java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n\tat java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)\n\tat org.corfudb.runtime.object.CorfuSMRObjectProxy.sync(CorfuSMRObjectProxy.java:414)\n\tat org.corfudb.runtime.object.CorfuSMRObjectProxy.interceptMutatorAccessor(CorfuSMRObjectProxy.java:250)\n\tat org.corfudb.runtime.collections.SMRMap$ByteBuddy$g2GQ00Sv.put(Unknown Source)\n\t... 9 more\n",
                    "cause: io.netty.util.IllegalReferenceCountException: refCnt: 0"]},
               [{map_qc,postcondition,3,[{file,"src/map_qc.erl"},{line,134}]},
                {proper_statem,check_postcondition,4,
                    [{file,"src/proper_statem.erl"},{line,568}]},
                {proper_statem,run_commands,5,
                    [{file,"src/proper_statem.erl"},{line,537}]},
                {proper_statem,run_commands,3,
                    [{file,"src/proper_statem.erl"},{line,502}]},
                {map_qc,'-prop/4-fun-3-',1,[{file,"src/map_qc.erl"},{line,304}]},
                {proper,apply_args,3,[{file,"src/proper.erl"},{line,1353}]},
                {proper,retry,3,[{file,"src/proper.erl"},{line,1040}]},
                {erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,674}]}]}}
    false

**Comment by slfritchie** [comment]
I've found a smaller counter-example that uses only a single client ... this can also be reproduced using the `corfu_smrobject` cmdlets in part (after configuring layout to use Replex replication ... I don't see the error when in chain replication mode, oddly enough).

    C11 = [[{init,{state,smrmap,"sfritchie-m01:8000",
                         [cmdlet0,cmdlet1,cmdlet2,cmdlet3,cmdlet4,cmdlet5,cmdlet6,
                          cmdlet7,cmdlet8,cmdlet9],
                         false,42,[]}},
            {set,{var,1},
                 {call,map_qc,reset,
                       [{cmdlet0,'corfu-8000@sfritchie-m01'},
                        "sfritchie-m01:8000"]}},
            {set,{var,4},
                 {call,map_qc,clear,
                       [{cmdlet0,'corfu-8000@sfritchie-m01'},
                        "sfritchie-m01:8000",42,smrmap]}},
            {set,{var,5},
                 {call,map_qc,remove,
                       [{cmdlet0,'corfu-8000@sfritchie-m01'},
                        "sfritchie-m01:8000",42,smrmap,"p"]}}]].

**Comment by amytai** [comment]
Ah yes, the eternal reference count exceptions. Can you parse the Erlang and specify what commands are being run, i.e. how do I reproduce this error in Java?

**Comment by slfritchie** [comment]
./bin/corfu_smrobject -c localhost:8000 -s 42 org.corfudb.runtime.collections.SMRMap clear
    ./bin/corfu_smrobject -c localhost:8000 -s 42 org.corfudb.runtime.collections.SMRMap remove p

**Comment by slfritchie** [comment]
@amytai I'm not 100% sure that my new QuickCheck branch is/isn't required to trigger this ... because I still rely on a bit of glue code to set up the Replex layout.  But if I use the Erlang<->Java glue to reset the server state & commit a Replex layout, then those two cmdlet commands will indeed cause the failure.

**Comment by slfritchie** [comment]
See PR #247 for definitely 100% reproducibility, at least for OS X.  The instructions in the README at https://github.com/CorfuDB/CorfuDB/tree/master/src/test/erlang are pretty cut-and-paste'able for a Debian/Ubuntu system.

**Comment by amytai** [comment]
Looks like there's a problem with the bulk-reads functionality. Stay tuned..
