### ISSUE TITLE
layout_qc.erl: Expose clientId to QuickCheck

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#252]
This is a "don't forget to change this" item for the QuickCheck test layout_qc.erl.

To allow for deterministic rank comparison/prediction by QuickCheck, I'd earlier commented some code over in `Rank.java`, namely here: https://github.com/slfritchie/CorfuDB/blob/qc-update-layout2.medhavi-test-experiment/src/main/java/org/corfudb/infrastructure/Rank.java#L32-L55

For the 1.0 release, Medhavi's commented code must be restored. The Paxos rank comparisons will be far better to reason about, namely rank uniqueness across all clients.  I haven't thought this through 100% yet, but last night while riding home on the train this outline seems reasonable.
- For each client that's controlled by the QuickCheck puppeteer, add an API call to expose the clientId string to QuickCheck glue code
- For the QuickCheck reset process, add a call to the new API to query all clientIds and store them in model state.
- Create an Erlang function equivalent to the highlighted Java code in the URL above for rank comparison.
- Use the new Erlang rank comparison function in all cases where the model today is comparing ranks.

**Comment by no2chem** [comment]
This doesn't seem like a requirement for the 1.0 milestone, so I've removed it.

**Comment by slfritchie** [comment]
Mid-June issues review: unsupported feature
