### ISSUE TITLE
Support Switchover on Non-leader LR

### ISSUE THREAD

**Issue by annym** [CorfuDB/CorfuDB#2624]
## Overview

We need a means to reply from a non-leader LR when the switchover workflow is triggered from this. We can approach this by periodically persisting the replication status in the metadata table and accessing this table in the queryReplicationStatus API.

**Comment by xiaoqin2012** [comment]
There are two clusters: A (active) and B (standby). While B is planning to transition from standby to active role, cluster A's site manager will query LR for log replication status. 
The metadata at the cluster B records the replication status. 
1. In snapshot sync.
2. In delta sync. (only this implemented today) 

Option for implementation:
1. Any LR node at cluster A can send a query message to a node at cluster B to get the log replication status
2. Comparing the query result with its own log tail and do the proper calculation.

**Comment by pankti-m** [comment]
> There are two clusters: A (active) and B (standby). While B is planning to transition from standby to active role, cluster A's site manager will query LR for log replication status.
> The metadata at the cluster B records the replication status.
> 
>     1. In snapshot sync.
> 
>     2. In delta sync. (only this implemented today)
> 
> 
> Option for implementation:
> 
>     1. Any LR node at cluster A can send a query message to a node at cluster B to get the log replication status
> 
>     2. Comparing the query result with its own log tail and do the proper calculation.

Does this mean we do not have metadata on the active to tell the snapshot sync progress?

**Comment by xiaoqin2012** [comment]
The current log replication metadata is per cluster and record the replication status if it is a standby cluster.
