### ISSUE TITLE
invalidateLayout race condition

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#264]
CorfuRuntime has a layout global variable that can be modified by different threads this can result in a race condition where different layout versions can interleave causing the epoch version to regress for some routers:
https://github.com/CorfuDB/CorfuDB/blob/master/src/main/java/org/corfudb/runtime/CorfuRuntime.java#L290

**Comment by dahliamalkhi** [comment]
Looking at the code, handleMessageSetEpoch in LayoutServer already checks that the epoch is not set backward. 

So the only remaining issue is the one pointed here.

**Comment by Maithem** [comment]
@no2chem Is there a good reason to have fetch layout run asynchronously ? If a layout is required and the client can't fetch one, then progress cannot be made, is that right?

I wan't to make it synchronous because we have had concurrency problems in the past because of this. Race conditions can also happen in the current code.

**Comment by no2chem** [comment]
Shouldn't this be fixed if invalidateLayout is marked synchronized?

In the meantime, we probably need to re-think the software engineering for the runtime layout mechanism.

**Comment by Maithem** [comment]
@no2chem I think so.

I wanted to refactor some code to, the way the layout future is leaked all over the place is not good.

I'll just submit a patch to make invalidateLayout synchronized and then w can revisit this problem later
