### ISSUE TITLE
remove debugging code inside NettyRouter

### ISSUE THREAD

**Issue by dahliamalkhi** [CorfuDB/CorfuDB#265]
@slfritchie [https://github.com/CorfuDB/CorfuDB/blame/master/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java#L75](url)

**Comment by no2chem** [comment]
@slfritchie do you plan on working on this? I think the line was here. 
https://github.com/CorfuDB/CorfuDB/blob/master/infrastructure/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java#L77

**Comment by slfritchie** [comment]
Mid-June issues review: already removed
