### ISSUE TITLE
Allow multiple custom serializers

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#266]
Once the custom serializer is set, it cannot be changed, its almost like a global static variable. Initially, we made this decision to safeguard from dynamically changing the custom serializer once it is set. Since the SMR can use this serialize bad things can happen if the serializer changes. 

This can be really annoying, think of test code where in the @Before method, it tries to setup a serializer.
Only the first invocation will set it and the subsequent ones will need to handle a Runtime Exception.

First of all, I think this is a structural problem, we should refactor the code in a way where we allow for multiple custom serializers. In the mean time, I think we should remove this check:
https://github.com/CorfuDB/CorfuDB/blob/f1cd5d96c186fca299286a63240fd6ae3c5a2c5e/src/main/java/org/corfudb/util/serializer/SerializerType.java#L25

and leave it to the discretion of the consumer until we do that refactor.

**Comment by no2chem** [comment]
Hm, this is interesting.

It seems that the right thing to do is create two maps of bytes->functions, where bytes enocde the serializer type and the user can register a function for any serializer type to perform serialization/deserialization. It doesn't seem to make sense to change the serialization functions for a given type after initialization, so I think we're spared from that step.

But maybe we should take a step back and ask whether we want to provide this level of flexibility... At the moment, I don't see what the harm is, though.

**Comment by Maithem** [comment]
We already have a ISerializer interface, shouldn't that be sufficient? 
I also don't see the need for a "registry" of serializers, I feel that it would be easier
and cleaner to just use ISerializer instances.
