### ISSUE TITLE
Inconsistent SMRMap

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#267]
@no2chem @dahliamalkhi 

The SMRMap doesn't enforce immutability on its in memory objects. As a consequence, the client's in memory state of the SMRMap can diverge from the persisted log. To illustrate this, I wrote this test:

https://github.com/Maithem/CorfuDB/commit/0139244afd2061f3ec74ab9d189d7dc3e51dc388#diff-a3d4c2fa410c1c7b2eeec3a6af584fa4R51

**Comment by no2chem** [comment]
Yes, that's a known problem. I wouldn't call it a bug. The only way to get around it would be to require all objects being put into the map be CorfuObjects, or automagically wrap objects being put into the map, which probably would be a performance hit. Do you want to explicitly prevent users from putting non-CorfuObjects in the map?

**Comment by Maithem** [comment]
Apparently, this is also a known issue in Java map implementation, keys can also leak if they are mutable. 

I guess its the users responsibility to be careful.
