### ISSUE TITLE
cacheMissTimesOut failing intermittently 

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#268]
https://github.com/CorfuDB/CorfuDB/blob/599d9b1881acee1ef47eaf58d98db24d7b1b2665/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java#L28

**Comment by no2chem** [comment]
This seems to be because of variable Travis-CI execution times and the timeout set too low. I'll put out a patch by increasing the timeout.

**Comment by no2chem** [comment]
Should be fixed by #276
