### ISSUE TITLE
verifyStateTransferWithChainHeadFailure Failing

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#2690]
**Bug report.** 
Test is failing, please take a look 
https://api.travis-ci.org/v3/job/716479941/log.txt

**Comment by xnull** [comment]
Tests run: 125, Failures: 0, Errors: 0, Skipped: 1
...
[INFO] BUILD SUCCESS
...
Done. Your build exited with 0.

which tests failing?

**Comment by Maithem** [comment]
Strange. Might have been a different log. 

Will re-open if I see it again.
