### ISSUE TITLE
Apparent regression after PR #263: race in hole fill

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#273]
This appears to be a regression after the merge of #263. In the parallel version of QuickCheck test for the SMRMap, there's an occasional error where an exception is thrown server-side in a race with a hole fill.  @Maithem, could you take a peek?  This appears to destabilize any concurrent updates to `SMRMap` objects.

The problem is quite non-deterministic, it's much easier to see when using the default logging level.  For detailed trace, reproduce using.

Server:

    % ./bin/corfu_server -Q -l /tmp/some/path -s 8000 --cm-poll-interval=99999 -d TRACE > & foo

Client, which performs random valid API ops from the `SMRMap` API.  All ops are using the same streamID and thus same `SMRMap` object.

    % cd src/test/erlang
    % ./Build.sh proper
    % ./Build.sh proper-shell
    > proper:quickcheck(proper:numtests(2000, map_qc:prop_parallel()), [noshrink]).

... and then wait for a `WARN` level message in the `foo` log file mentioning:

     17:50:21.760 ERROR [event-5] o.c.i.l.StreamLogFiles - Disk_write[0]: Exception
     org.corfudb.runtime.exceptions.OverwriteException: null
            at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:208)

Note that this usually happens at log offset 0, but I have seen it happen rarely at other offsets (e.g. 3 or 12).

At standard trace level, the output can look like this:

     17:50:21.524 WARN  [DistErl-8] o.c.i.SequencerServer - Sequencer recovery requested but checkpoint not set, defaulting to 0
     17:50:21.752 INFO  [event-5] o.c.i.l.StreamLogFiles - Opened new log file at /tmp/some/path/log0
     17:50:21.752 INFO  [event-11] o.c.i.l.StreamLogFiles - Disk_write[0]: Written to disk.
     17:50:21.760 ERROR [event-5] o.c.i.l.StreamLogFiles - Disk_write[0]: Exception
     org.corfudb.runtime.exceptions.OverwriteException: null
            at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:208)
    17:50:21.761 ERROR [event-5] o.c.i.NettyServerRouter - Exception during read!
     java.lang.RuntimeException: org.corfudb.runtime.exceptions.OverwriteException
            at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:213)
    Caused by: org.corfudb.runtime.exceptions.OverwriteException: null
            at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:208)
    17:50:21.768 INFO  [event-1] o.c.i.l.StreamLogFiles - Disk_write[1]: Written to disk.
     17:50:21.783 INFO  [event-15] o.c.i.l.StreamLogFiles - Disk_write[2]: Written to disk.
     17:50:26.758 WARN  [DistErl-1] o.c.r.v.AbstractView - Timeout executing remote call, invalidating view and retrying in 5s
     17:50:31.764 ERROR [event-5] o.c.i.l.StreamLogFiles - Disk_write[0]: Exception
     org.corfudb.runtime.exceptions.OverwriteException: null
            at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:208)
    17:50:31.764 ERROR [event-5] o.c.i.NettyServerRouter - Exception during read!
     java.lang.RuntimeException: org.corfudb.runtime.exceptions.OverwriteException
            at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:213)
    Caused by: org.corfudb.runtime.exceptions.OverwriteException: null
            at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:208)
    17:50:33.753 INFO  [event-13] o.c.i.l.StreamLogFiles - Disk_write[3]: Written to disk.

For a `TRACE` level log, see https://gist.github.com/slfritchie/eac869fd354eeda4a1bbc56db995cd57

**Comment by Maithem** [comment]
@slfritchie Thanks for reporting.
Can you also attach the test case?

**Comment by slfritchie** [comment]
Maithem, there is no single test case. It's all random chance in a race, as
far as I can tell. It's easy to generate the needed load, using QC.

QC is currently using all (10+, I forget the count) API functions in the
SMRMap. I could try to reduce the API range if there is a smaller fraction
of the ops that can still trigger it. And also using some printf() to see
how many concurrent updates to the map are necessary.

-Scott

**Comment by slfritchie** [comment]
FWIW, issue #201 still pops up regularly, usually in the first few seconds.

**Comment by slfritchie** [comment]
Yay, I've got a case that uses only two concurrent load generators, and it only uses get & put ops on a single SMRMap object.  It also needs only two `CorfuRuntime` environments, one for exclusive use by each load gen thread.  The syntax below is a still a bit Erlang-flavored, but I hope it's clear what each function is doing.  All ops are against only one SMRMap that uses streamID=42.

    Concurrent load gen #1:
    get, [{cmdlet0,"a"]
    put, [{cmdlet0,"l","Hello-world!"]
    get, [{cmdlet0,"v"]
    put, [{cmdlet0,"a","Another-value"]
    
    Concurrent load gen #2:
    put, [{cmdlet1,"n",""]
    put, [{cmdlet1,"a","Hello-world!"]

That's it.

In the QC/Erlang shell, cut-and-paste the following to find a smaller test case that (on my machine at home) can trigger the bug in under 10 seconds, usually.  Yes, it's ugly, but I stripped out the whitespace to make managing the text easier.

        C2 = [{[{init,{state,smrmap,[115,98,98,53,58,56,48,48,48],[cmdlet0,cmdlet1,cmdlet2,cmdlet3,cmdlet4,cmdlet5,cmdlet6,cmdlet7,cmdlet8,cmdlet9],false,42,[]}},{set,{var,1},{call,map_qc,reset,[{cmdlet0,'corfu-8000@sbb5'},[115,98,98,53,58,56,48,48,48]]}}],[[{set,{var,2},{call,map_qc,get,[{cmdlet0,'corfu-8000@sbb5'},[115,98,98,53,58,56,48,48,48],42,smrmap,[97]]}},{set,{var,3},{call,map_qc,put,[{cmdlet0,'corfu-8000@sbb5'},[115,98,98,53,58,56,48,48,48],42,smrmap,[108],[72,101,108,108,111,45,119,111,114,108,100,33]]}},{set,{var,4},{call,map_qc,get,[{cmdlet0,'corfu-8000@sbb5'},[115,98,98,53,58,56,48,48,48],42,smrmap,[118]]}},{set,{var,5},{call,map_qc,put,[{cmdlet0,'corfu-8000@sbb5'},[115,98,98,53,58,56,48,48,48],42,smrmap,[97],[65,110,111,116,104,101,114,45,118,97,108,117,101]]}}],[{set,{var,6},{call,map_qc,put,[{cmdlet1,'corfu-8000@sbb5'},[115,98,98,53,58,56,48,48,48],42,smrmap,[110],[]]}},{set,{var,7},{call,map_qc,put,[{cmdlet1,'corfu-8000@sbb5'},[115,98,98,53,58,56,48,48,48],42,smrmap,[97],[72,101,108,108,111,45,119,111,114,108,100,33]]}}]]}].
        [true = proper:check(map_qc:prop_parallel(), C2) || _ <- lists:seq(1,100)].

**Comment by slfritchie** [comment]
Sweet, I've written a Java-only reproducer.  It's hideously ugly, but it works.  It does indeed perform those two load thingies in a loop and runs them 10K times in a loop.  It usually triggers the hole fill bug we're looking for.

If it doesn't, then running it repeatedly will indeed get it.  In fact, as the SMRMap's history gets longer, it takes fewer put()s to trigger the bug.

The most important pieces of reproducing code are at https://gist.github.com/slfritchie/22d0b5a3083a5c6758ee9117948c608e.

**Comment by slfritchie** [comment]
I forgot to mention the client's behavior in all of this.  When the bug on the server side is triggered:

* Both threads are unable to perform more put() & get() ops

* The client logs these at 10 second intervals:

    01:11:00.417 WARN  [Thread-4] o.c.r.v.AbstractView - Timeout executing remote call, invalidating view and retrying in 5s
     01:11:10.426 WARN  [Thread-4] o.c.r.v.AbstractView - Timeout executing remote call, invalidating view and retrying in 5s
     01:11:20.432 WARN  [Thread-4] o.c.r.v.AbstractView - Timeout executing remote call, invalidating view and retrying in 5s
     01:11:30.437 WARN  [Thread-4] o.c.r.v.AbstractView - Timeout executing remote call, invalidating view and retrying in 5s
     01:11:40.443 WARN  [Thread-4] o.c.r.v.AbstractView - Timeout executing remote call, invalidating view and retrying in 5s

* The server logs these at 10 second intervals but offset from the client's complaints.

    01:10:55.417 ERROR [event-4] o.c.i.l.StreamLogFiles - Disk_write[646]: Exception
     org.corfudb.runtime.exceptions.OverwriteException: null
    	at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:208)
    01:10:55.417 ERROR [event-4] o.c.i.NettyServerRouter - Exception during read!
     java.lang.RuntimeException: org.corfudb.runtime.exceptions.OverwriteException
    	at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:213)
    Caused by: org.corfudb.runtime.exceptions.OverwriteException: null
    	at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:208)
    01:11:05.422 ERROR [event-4] o.c.i.l.StreamLogFiles - Disk_write[646]: Exception
     org.corfudb.runtime.exceptions.OverwriteException: null
    	at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:208)
    01:11:05.423 ERROR [event-4] o.c.i.NettyServerRouter - Exception during read!
     java.lang.RuntimeException: org.corfudb.runtime.exceptions.OverwriteException
    	at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:213)
    Caused by: org.corfudb.runtime.exceptions.OverwriteException: null
    	at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:208)
    01:11:15.429 ERROR [event-4] o.c.i.l.StreamLogFiles - Disk_write[646]: Exception
     org.corfudb.runtime.exceptions.OverwriteException: null
    	at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:208)
    01:11:15.430 ERROR [event-4] o.c.i.NettyServerRouter - Exception during read!
     java.lang.RuntimeException: org.corfudb.runtime.exceptions.OverwriteException
    	at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:213)
    Caused by: org.corfudb.runtime.exceptions.OverwriteException: null
    	at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:208)
    01:11:25.435 ERROR [event-4] o.c.i.l.StreamLogFiles - Disk_write[646]: Exception
     org.corfudb.runtime.exceptions.OverwriteException: null
    	at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:208)
    01:11:25.436 ERROR [event-4] o.c.i.NettyServerRouter - Exception during read!
     java.lang.RuntimeException: org.corfudb.runtime.exceptions.OverwriteException
    	at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:213)
    Caused by: org.corfudb.runtime.exceptions.OverwriteException: null
    	at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:208)
    01:11:35.439 ERROR [event-4] o.c.i.l.StreamLogFiles - Disk_write[646]: Exception
     org.corfudb.runtime.exceptions.OverwriteException: null
    	at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:208)
    01:11:35.440 ERROR [event-4] o.c.i.NettyServerRouter - Exception during read!
     java.lang.RuntimeException: org.corfudb.runtime.exceptions.OverwriteException
    	at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:213)
    Caused by: org.corfudb.runtime.exceptions.OverwriteException: null
    	at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:208)

**Comment by slfritchie** [comment]
I've created a reproducing client in Java, see the little branch at https://github.com/slfritchie/CorfuDB/tree/slf/repro-bug273

**Comment by slfritchie** [comment]
FYI, still happening on Nov 17's master branch at commit 170b77d1b1f8b9788fa9f552ce63e0c21bee784b.  (Which is a contrast to #288, which appears to have vanished after the big code reorganization.)

**Comment by Maithem** [comment]
Thanks for the update @slfritchie , I think that problem is caused by a timing issue. I'll look into it soon.

**Comment by slfritchie** [comment]
Found the problem, running tests now, a quick PR after lunch, sorry.
