### ISSUE TITLE
Random leak error message

### ISSUE THREAD

**Issue by dahliamalkhi** [CorfuDB/CorfuDB#274]
With the latest version on master, every time I run a very simple application (filling an SMRmap with 100K items, in various ways) I get the following error message once, at random points in the execution:

19:33:21.567 ERROR [org.corfudb.runtime.clients.NettyClientRouter$2event-0] i.n.u.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetection.level=advanced' or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html for more information.

Any idea what is causing it, and what it is causing?

@no2chem @Maithem @slfritchie

**Comment by slfritchie** [comment]
Ha, I just mentioned https://github.com/CorfuDB/CorfuDB/issues/273#issuecomment-258583621 a couple of hours ago.  I believe this is already reported in #201 from July.

**Comment by dahliamalkhi** [comment]
ah, correct. let me close all the extraneous ones..
