### ISSUE TITLE
Cluster Id Validation Is Expensive

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#2748]
**Bug report.**
Accessing the local data store on every message to validate the cluster id is really expensive because its serialized.
The RPC path should not participate in any expensive synchronization.

**Comment by WenbinZhu** [comment]
ClusterId is get from currentLayout, which most of the time is cached in memory, rigtht?

**Comment by Maithem** [comment]
The layout itself is cached, but its access with a `synchronized`

```java

@Override
    public synchronized <T> T get(KvRecord<T> key) {
        String path = key.getFullKeyName();
        Object val = cache.get(path, k -> {
            if (!inMem) {
                T loadedVal = load(key.getDataType(), path);
                if (loadedVal != null) {
                    return loadedVal;
                }
            }

            // We need to maintain a path -> null mapping for keys that were loaded, but
            // were empty. This is required to prevent loading an empty key more than once, which is expensive.
            return NullValue.NULL_VALUE;
        });

        return val == NullValue.NULL_VALUE ? null : (T) val;
    }

```

**Comment by WenbinZhu** [comment]
@Maithem I see, can we remove synchronized? cache.get() seems thread safe

**Comment by Maithem** [comment]
@WenbinZhu Yea, I think all of the `synchronized` methods in `DataStore` can be removed.

**Comment by WenbinZhu** [comment]
I have a PR to improve local data store serialization performance, maybe I can resurrect that patch and include this `synchronized` cleanup.

**Comment by Maithem** [comment]
@WenbinZhu yea that would be great. Re-assigned.
