### ISSUE TITLE
Update documentation to reflect new repository location

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#283]
The repository has been moved from CorfuDB/CorfuDB to CorfuDB/Corfu-Repo as a result of #257.

All documentation needs to be updated to reflect this new path.

**Comment by dahliamalkhi** [comment]
I believe this is now donw.

**Comment by no2chem** [comment]
None of the links were updated in README.md, could you point to the PR that updates them? Otherwise I'll update them.

**Comment by dahliamalkhi** [comment]
Actually, I am not sure the repo is working, at least not with the instructions under Corfu-Repos README.

Here is a dump of the error you get from maven:

        INFO] Building CorfuDB-tutorials 1.0-SNAPSHOT
        [INFO] ------------------------------------------------------------------------
        Downloading:
        https://raw.github.com/corfudb/corfudb/mvn-repo/org/corfudb/corfu/0.1-SNAPSHOT/maven-metadata.xml
        Downloading:
        https://raw.github.com/corfudb/corfudb/mvn-repo/org/corfudb/corfu/0.1-SNAPSHOT/corfu-0.1-SNAPSHOT.pom
        [WARNING] The POM for org.corfudb:corfu:jar:0.1-SNAPSHOT is missing, no
        dependency information available
        Downloading:
        https://raw.github.com/corfudb/corfudb/mvn-repo/org/corfudb/corfu/0.1-SNAPSHOT/corfu-0.1-SNAPSHOT.jar
        [INFO] ------------------------------------------------------------------------
        [INFO] BUILD FAILURE
        [INFO] ------------------------------------------------------------------------
        [INFO] Total time: 3.256 s
        [INFO] Finished at: 2016-11-19T10:52:45-08:00
        [INFO] Final Memory: 9M/155M
        [INFO] ------------------------------------------------------------------------
        [ERROR] Failed to execute goal on project CorfuDB-tutorials: Could not resolve
        dependencies for project
        org.corfudb.tutorials:CorfuDB-tutorials:jar:1.0-SNAPSHOT: Could not find
        artifact org.corfudb:corfu:jar:0.1-SNAPSHOT in corfu-github-mvn-repo
        (https://raw.github.com/corfudb/corfudb/mvn-repo/) -> [Help 1]
        org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal
        on project CorfuDB-tutorials: Could not resolve dependencies for project
        org.corfudb.tutorials:CorfuDB-tutorials:jar:1.0-SNAPSHOT: Could not find
        artifact org.corfudb:corfu:jar:0.1-SNAPSHOT in corfu-github-mvn-repo
        (https://raw.github.com/corfudb/corfudb/mvn-repo/)

**Comment by dahliamalkhi** [comment]
Two things are broken. One is easy to fix, the maven file for downloading mvn-repo has a wrong url, should be:

                <url>https://github.com/CorfuDB/Corfu-Repos/blob/mvn-repo</url>

The second is harder, @no2chem  --
I think that the directory structure in Corfu-Repos seems broken. The directory with latest snapshot should be named  0.1-SNAPSHOT

**Comment by no2chem** [comment]
The directory structure is correct, I think. SNAPSHOT should direct maven to pick the latest version. I think the problem is that after splitting into module, not all the jars are being copied over. I'll look into that. The artifact should now be called runtime.

**Comment by dahliamalkhi** [comment]
I didn't realize pull closes issues automatically.

**Comment by no2chem** [comment]
It does, if the pull contains a commit which contains "closes #x".

**Comment by dahliamalkhi** [comment]
actually, the readme.md in both corfuDB and corfu-Repos still need to be updated.

**Comment by dahliamalkhi** [comment]
the remove pom should be: 

    <repositories>
            <repository>
                <id>mvn-repo</id>
                <url>https://github.com/CorfuDB/Corfu-Repos/mvn-repo</url>
                
                <snapshots>
                    <enabled>true</enabled>
                    <updatePolicy>always</updatePolicy>
                </snapshots>
            </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.corfudb</groupId>
            <artifactId>runtime</artifactId>
            <version>0.1-SNAPSHOT</version>
            <scope>compile</scope>
            
        </dependency>
    </dependencies>
