### ISSUE TITLE
Broken primitive serializer

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#285]
For some reason, the primitive serializer no longer works.

It seems this code patch turned off the unit test for this serializer
https://github.com/CorfuDB/CorfuDB/blame/master/src/test/java/org/corfudb/runtime/object/CorfuSMRObjectProxyTest.java#L189

**Comment by Maithem** [comment]
If you set setSerializer(Serializers.PRIMITIVE), it will pass, but why is it passing when the serializer is null?
I don't think that object is instrumented correctly.

**Comment by no2chem** [comment]
Well, if you set it to primitive, it actually fails, and you set it to null, so I was wondering what the reason was for that?

**Comment by Maithem** [comment]
I might have changed it by mistake.

I'm running this on master and it passes:

    @Test
    @SuppressWarnings("unchecked")
    public void canUsePrimitiveSerializer()
            throws Exception {
        //begin tests
        CorfuRuntime r = getDefaultRuntime().connect();
        TestClassWithPrimitives test = r.getObjectsView().build()
                .setType(TestClassWithPrimitives.class)
                .setStreamName("test")
                .setSerializer(Serializers.PRIMITIVE)
                .open();

        test.setPrimitive("hello world".getBytes());
        assertThat(test.getPrimitive())
                .isEqualTo("hello world".getBytes());
    }

**Comment by no2chem** [comment]
Ok, this appears to have been fixed by #296, closing.
