### ISSUE TITLE
doesNotUpdateToLayoutWithSmallerEpoch intermittently failing

### ISSUE THREAD

**Issue by annym** [CorfuDB/CorfuDB#2853]
## Overview

doesNotUpdateToLayoutWithSmallerEpoch is intermittently failing with QuorumUnreachable

Link: [https://github.com/CorfuDB/CorfuDB/pull/2851/checks?check_run_id=1654835400](https://github.com/CorfuDB/CorfuDB/pull/2851/checks?check_run_id=1654835400)

Error:  Errors: 
9227
Error:    CorfuRuntimeTest.doesNotUpdateToLayoutWithSmallerEpoch:154 » QuorumUnreachable
9228
[INFO] 
9229
Error:  Tests run: 666, Failures: 0, Errors: 1, Skipped: 5

**Comment by xcchang** [comment]
A potential fix in this PR: https://github.com/CorfuDB/CorfuDB/pull/2967
