### ISSUE TITLE
NullPointerException in StreamLogFiles.writeEntry()

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#288]
Relative to `master` branch at commit 8e7645de81c690584dacac918f888ae341739164

I need to Java-ify this test case, but if QC has two CorfuRuntimes that execute concurrently, the exception reported appears to be 100% consistently reproducible.

 Runtime 1:

     FGMap m = setup(FGMap, streamid=42);
    
     m.put("q", "qf");
     -> returns ok, no previous value of "q".

 Runtime 2:

     FGMap m = setup(FGMap, streamid=42);
    
     m.keySet();
     -> returns ["q"]

 ... as a side-effect, I see this:

     18:15:59.786 ERROR [ForkJoinPool.commonPool-worker-0] o.c.i.l.StreamLogFiles - Disk_write[1]: Exception
     java.lang.NullPointerException: null
    	at org.corfudb.infrastructure.log.StreamLogFiles.writeEntry(StreamLogFiles.java:173)

**Comment by dahliamalkhi** [comment]
I am trying to reproduce this in Java and can't. See code below. You can play with the order in which you instantiate the maps, do the put() and keySet() calls, etc.; all seem to work fine.

Question -- are you using from concurrent threads, is concurrency a potential issue?


package org.corfudb.tutorials;

import org.corfudb.runtime.CorfuRuntime;
import org.corfudb.runtime.collections.FGMap;
import org.corfudb.runtime.collections.SMRMap;

import java.util.Map;
import java.util.Set;

/**
 * Created by dmalkhi on 11/15/16.
 */
public class TwoRuntimes {
    private static CorfuRuntime getRuntimeAndConnect(String configurationString) {
        CorfuRuntime corfuRuntime = new CorfuRuntime(configurationString).connect();
        return corfuRuntime;
    }

    public static void main(String[] args) {
        new TwoRuntimes().start();
    }

    private void start() {
        CorfuRuntime runtime1 = getRuntimeAndConnect("localhost:8888");
        CorfuRuntime runtime2 = getRuntimeAndConnect("localhost:8888");


        Map<String, Integer> testMap1 = runtime1.getObjectsView()
                .build()
                .setType(FGMap.class)
                .setStreamName("stream1")
                .open();
        Map<String, InconsistentInMemoryView.MutableClass> testMap2 = runtime2.getObjectsView()
                .build()
                .setType(FGMap.class)
                .setStreamName("stream1")
                .open();

        Set<String> value2 = testMap2.keySet();


        String key = "key1";
        testMap1.put(key, new Integer(1));
        int value1 = testMap1.get(key);

        System.out.println("value1=" + value1);
        System.out.println("value2=" + value2);
    }

}

**Comment by slfritchie** [comment]
Dahlia, yes, concurrency is required. QC without concurrency never sees this error.

**Comment by slfritchie** [comment]
Reliable reproducer: https://gist.github.com/slfritchie/9c786902768f04f916adf0c6e614a42d

Usage example (change your classpath appropriately):

    java -cp /Users/sfritchie/v/src/CorfuDB/bin/../target/corfu-0.1-SNAPSHOT-shaded.jar -Xmx1000m org.corfudb.tutorials.TwoRuntimes localhost:8000 s2

* 1st arg: Corfu server endpoint, e.g. `localhost:8000`
* 2nd arg: stream name, e.g., `s1`

The error happens quite reliably for the first use on a new stream. Repeated use for the same stream will not log an exception.  Also note that the output of the program itself is not exceptional: the client isn't aware of the exception, nor does the output differ between 1st run & subsequent runs for the same stream.

`TRACE` level output example is at https://gist.github.com/slfritchie/b6ad962b95707eefde04426f66206949

**Comment by slfritchie** [comment]
FYI, `git bisect` suggests that this bug first appears at commit dbeeaa5646c9a1988bcf7800b45545ea65dda2f2.

**Comment by dahliamalkhi** [comment]
I've looked at https://gist.github.com/slfritchie/b6ad962b95707eefde04426f66206949 , but it is just output.

@slfritchie , If you have the time to play with the simple code above, please try to reproduce in Java (turns into multi-threaded, etc.). I'll get to it myself later today.

**Comment by Maithem** [comment]
@slfritchie @dahliamalkhi This is a known problem, apparently we didn't open a tracking issue. The problem is, appends are not serialized at the lowest level (i.e. file writes). I was going to address that as part of the fsync work. Also, this problem can easily be reproducible with concurrent writes to a stream, its not only visible from the objects layer.

**Comment by slfritchie** [comment]
It looks like this bug's behavior has been altered between the initial report and today's 'master' at commit 170b77d1b1f8b9788fa9f552ce63e0c21bee784b.  The test case as reported doesn't work any longer.  I'm not sure why.

The problem has not entirely disappeared, however, it's just far more rare.  I've managed to provoke it once, using the `SMRMap` flavor of the concurrent test.  The recent source reorganization has turned things upside-down, so I don't have a concrete & stable test case yet, sorry.  Workin' on it....

**Comment by slfritchie** [comment]
Looks like this race condition is probably fixed.  `git bisect` says:

1. Last commit to have the bug: 4c85a64d645f15860c4579cc843ff7be6f7f3680
    - Tue Nov 15 18:08:30 2016 -0800
2. First commit to make the bug rare/gone: 0b416e33eb3d9aca75043b610db2c892f0c2d3a4
    - Fri Nov 11 18:50:26 2016 -0800

The magic 0b416e33eb3d9aca75043b610db2c892f0c2d3a4 commit made substantial changes to `StreamLogFiles::writeEntry`, including deleting the line of code that was throwing the exception.
