### ISSUE TITLE
API of StreamLogFiles::append permits lost write bug

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#291]
Followup to the problem in #288.  See https://github.com/CorfuDB/CorfuDB/blob/master/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java#L309

If the `writeRecord()` call throws an exception, odds are high that the desired append bits didn't make it to the file system.  But the Caffeine cache at https://github.com/CorfuDB/CorfuDB/blob/master/src/main/java/org/corfudb/infrastructure/LogUnitServer.java#L323-L325 gets no signal that the write may failed: neither an exception rises here nor return value signal.

**Comment by Maithem** [comment]
I don't think this is a bug, its a feature, a weird one too. Not enabling --sync will cause the server to acknowledge a write request right away after it starts an append in the background. I will remove this option. In other words, all rights should sync. 

https://github.com/CorfuDB/CorfuDB/blob/master/infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java#L305

Also, note this there is an issue for this: https://github.com/CorfuDB/CorfuDB/issues/160

btw, even setting sync to true can lose data, we dont do fsync anywhere. I will submit a patch soon to address #160

**Comment by Maithem** [comment]
@slfritchie I merged a fix, can you verify and close this issue?

**Comment by slfritchie** [comment]
The silent write is gone, but the behavior on any I/O exception (for example) will be caught by `NettyServerRouter` which in turn won't send any reply to the client, and the client needs to wait.  That's not good, but arguably it's a different bug/feature.
