### ISSUE TITLE
ReconfigurationEventHandlerTest.updateLayoutOnFailure Failure

### ISSUE THREAD

**Issue by annym** [CorfuDB/CorfuDB#2915]
## Overview

Intermittent Failure of test: ReconfigurationEventHandlerTest.updateLayoutOnFailure
Link: [https://github.com/CorfuDB/CorfuDB/pull/2909/checks?check_run_id=2151383146](https://github.com/CorfuDB/CorfuDB/pull/2909/checks?check_run_id=2151383146)

**Error Detail:**

Error:  Failures: 
9874
Error:    ReconfigurationEventHandlerTest.updateLayoutOnFailure:86 
9875
expected: Layout(layoutServers=[test:0, test:1, test:2], sequencers=[test:0, test:1, test:2], segments=[Layout.LayoutSegment(replicationMode=CHAIN_REPLICATION, start=0, end=-1, stripes=[Layout.LayoutStripe(logServers=[test:0, test:1])])], unresponsiveServers=[test:2], epoch=2, clusterId=00000000-0000-0000-0000-000000000000)
9876
but was : Layout(layoutServers=[test:0, test:1, test:2], sequencers=[test:0, test:1, test:2], segments=[Layout.LayoutSegment(replicationMode=CHAIN_REPLICATION, start=0, end=-1, stripes=[Layout.LayoutStripe(logServers=[test:0, test:1, test:2])])], unresponsiveServers=[], epoch=1, clusterId=00000000-0000-0000-0000-000000000000)

**Comment by xcchang** [comment]
A potential fix in this PR: https://github.com/CorfuDB/CorfuDB/pull/2967
