### ISSUE TITLE
Can't find corfu_layouts.clj while running 'corfu_layouts add_layout'   

### ISSUE THREAD

**Issue by giri-basava** [CorfuDB/CorfuDB#297]
Hi, as per the readme, trying to add a second server to the layout. The request fails with "../corfu_scripts/corfu_layouts.clj (No such file or directory)". The file 'corfu_layout.clj' is present, but 'corfu_layouts.clj' is missing in the git repo.

user1@host1: /workspace/CorfuDB/bin$ ./corfu_layouts add_layout -c localhost:9000 -e localhost:9001
WARNING: cat already refers to: #'clojure.core/cat in namespace: net.cgrand.parsley.fold, being replaced by: #'net.cgrand.parsley.fold/cat
Exception in thread "main" java.io.FileNotFoundException: /home/sfast/workspace/CorfuDB/bin/../corfu_scripts/corfu_layouts.clj (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        ....
        ....
user1@host1@ssjc-part-a1-stor11:/workspace/CorfuDB/bin$ ls ../corfu_scripts/
corfu_layout.clj  corfu_management_bootstrap.clj  corfu_ping.clj  corfu_query.clj  corfu_reset.clj  corfu_stream.clj  quickcheckmode.clj

**Comment by Maithem** [comment]
Look at https://github.com/CorfuDB/CorfuDB/issues/284 for a workaround.

**Comment by giri-basava** [comment]
Thanks. Duplicate of #284
