### ISSUE TITLE
Stream API cleanup

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#300]
Since corfu doesn't know how to serialize any object, StreamView.write should accept a byte array, not
an object. I know that we use **public long write(Object object)** to write our own objects, but that shouldn't be exposed to the client.

Also,  logPointer, resolveBackpointersToRead and acquireAndWrite  should be private.

**Comment by slfritchie** [comment]
Mid-June issues review: ping @Maithem

**Comment by no2chem** [comment]
API sealing to be decided by v1.0-M2

**Comment by Maithem** [comment]
Will be addressed in #1207
