### ISSUE TITLE
Stream Write BufferOverflowException

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#304]
Writing 100 entries each 2mb throws the following exception:

 00:31:25.493 INFO  [event-0] o.c.i.l.StreamLogFiles - Disk_write[65]: Written to disk.
 00:31:25.516 INFO  [event-0] o.c.i.l.StreamLogFiles - Disk_write[66]: Written to disk.
 00:31:25.541 ERROR [event-0] o.c.i.l.StreamLogFiles - Disk_write[67]: Exception
 java.nio.BufferOverflowException: null
	at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:363)
00:31:25.541 ERROR [event-0] o.c.i.NettyServerRouter - Exception during read!
 java.lang.RuntimeException: java.nio.BufferOverflowException
	at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:308)
Caused by: java.nio.BufferOverflowException: null
	at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:363)

**Comment by slfritchie** [comment]
To be tested by PR #307

**Comment by slfritchie** [comment]
Ha, I just ran into this while trying to test an old bug report, #211, was still a problem.  Using a 20 MByte input file, I hit this error on the 9 iteration of:

    for i in `seq 1 10`; do /bin/echo -n $i "" ; cat /tmp/input-file | ./bin/corfu_stream -i s$i -c localhost:8000 write; done

**Comment by Maithem** [comment]
@slfritchie Are you sure thats the same problem? 

This problem happens because we fix the log-file size without controlling the size of each write. For example, we map a 125mb file for every 10k entries and since the write size can be arbitrary, we can write more than 125mb to the same file which throws a BufferOverflowException. This can easily be fixed with remove the restriction on the file size, but then you need to have a more clever mechanism to memory map that file as it grows.

**Comment by slfritchie** [comment]
"Are you sure thats the same problem?"  No, sorry, it's a "feels similar" thing.

**Comment by Maithem** [comment]
fixed by #317
