### ISSUE TITLE
Exception during application of SMR method

### ISSUE THREAD

**Issue by dahliamalkhi** [CorfuDB/CorfuDB#309]
@no2chem simple test (FirstCustomCorfuObject.java in tutorials package) of new object annotation yields  
09:56:17.864 WARN  [main] o.c.r.o.CorfuSMRObjectProxy - Exception during application of SMR method Increment

**Comment by no2chem** [comment]
Yeah that's because in the old scheme, you need to call getSMRObject() to get the object state.

**Comment by dahliamalkhi** [comment]
ok, looks it's it's best to wait to switch to the new annotations paradigm. closing this issue.
