### ISSUE TITLE
Failed append to log doesn't reply to client

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#310]
For context, see also discussion of #291 and #288.

In cases where `StreamLogFiles.append()` throws an `IOException` (or other exception), it's converted to a `RuntimeException` which is caught by `NettyServerRouter`.  The server logs an error and does nothing further.  The client is left to wait for a timeout, then will delay again (invalidating its layout, wait, then layout bootstrap).  This could be interpreted as a bug or a feature.  If bug, it needs fixing.  If feature, IMHO, it needs documentation.

**Comment by slfritchie** [comment]
Since we don't have a dynamic fault injection framework in place yet, here's a kludge to demo: https://github.com/CorfuDB/CorfuDB/compare/master...slfritchie:slf/append-exception-demo.  Then use `cat README.md | ./bin/corfu_stream -i 20 -c localhost:8000 write` a few times to advance the log to the faulty area.

**Comment by Maithem** [comment]
I'm looking at it.

**Comment by rogermichoud** [comment]
I was having a look at the code. I was able to "bubble up" the IOException to the StreamLogFiles. I was thinking of creating a new message type to send back to the client. 

With the current code, if a IOException happens, it dies in the batchwriter [https://github.com/CorfuDB/CorfuDB/blob/master/infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java#L117](url)

I consider an IOException a pretty severe fault, the client should trigger a new layout election upon reception of this message.

If you agree with me, I would start the implementation of this mechanism.

As a more advance step, we could imagine some "repair" mechanism on the faulty unit.

**Comment by slfritchie** [comment]
Mid-June issues review: ping @Maithem and @rogermichoud

**Comment by no2chem** [comment]
Is this still an issue? It needs to be sealed by v1.0-M3

**Comment by Maithem** [comment]
This is no longer the case, we catch uncaught exceptions and send back the exception in a message.
