### ISSUE TITLE
ManagementServer can be bootstrapped multiple times

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#322]
Relative to commit 58190acde22b76301e501216a276078a3cff087c on master.

The ManagementServer does not refuse being bootstrapped a second time.  For example:

1. Start a server on `localhost:8000` with `-m` and `-s` flags.
2. Run `rm -f /tmp/foo ; sh -c 'bin/corfu_layouts -c localhost:8000 query 2>&1 | grep -v parsley.fold/cat | sed 1d ' > /tmp/foo`.
3. Run `bin/corfu_management_bootstrap -c localhost:8000 -l /tmp/foo` twice.

Output on the server side:

     14:59:26.852 INFO  [event-7] o.c.i.ManagementServer - Received Bootstrap Layout : Layout(layoutServers=[localhost:8000], sequencers=[localhost:8000], segments=[Layout.LayoutSegment(replicationMode=CHAIN_REPLICATION, start=0, end=-1, stripes=[Layout.LayoutStripe(logServers=[localhost:8000])], replexes=null)], epoch=0)
     14:59:38.654 INFO  [event-8] o.c.i.ManagementServer - Received Bootstrap Layout : Layout(layoutServers=[localhost:8000], sequencers=[localhost:8000], segments=[Layout.LayoutSegment(replicationMode=CHAIN_REPLICATION, start=0, end=-1, stripes=[Layout.LayoutStripe(logServers=[localhost:8000])], replexes=null)], epoch=0)

**Comment by zalokhan** [comment]
I can have a look at this.

**Comment by zalokhan** [comment]
Closing this issue as the above PR #326 should have solved it.
