### ISSUE TITLE
Compare write schema vs. registered schema

### ISSUE THREAD

**Issue by annym** [CorfuDB/CorfuDB#3221]
## Overview

Currently, a table can be opened with schema_1 and yet updated with schema_2. There is no actual comparison with the registered schema. This could lead to corruption scenarios and moreover uncover very complex bugs like one recently looked at by @Lujie1996 in which incompatible changes in the schemas across several upgrades led to 'apparent' data loss, as secondary indexes were not returning the correct data. 

This is a bit of a more complex change as it can have performance implications, but should definitely be looked into.

**Comment by hisundar** [comment]
While not ideal this ensures that on valid upgrades the newer schemas take over from the older ones
