### ISSUE TITLE
StreamView cannot read relative stream addresses properly

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#329]
When running the following test twice, the second time it runs it will fail because StreamView
will return a null when trying to read address 0 because it checks the following condition:

if (thisRead > maxGlobal) {
                    getCurrentContext().currentBackpointerList.add(thisRead);
                    return null;
                }

   @Test
    public void simpleStreamTest() throws Exception {

        CorfuRuntime rt = new CorfuRuntime(layoutServers).connect();
        rt.setCacheDisabled(true);

        UUID streamId = UUID.randomUUID();

        StreamView s1 = rt.getStreamsView().get(streamId);

        // Verify that the stream is empty
        assertThat(s1.check()).isEqualTo(-1);

        // Generate and write random data. Write 100 entries, each entry is 2mb
        int entrySize = 1000000;
        int numEntries = 100;
        byte[][] data = new byte[numEntries][entrySize];

        Random rand = new Random();

        for(int x = 0; x < numEntries; x++) {
            rand.nextBytes(data[x]);
            s1.write(data[x]);
        }

        // Read back the data and verify it is correct
        for(int x = 0; x < numEntries; x++) {
            System.out.println("reading address " + x);
            LogData entry = s1.read(x);
            System.out.println("entry " + x +" address " + entry);
            byte[] tmp = (byte[]) entry.getPayload(rt);
            assertThat(tmp).isEqualTo(data[x]);
        }
    }

**Comment by Maithem** [comment]
@no2chem This is a problem for clients that restart, should we just sync to the tail once the client opens the stream?

**Comment by no2chem** [comment]
Hm. The test should actually fail at:
`assertThat(s1.check()).isEqualTo(-1)`, right? But maybe the sequencer gets reset while the logunit doesn't?

Where in the test is it failing the second time? Also why is the test being run twice without the server restarting?

**Comment by Maithem** [comment]
Right, it will fail on the first assert, I pasted the wrong code, but this test was failing before:

    @Test
    public void simpleStreamTest() throws Exception {

        CorfuRuntime rt = new CorfuRuntime(layoutServers).connect();
        rt.setCacheDisabled(true);


        UUID streamId = CorfuRuntime.getStreamID("stream1");

        StreamView s1 = rt.getStreamsView().get(streamId);

        final int numEntries = 10;
        byte[] data = new byte[numEntries];

        for(int x = 0; x < numEntries; x++) {
            s1.write(data);
        }

        CorfuRuntime rt2 = new CorfuRuntime(layoutServers).connect();
        rt.setCacheDisabled(true);


        UUID streamId2 = CorfuRuntime.getStreamID("stream1");

        StreamView s2 = rt.getStreamsView().get(streamId);

        // Read back the data and verify it is correct
        for(int x = 0; x < numEntries; x++) {
            LogData entry = s2.read(x);
            assertThat(entry.getPayload(rt)).isNotNull();
        }
    }


Now it seems to pass.

**Comment by slfritchie** [comment]
Mid-June issues review: the `StreamView` class no longer exists.  Please open a new ticket on the replacement class if the bug is still relevant.
