### ISSUE TITLE
LogUnitClient Leaks Memory

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#335]
A write payload is allocated but never freed after the message is flushed.

    public CompletableFuture<Boolean> write(long address, Set<UUID> streams, long rank,
                                            Object writeObject, Map<UUID, Long> backpointerMap) {
        ByteBuf payload = ByteBufAllocator.DEFAULT.buffer();
        Serializers.CORFU.serialize(writeObject, payload);
        WriteRequest wr = new WriteRequest(WriteMode.NORMAL, null, payload);
        wr.setStreams(streams);
        wr.setRank(rank);
        wr.setBackpointerMap(backpointerMap);
        wr.setGlobalAddress(address);
        return router.sendMessageAndGetCompletable(CorfuMsgType.WRITE.payloadMsg(wr));
    }

**Comment by slfritchie** [comment]
I have a Java reproducer available at https://github.com/slfritchie/CorfuDB/tree/slf/bug355-Leak2.  I hope that it is effective on your machine as it is on mine.

See the commit log at https://github.com/slfritchie/CorfuDB/commit/5abd981f6379bcce86b2f6ee31371d6f88ce9c56 for instructions to reproduce and sample output.

**Comment by Maithem** [comment]
addressed by #525
