### ISSUE TITLE
Fix flaky test LogReplicationFSMTest.testLogReplicationSnapshotTransmitterNoBatch

### ISSUE THREAD

**Issue by pankti-m** [CorfuDB/CorfuDB#3388]
## Overview

LogReplicationFSMTest.testLogReplicationSnapshotTransmitterNoBatch sometimes hits an AssertionError on the expected FSM state.
Expected = LogReplicationStateType.WAIT_SNAPSHOT_APPLY
Actual = LogReplicationStateType.IN_LOG_ENTRY_SYNC

Opening this issue to debug and address the flakiness.

**Comment by xcchang** [comment]
Recent running result: https://github.com/CorfuDB/CorfuDB/actions/runs/3753070452/jobs/6375945191

**Comment by pankti-m** [comment]
Being addressed in # 3638
