### ISSUE TITLE
ManagementServer attempts to fetch layout from sequencer & logunit nodes

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#349]
Relative to commit c158aad0e04fde52f56dea1970c63e1817321592, the ManagementServer attempts to fetch layouts from all (?) endpoints mentioned in the layout instead of only from endpoints in the layout servers list.

To reproduce:

1. Start server via `./bin/corfu_server -m -s -d WARN 8000`.  Do not run a server process that listens to port 8001.
2. Run cmdlet `bin/corfu_layouts -c localhost:8000 edit`
3. Change layout so that sequencers list looks like the JSON snippet below.
4. Observe exceptions logged by the server.

Layout JSON:

    {
      "layoutServers": [
        "localhost:8000"
      ],
      "sequencers": [
        "localhost:8000", "localhost:8001"
      ],
      "segments": [
        {
          "replicationMode": "CHAIN_REPLICATION",
          "start": 0,
          "end": -1,
          "stripes": [
            {
              "logServers": [
                "localhost:8000"
              ]
            }
          ]
        }
      ],
      "epoch": 0
    }

Exceptions logged by server.  Note that the 2nd message, `Couldn't connect to any layout servers[...]` probably indicates another bug? Namely, the single polling attempt by ManagementServer may be blocking forever because this layout fetch attempt is failing & retrying infinitely.

    12:07:46.701 WARN  [ForkJoinPool.commonPool-worker-1] o.c.r.CorfuRuntime - Tried to get layout from localhost:8000 but failed with exception:
     org.corfudb.runtime.exceptions.NetworkException: AnnotatedConnectException connecting to endpoint [endpoint=localhost:8001]
    	at org.corfudb.runtime.clients.NettyClientRouter.start(NettyClientRouter.java:260)
    Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8001
    	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    12:07:46.701 WARN  [ForkJoinPool.commonPool-worker-1] o.c.r.CorfuRuntime - Couldn't connect to any layout servers, retrying in 5s.

**Comment by zalokhan** [comment]
The management server uses the runtime to fetch the latest layout.
The runtime fetches the layout correctly but here it tries to create a clientRouter for 8001 (whose server process is not listening yet) to set the new Epoch which causes the block.
https://github.com/CorfuDB/CorfuDB/blob/master/runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java#L316

Should we be handling exceptions for this separately so as not to block the clients?

**Comment by slfritchie** [comment]
Hm, that "FIXME" section needs fixing, yes.  The ManagementServer needs to be able to finish execution of a single polling attempt in a finite amount of time.

Your link to CorfuRuntime.java#L316 shows a use of layout.getAllServers() that should be avoided in the ManagementServer's context.  I'm not sure if it is a good idea in other contexts, sorry.

**Comment by dahliamalkhi** [comment]
@zalokhan @zalokhan has this been addressed by latest merges?

**Comment by zalokhan** [comment]
No @dahliamalkhi this hasn't been fixed yet.
I will discuss this with @slfritchie to get a solution for this.

**Comment by slfritchie** [comment]
Mid-June issues review: ping @zalokhan

**Comment by zalokhan** [comment]
@slfritchie One approach to resolve this issue is to not rely on the runtime and rather create and manage routers to all layout servers. These routers can be used to query the layout.
(Note. To ping all the servers the management server anyways manages separate routers.)
Runtime will only be required at the time of failure correction (to seal and run paxos.)
Let me know if this sounds like a reasonable fix.

**Comment by slfritchie** [comment]
@zalokhan Yes, sounds reasonable.

**Comment by zalokhan** [comment]
The runtime fetchLayout is no more blocked to create client routers to unresponsive nodes.
#945
