### ISSUE TITLE
LayoutServer prepare rank history depends on prior use of set_layout vs. commit

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#351]
Relative to commit c158aad0e04fde52f56dea1970c63e1817321592 ... In a sequence of **{command}, prepare, commit, prepare**, the result of the 2nd prepare differs depending on the first cmd **{command}**.

* If the 1st command sets the server's epoch via commit, then 2nd prepare is not aware of the 1st prepare at all.
* If the 1st command sets the server's epoch via set_epoch, then 2nd prepare **is** aware of the 1st prepare.

Expected value of 2nd prepare:

    ["OK"] = layout_qc:reset().
    ["OK"] = layout_qc:set_epoch(100).
    ["OK","ignored: ignored"] = layout_qc:prepare(100, 63).    % epoch = 100, rank = 63; "ignored: ignored" = no proposed epoch
    ["OK"] = layout_qc:commit(100, 63, {layout,100,[],[],[]}).
    ["ERROR","Exception during prepare","org.corfudb.runtime.exceptions.OutrankedException: Higher rank 63 encountered, layout = null","newRank: 63","layout: "] =
        layout_qc:prepare(100, 50).                            % epoch = 100, rank = 50.

Observed value of 2nd prepare when commit is used instead of set_epoch.

    ["OK"] = layout_qc:reset().
    ["OK"] = layout_qc:commit(0, 22, {layout,1,[],[],[]}).
    ["OK","ignored: ignored"] = layout_qc:prepare(1, 63).      % epoch = 1, rank = 63; "ignored: ignored" = no proposed epoch
    ["OK"] = layout_qc:commit(1, 63, {layout,100,[],[],[]}).
    ["OK", "ignored: ignored"] =
        layout_qc:prepare(100, 50).                            % epoch = 100, rank = 50.

**Comment by slfritchie** [comment]
Mid-June issues review: @zalokhan does this bug interfere with/relevant to your work, or should it be closed?

**Comment by zalokhan** [comment]
Not relevant with what I'm doing. 
I think we can close this now.
