### ISSUE TITLE
Linearizability violation using Replex replication + SMRMap

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#354]
Pure java reproducer for linearizability violation using Replex replication,
found by QuickCheck (after adding today support for Replex layouts).
Multiple runtimes are **required** by this sequential test case.

Pretty-printed version of the original failing test case:

    [[{init,#state{map_type = smrmap,replication_type = replex,
                   endpoint = "sfritchie-m01:8000",
                   reset_p = false,stream = 42,d = []}},
      #exec{step = 1,func = reset,args = [runtime5,[replex]]},
      #exec{step = 3,func = put,
            args = [runtime6,["b","lumxejgbpxbdcclmmngolaq"]]},
      #exec{step = 4,func = put,
            args = [runtime6,["v","Hello-world!"]]},
      #exec{step = 5,func = put,
            args = [runtime2,["a","qqshepqitpalyktjcscmjxvsqe"]]},
      #exec{step = 6,func = put,args = [runtime8,["b",'']]},
      #exec{step = 8,func = put,args = [runtime4,["c",'']]},
      #exec{step = 15,func = put,args = [runtime2,["y",'']]},
      #exec{step = 16,func = put,args = [runtime5,["s",'']]},
      #exec{step = 18,func = put,
            args = [runtime9,["a","qmsknkhkmmlsodtbpvkzv"]]},
      #exec{step = 19,func = put,
            args = [runtime3,["b","Hello-world!"]]},
      #exec{step = 20,func = put,
            args = [runtime9,["f","Another-value"]]},
      #exec{step = 21,func = put,
            args = [runtime9,["z","Hello-world!"]]},
      #exec{step = 22,func = clear,args = [runtime8,[]]},
      #exec{step = 23,func = put,args = [runtime0,["f",'']]},
      #exec{step = 27,func = put,
            args = [runtime8,["o","Another-value"]]},
      #exec{step = 28,func = remove,args = [runtime1,["f"]]},
      #exec{step = 29,func = put,
            args = [runtime5,["a","Hello-world!"]]},
      #exec{step = 30,func = remove,args = [runtime4,["a"]]}]]

The last step, #30, removes "a" from the map and should be
returning "Hello-world!" (from step #29).  But instead, the remove
returns "qqshepqitpalyktjcscmjxvsqe", which is "a"'s value from
step #5.

To reproduce, check out the `slf/weird-replex` branch and compile, e.g., `git clone --branch=slf/weird-replex https://github.com/CorfuDB/CorfuDB` then `cd CorfuDB ; mvn install`.

1. Start a Corfu server via:

    ./bin/corfu_server -m -s -d WARN 8000

2. Run the following client:

    java -Dio.netty.leakDetection.level=advanced -cp ./cmdlets/target/cmdlets-0.1-SNAPSHOT-shaded.jar org.corfudb.cmdlets.WeirdReplex localhost:8000 stream42 replex ; echo status was $status

... where the arguments are:

	1. Corfu server endpoint
	2. Stream name
	3. replex | chain_replication

Note that more than a single runtime is necessary for this bug to occur.
If I use the `WeirdReplex2` class instead, I observe bug-free execution.

**Comment by slfritchie** [comment]
I've a weird observation to add, but it might be helpful for bug diagnosis.  I see this same error popping up when using CHAIN_REPLICATION layouts, but I'm 98% sure that it's somehow related to mixing tests with REPLEX & CHAIN_REPLICATION layouts, where the change is made between test cases as part of a system-under-test reset of state. If I force the test model to only use CHAIN_REPLICATION layouts, this error never appears.

**Comment by slfritchie** [comment]
FWIW, I've added an easier to read test case (pure Java reproducer) at https://github.com/slfritchie/CorfuDB/blob/4e37b248e134555245b4410f55ff251051d9a9bd/cmdlets/src/main/java/org/corfudb/cmdlets/WeirdReplex3.java#L80-L97

* For new REPLEX streams, the answer is always `m`, incorrect.  Note that step 13, 14, and 18 all use the same runtime, `runtime0`, and that 18's incorrect answer goes backward 2 values (relative to `runtime0`'s method calls) or backward 5 values (relative to both runtime's method calls).
* For existing/re-used REPLEX streams, the answer is always correct.

**Comment by dahliamalkhi** [comment]
Replex not supported.
