### ISSUE TITLE
opacity test failing on annotationProcessor branch

### ISSUE THREAD

**Issue by dahliamalkhi** [CorfuDB/CorfuDB#371]
added onto #324 an opacity test on a branch called 'opacity' (https://github.com/CorfuDB/CorfuDB/tree/opacity) . Unless I am wrong, seems like opacity is indeed violated? @no2chem

**Comment by no2chem** [comment]
Ok, this looks like a bug with optimistic updates which are not undoable. In particular, it seems that a conditional in VersionLockedObject was boolean AND when it should have been OR:
https://github.com/CorfuDB/CorfuDB/blob/annotationProcessor/runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java#L131

**Comment by dahliamalkhi** [comment]
I guess the status is not supported yet. changing status to wontfix. Adding PR for the opacity test as unit test into PR #324

**Comment by no2chem** [comment]
Hm, why did you change the status to won't fix (what do you mean by the status is not supported yet?)

**Comment by dahliamalkhi** [comment]
That was the most relevant label I could find -- basically what I meant is: in case multiple threads are accessing an object that does not support undo, the system will throw an exception, not provide opacity. is there a better way to tag this?
