### ISSUE TITLE
Cluster Reconfiguration Livelock Scenario

### ISSUE THREAD

**Issue by zfrenette** [CorfuDB/CorfuDB#3875]
Under certain conditions, the CorfuRuntime can block indefinitely and stall during cluster reconfiguration by rejecting layouts from all responsive nodes due to these layouts having a stale epoch. Consider the following example.

We begin with a three node cluster {N0, N1, N2} where all nodes are responsive and on the same epoch. For simplicity, we assume that N0 is the primary sequencer. This scenario plays out as follows:

1) The failure detector on N1 detects that N2 is unresponsive. It generates a new layout by moving N2 to the unresponsive list.
2) N1 proceeds by initiating the seal protocol. The SEAL requests are received by N1 and N2, but not by N0.
3) Having received enough responses, the new layout is considered sealed and N1 proceeds by attempting the consensus protocol.
4) PREPARE_LAYOUT and PROPOSE_LAYOUT requests are eventually received by N1 and N2, but not by N0.
5) A quorum is achieved for the new layout and N1 proceeds by attempting COMMIT_LAYOUT. Here however, COMMIT_LAYOUT is only received by N2; not by N0 and N1. The consensus portion is now complete and N1 attempts to bootstrap the sequencer (N0), which also times out.
6) At this stage:
- N0 is still on the original epoch with the original layout
- N1 is on the new epoch but does not have the new layout
- N2 is on the new epoch and has the new layout
7) From here, whenever a CorfuRuntime receives a layout response from N2 (through fetchLayout), other RPCs will begin timing out until the SystemDownHandler is triggered. This is occurs because N2 is the only node that has the most recent layout, but the node is filtered out because it's in the unresponsive list. Once this new layout is observed once, layout responses from N0 and N1 are discarded since they have a stale epoch.
8) Once the SystemDownHandler is triggered and the runtime is restarted, the cycle repeats.

**Comment by xnull** [comment]
> 4. PREPARE_LAYOUT and PROPOSE_LAYOUT requests are eventually received by N1 and N2, but not by N0.
How this is possible? I mean, why N0 doesn't get those requests? Is the node unavailable at the time?

**Comment by zfrenette** [comment]
> How this is possible? I mean, why N0 doesn't get those requests? Is the node unavailable at the time?

There are infra issues occurring on the setup for several minutes during. A number of RPC messages are not received between nodes.
