### ISSUE TITLE
Sync parent directory

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#433]
When new files are create they need to be synced along with their parent directory to disk. Here's an excerpt fom the fsync man page : 

> Calling fsync() does not necessarily ensure that the entry in the
       directory containing the file has also reached disk.  For that an
       explicit fsync() on a file descriptor for the directory is also
       needed." . 

The side effect of not doing this in server is writes that disappear after they have been acknowledged.

**Comment by dahliamalkhi** [comment]
please be specific: which module? what files?

**Comment by Maithem** [comment]
@dahliamalkhi When a new log file is created, here:
https://github.com/CorfuDB/CorfuDB/blob/master/infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java#L306

**Comment by slfritchie** [comment]
Mid-June issues review: ping @Maithem
