### ISSUE TITLE
Hole Filling Bug

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#439]
In addition to writing holes, the hole filling mechanism should also propagate values that have been 
partially written in the chain. For example, If a client writes to the head then it fails, other clients would
try to fill in the hole for that address, but when they try to write to the head an overwrite exception
is thrown. Instead, the clients should take the value for that address from the head and propagate it to the tail.

**Comment by dahliamalkhi** [comment]
I think this can be closed already? @Maithem

**Comment by slfritchie** [comment]
Mid-June issues review: ping @Maithem, is @kspirov's new & refactored code in #527 and subsequent runtime PRs sufficient?

**Comment by no2chem** [comment]
Closed by #524
