### ISSUE TITLE
Request to support systemd watchdog in corfu server

### ISSUE THREAD

**Issue by bitmingw** [CorfuDB/CorfuDB#497]
NSX-T DK will be running in Ubuntu 16.04 (Xenial) host system. Xenial use [systemd](https://www.freedesktop.org/wiki/Software/systemd/) as service supervisor. We would want corfu to support systemd watchdog in Xenial so systemd can restart corfu server automatically under certain conditions.

Implement systemd watchdog requires an open socket to systemd daemon and certain messages within a time interval. Some tech details are explained in [this article](http://0pointer.de/blog/projects/watchdog.html).

**Comment by bitmingw** [comment]
@Maithem

**Comment by zalokhan** [comment]
I think we have investigated this and have a solution for Xenial systemd supported hosts.
To reproduce this.
First create a systemd unit file with the below contents:
```
# Automatically generated by systemd-sysv-generator

[Unit]
Documentation=man:systemd-sysv-generator(8)
SourcePath=/etc/init.d/corfu-server
Description=LSB: Corfu Infrastructure Server
After=remote-fs.target
After=systemd-journald-dev-log.socket

[Service]
Type=forking
Restart=always
TimeoutSec=5min
IgnoreSIGPIPE=no
KillMode=process
GuessMainPID=no
RemainAfterExit=no
ExecStart=/etc/init.d/corfu-server start
ExecStop=/etc/init.d/corfu-server stop

[Install]
WantedBy=multi-user.target
```
After restarting corfu-server, systemd would monitor the corfu_server process and will restart if it exits or fails.
