### ISSUE TITLE
Incorrect Code Generation For Overloaded SMR Methods

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#509]
When overloading methods the annotation processor will generate incorrect code. For example, in the case of an smr map, if you overload put and have something like v1 put(k1, v1, v2)
then the generated class would have an upcall map that will omit one of the signatures which will cause a runtime exception. The upcall map would look something like:

public final Map<String, ICorfuSMRUpcallTarget<SMRMap<K, V>>> upcallMap_CORFUSMR = new ImmutableMap.Builder<String, ICorfuSMRUpcallTarget<SMRMap<K, V>>>()
  .put("remove", (obj, args) -> { return obj.remove((java.lang.Object) args[0]);})
  .put("putAll", (obj, args) -> { obj.putAll((java.util.Map<? extends K,? extends V>) args[0]);return null;})
  .put("clear", (obj, args) -> { obj.clear();return null;})
  .put("put", (obj, args) -> { return obj.put((K) args[0], (V) args[1]);})
.put("put", (obj, args) -> { return obj.put((K) args[0], (V) args[1], (V) args[2]);}).build();

A possible fix would be to have the whole signature as the key (instead of the name).
What do you think @no2chem ?

**Comment by no2chem** [comment]
Yeah, this is a bug. When name is not set in the annotation, the full signature should be used. We used to call `ReflectionUtils.getShortMethodName(method.toString())` in the old codebase, maybe we can do that again?

**Comment by Maithem** [comment]
Yes, that will implicitly capture the number of parameters which is what is needed. 

You also bring up an important point, the annotation method naming can break java's typing system. Not javac, but our annotation processor. For instance, one method name can map to two methods with different return types. Can we just remove the method annotation naming? it seems error-prone.

**Comment by no2chem** [comment]
No, I think we need to keep the method annotation naming. Otherwise method names could get quite long. Maybe they should automatically end with the number of parameters automatically though (put becomes put2), but I'm not sure that's a good idea. Maybe it'd be sufficient for the processor to check for duplicate up all targets and error. The reason we need the name is for methods like blindPut, which take a different name, and backwards compatibility.
