### ISSUE TITLE
Unit tests SealIT and StreamIT have wrong suffix, rely on external server

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#511]
While examining other unit test classes, I noticed that these two classes share a couple of broken traits:

* Neither ends in `Test` and thus aren't run regularly by developers using common Maven incantations  or by TravisCI.
* Both rely on a Corfu server external to the unit test framework.

It would be handy if these two classes were refactored to use the `TestClientRouter` style interface to simulated Corfu servers.  Also handy would be running regularly within the CI system.

**Comment by slfritchie** [comment]
cc: original authors @Maithem and @rogermichoud.

**Comment by Maithem** [comment]
These are integration tests, so It doesn't make sense to run them against the test client router.
There was a plan to run *IT tests during the CI run.

**Comment by slfritchie** [comment]
I wasn't aware of that convention, sorry.  I've been examining modules that have `@Test` annotations but aren't being run by CI, and these modules fit those conditions.
