### ISSUE TITLE
BackpointerStreamView fillReadQueue hole fill leaves empty entry

### ISSUE THREAD

**Issue by kjames88** [CorfuDB/CorfuDB#522]
With two threads operating on a single map, BackpointerStreamView::fillReadQueue encounters a null/EMPTY element for an address.  It attempts to hole-fill and gets an OverwriteException.  currentEntry is updated to the local state, which is null/EMPTY, and processing continues.  Because the entry is not present, containsStream fails and nothing is added to readQueue.  When the affected thread later tries to sync to the skipped address, AbstractQueuedStreamView::getNextEntries returns nothing due to (context.readQueue.first() > maxGlobal).

Use of cache for read in fillReadQueue allows the client to be unaware of changes on the server and hole filling logic allows the stream view to advance without filling gaps in the history.  This seems to be a correctness problem.

*BackpointerStreamView::fillReadQueue*
`currentEntry = runtime.getAddressSpaceView().read(currentRead);`

*AddressSpaceView::read()*
`ILogData data = readCache.get(address);
            if (data == null) {
                data = new InMemoryLogData(DataType.EMPTY);
                data.setGlobalAddress(address);
}`

The failure was observed with a non-transaction 2 thread test writing to a single map.  In this case, CorfuCompileProxy::getUpcallResultInner throws RuntimeException because the entry, while received into the cache, was never propagated into the stream view, and therefore never triggered setUpcallResult.

**Comment by medhavidhawan** [comment]
/**
     * Reset all in-memory caches.
     */
    public void resetCaches() {
        readCache = Caffeine.<Long, ILogData>newBuilder()
                .<Long, ILogData>weigher((k, v) -> v.getSizeEstimate())
                .maximumWeight(runtime.getMaxCacheSize())
                .recordStats()
                .build(new CacheLoader<Long, ILogData>() {
                    @Override
                    public ILogData load(Long aLong) throws Exception {
                        return cacheFetch(aLong);
                    }

                    @Override
                    public Map<Long, ILogData>
                    loadAll(Iterable<? extends Long> keys) throws Exception {
                        return cacheFetch((Iterable<Long>) keys);
                    }
                });
    }

If you look at the readCache initialization code, it does a cacheFetch() inside the load method which is used if the data is not in the cache.  So the get will either load the data into the cache and then get it or it will directly get it from the cache if it is present.

**Comment by Maithem** [comment]
Addressed by #522
