### ISSUE TITLE
question

### ISSUE THREAD

**Issue by publicocean0** [CorfuDB/CorfuDB#540]
hi, i have to implement a distributed transactional replication. Can i use your library?
I developped a mini database embedded and now i want make it distributed. 
Ok it is transactional and distributed but how to intercept the messages for a replica?

**Comment by Maithem** [comment]
Hello,

CorfuDB is an open source project released under Apache License, Version 2.0. You can use CorfuDB as long as you abide by the license.

Please open a new issue if you encounter bugs, or if you have a more specific question.
