### ISSUE TITLE
New runtime streaming LogData to remainingUpTo creates container of all updates

### ISSUE THREAD

**Issue by kjames88** [CorfuDB/CorfuDB#566]
When a corfu stream is accessed on a new client, all logged updates need to be read from log unit.  The streaming implementation in corfu collects all the entries through a series of data structures into a flat list in StreamViewSMRAdapter::remainingUpTo().  Profiling shows 30k reachable LogData objects using 430MB in an L2 test with cache size of 100MB.

**Comment by slfritchie** [comment]
Mid-June issues review: ping @kjames88, I don't know if you've looked at this case in the `master` recently.

**Comment by no2chem** [comment]
Performance issue, let's complete by v1.0-M3.
