### ISSUE TITLE
Corfu maven repository issue 

### ISSUE THREAD

**Issue by cjqhenry14** [CorfuDB/CorfuDB#567]
I want to create a maven project which depends on CorfuDB, but I follow the instructions here: https://github.com/CorfuDB/CorfuDB#now-i-want-to-write-a-program-that-uses-corfu
it will show "[WARNING] The POM for org.corfudb:runtime:jar:0.1-SNAPSHOT is missing, no dependency information available" and can't find the corfu dependency.

The repo URL from https://github.com/CorfuDB/Corfu-Repos also doesn't work.

Looks like the CorfuDB repo address is not valid.

Thanks.

**Comment by bitmingw** [comment]
@cjqhenry14 [Corfu Repos](https://github.com/CorfuDB/Corfu-Repos) looks good. I believe you need to take off SNAPSHOT and change it to a number listed in that repository, and you are good to go.

**Comment by slfritchie** [comment]
Hi, sorry about the delay in reviewing this ticket.  As near as I can tell, the Maven SNAPSHOT mechanism ought to work as the README says when dealing with the `runtime` JAR.  However, there are dependencies on `annotations` and `annotationProcessor` JARs that aren't in the `Corfu-Repos` repository.  I'll experiment today with a change to the TravisCI post-build script to add the missing JARs.
