### ISSUE TITLE
WriteSetSMRStream bug

### ISSUE THREAD

**Issue by dahliamalkhi** [CorfuDB/CorfuDB#570]
WriteSetSMRStream does not handle nesting correctly (see test below, which fails). 

@no2chem , I am also unhappy with the design -- WriteSetSMRStream does not know when transaction contexts are really merged, the code in 'previous()' and in 'merge()' is unreadable. 

I am cleaning it up thoroughly now will submit a patch. 

The failing test, inside UndoTest:

    @Test
    public void checkRollbackNested()  throws Exception {
        ArrayList<Map> maps = new ArrayList<>();

        final int nmaps = 2;
        for (int i = 0; i < nmaps; i++)
            maps.add( (SMRMap<Integer, String>) instantiateCorfuObject(
                    new TypeToken<SMRMap<Integer, String>>() {}, "test stream" + i)
            );
        final int key1 = 1, key2 = 2, key3 = 3;
        final String tst1 = "foo", tst2 = "bar";
        final int nNests = PARAMETERS.NUM_ITERATIONS_LOW;

        // start tx in one thread, establish snapshot time
        t(1, () -> {
            TXBegin();
            maps.get(0).get(key1);
            maps.get(1).get(key1);
        });

        // in another thread, nest nNests transactions writing to different streams
        t(2, () -> {
            for (int i = 0; i < nNests; i++) {
                TXBegin();
                maps.get((i%nmaps)).put(key1, (i % nmaps) == 0 ? tst1 : tst2);
                maps.get((i%nmaps)).put(key2, (i % nmaps) == 0 ? tst1 : tst2);
                maps.get((i%nmaps)).put(key3, (i % nmaps) == 0 ? tst1 : tst2);
            }
        });

        t(1, () -> {
            assertThat(maps.get(0).get(key1))
            .isEqualTo(null);
            assertThat(maps.get(1).get(key1))
                    .isEqualTo(null);
        });

    }

**Comment by no2chem** [comment]
I'm not particularly happy with how WriteSetSMRStream is written either, so a rewrite is welcome. The fix to the bug given seems pretty simple though and I added it in #571. It -might- be a good idea to base any further changes on top of #569, though.
