### ISSUE TITLE
clear() is not transactionally safe

### ISSUE THREAD

**Issue by vjeko** [CorfuDB/CorfuDB#575]
```java
  @Override
  @Mutator(
      name = "clear",
      reset = true
  )
  public void clear() {
    proxy_CORFUSMR.logUpdate("clear",false,null);
  }
```

**Comment by no2chem** [comment]
Can you give more detail? The attached code snippet gives no information...



On Mon, May 01, 2017 at 6:00pm, Vjekoslav Brajkovic < notifications@github.com [notifications@github.com] > wrote:
@Override@Mutator(
      name="clear",
      reset=true
  )
  publicvoid clear() {
    proxy_CORFUSMR.logUpdate("clear",false,null);
  }
