### ISSUE TITLE
Provide a comparison with Raft

### ISSUE THREAD

**Issue by thedrow** [CorfuDB/CorfuDB#576]
Raft is one of the most widely used consensus algorithms.
When evaluating new technologies it's useful to know what the differences are between the widely used tech and the one presented in this repository.

When Raft is more suitable to use? Which usecases fit CorfuDB better?

**Comment by slfritchie** [comment]
Mid-June issues review: Oops, Omar, apologies for overlooking your question.  For a longer answer, you're right, we probably ought to update the Corfu wiki with a compare & contrast section.

For a short answer, Raft provides an ordered log, and what you do with that log is up to you.  Further, there is no single Raft implementation, for good or not.  You have many choices of protocol implementations & implementation languages.
Corfu also provides an ordered log but also builds state machine replicated (SMR) objects on top of that log for easy use by POJO-appearing Java objects.  Corfu's SMR object implementation is available only in Java; if your application doesn't run on the JVM, Corfu isn't a good choice for that app.

**Comment by no2chem** [comment]
Let's have this in the documentation by v1.0.

**Comment by Maithem** [comment]
@thedrow we don't have cycles for now. Please feel free to contribute if you choose to compare the two protocols.
