### ISSUE TITLE
Differentiate between DataCorruption Exceptions

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#579]
Data Corruption can be thrown on bad checksums, delimiters, protobuf encoding. I think its a good idea to differentiate between these exceptions as it makes debugging easier.

**Comment by slfritchie** [comment]
Mid-June issues review: ping @Maithem

**Comment by no2chem** [comment]
This needs to be decided on before the API is sealed.

**Comment by Maithem** [comment]
Old. The delimiter has been removed by #1212
