### ISSUE TITLE
WriteSetSMRStream doesn't sync properly

### ISSUE THREAD

**Issue by dahliamalkhi** [CorfuDB/CorfuDB#596]
To check if the VersionLockedObject state is the same as a WriteSetSMRStream, we check if the stack of contexts are identical. This works only if every transaction in the stack accesses the object. To demonstrate this, I built below a test that makes use of mutators, which fails to sync the second object properly. @no2chem can you please take a look?

 @Test
    public void checkNestedNoAccessor()  throws Exception {
        ArrayList<TestClass> objects = new ArrayList<>();

        final int nObjects = 2;
        for (int i = 0; i < nObjects; i++)
            objects.add((TestClass) instantiateCorfuObject(
                    new TypeToken<TestClass>() {
                    }, "test stream" + i)
            );

        int nestingDepth = 2; 

        // first, nest transactions up to depth 'nestingDepth'
        // each TX invokes mutators only, no accessors, on the first object

        for (int nestLevel = 0; nestLevel < nestingDepth; nestLevel++) {
            TXBegin();
            objects.get(0).set(nestLevel);
        }

        // access the object, to affect sync on the in-memory object
        objects.get(0).get();

        // next, collapse some of the nested TX with aborts
        for (int nestLevel = 0; nestLevel < nestingDepth/2; nestLevel++) {
            TXAbort();
        }

        // then, restablish nested transactions up to the same nesting level
        // each TX invokes mutators only, no accessors, on the second object
        for (int nestLevel = 0; nestLevel < nestingDepth/2; nestLevel++) {
            TXBegin();
            objects.get(1).set(2*nestLevel);
        }

        // finally, access the objects
        assertThat(objects.get(0).get())
                .isEqualTo(nestingDepth/2-1);
        assertThat(objects.get(1).get())
                .isEqualTo((nestingDepth-1)*2); // this fails!!
    }

**Comment by no2chem** [comment]
This test seems to be wrong?

First, it doesn't compile, it seems to be missing a generic parameter on objects:
ArrayList<TestClass> objects = new ArrayList<>();

Second, you don't specify, but I assume TestClass is org.corfudb.runtime.object.TestClass in test?

Third, I have no idea what the final assertion is testing for, Object[1] is never set to (nestingDepth-1)*2, since the loop above it terminates after calling objects.get(1).set(2*0) = 0, where nestLevel = 0. on the next iteration, 1 < 2/2 = 1 < 1 fails and the loop terminates.

**Comment by dahliamalkhi** [comment]
1. unindented pasted code (the top level row) omits everything between '<' and '>' for some reason, but the test I run has the object type in the array declaration

2. yes, sorry, this is the right TestClass

3. you are right. I changed the test, and also checked with higher nestedDepth... and it passes. Here is the corrected test, I'll post it and then close this issue (for now):

          @Test
    public void checkNestedNoAccessor()  throws Exception {
        ArrayList<TestClass> objects = new ArrayList<>();

        final int nObjects = 2;
        for (int i = 0; i < nObjects; i++)
            objects.add((TestClass) instantiateCorfuObject(
                    new TypeToken<TestClass>() {
                    }, "test stream" + i)
            );

        int nestingDepth = 4;

        // first, nest transactions up to depth 'nestingDepth'
        // each TX invokes mutators only, no accessors, on the first object

        for (int nestLevel = 0; nestLevel < nestingDepth; nestLevel++) {
            TXBegin();
            objects.get(0).set(nestLevel);
        }

        // access the object, to affect sync on the in-memory object
        objects.get(0).get();

        // next, collapse some of the nested TX with aborts
        for (int nestLevel = 0; nestLevel < nestingDepth/2; nestLevel++) {
            TXAbort();
        }

        // then, restablish nested transactions up to the same nesting level
        // each TX invokes mutators only, no accessors, on the second object
        for (int nestLevel = 0; nestLevel < nestingDepth/2; nestLevel++) {
            TXBegin();
            objects.get(1).set(2*nestLevel);
        }

        // finally, access the objects
        assertThat(objects.get(0).get())
                .isEqualTo(nestingDepth/2-1);
        assertThat(objects.get(1).get())
                .isEqualTo((nestingDepth/2-1)*2);
    }

**Comment by dahliamalkhi** [comment]
I think I might "win" this after all. Here is a failing scenario, which I believe should not fail:

     nested commits "disappear" --


     @Test
    public void checkCommitNested()  throws Exception {
        ArrayList<TestClass> objects = new ArrayList<>();

        final int nObjects = 2;
        for (int i = 0; i < nObjects; i++)
            objects.add((TestClass) instantiateCorfuObject(
                    new TypeToken<TestClass>() {
                    }, "test stream" + i)
            );

        final int nestingDepth = 8;

        // first, nest empty transactions up to depth 'nestingDepth'
        for (int nestLevel = 0; nestLevel < nestingDepth; nestLevel++) {
            TXBegin();
        }

        // access the object, to cause the TX stack to be copied as
        // optimistic stream
        //objects.get(0).get();


        // commit some of the nested transactions
        // each committed TX first invokes mutators only, no accessors
        for (int nestLevel = 0; nestLevel < nestingDepth/2; nestLevel++) {
            objects.get(0).set(nestLevel);
            TXEnd();
        }

        // then, restablish nested transactions up to the same nesting level
        // each TX invokes mutators only, no accessors, on the second object
        for (int nestLevel = 0; nestLevel < nestingDepth/2; nestLevel++) {
            TXBegin();
            objects.get(1).set(2*nestLevel);
        }

        // finally, access the objects
        assertThat(objects.get(1).get())
                .isEqualTo((nestingDepth/2-1)*2);
        assertThat(objects.get(0).get())
                .isEqualTo(nestingDepth/2-1);

        }

**Comment by no2chem** [comment]
Hm, interesting. Unless I'm missing something, the test you give passes on master. I even tried increasing the nestLevel parameter to 16...

**Comment by slfritchie** [comment]
Hm, I see it fail on master's commit 2c236883 on the last assertThat():

    Failed tests: 
      GH596Test.checkCommitNested:298 expected:<[3]> but was:<[0]>

**Comment by no2chem** [comment]
ah, interesting, I was on commit 26115d1dea it seems. I'll inspect the changes...

**Comment by no2chem** [comment]
So, the problem seems to be, as @slfritchie points out, in commit 2c23688, which uses the write set entry size, which is incorrect in the case of nested updates (it should use the size of the nested update list).

I think what the test in access() was checking for before was whether or not there was an optimistic write set at all, which may have been a marker from a previous refactoring. I think the solution will be to have access check if the optimistic stream has updates or not...

**Comment by slfritchie** [comment]
Hrm, there's more than one good/bad transition in the recent history of master?  Or this commit really is the breaker?  I ran `git bisect` twice and got the same answer.

    %	git bisect start master efa07e1675fa03861740b786d930cac4695a7495
     %	git bisect run sh -c 'mvn clean > /dev/null ; mvn -Dtest="$1" -DfailIfNoTests=false test GH596Test'
    [....]
    e4ea127365896af27fedcd8acdc96d4b21775b29 is the first bad commit
    commit e4ea127365896af27fedcd8acdc96d4b21775b29
    Author: Michael Wei <mwei@cs.ucsd.edu>
    Date:   Sat Apr 29 16:20:48 2017 +0100
    
        cleanup deprecated code
    
    :040000 040000 7ba08bfcb53ee10326ee610c6114b5ad53ab483f 1448fc453b6a26c5b698d3fc39bf1e971fede83a M	annotationProcessor
    :040000 040000 f2bd8074f667240ded1750bbb70ea6627e5a1703 48bfe55df7accc98632511b214faa4bda914e6e5 M	runtime
    :040000 040000 865c30621348c46ce2aa66255dc4d734990d124e f4a1bcb8e53707ea1c6b794aa3d96c7063d44148 M	test
    bisect run success

**Comment by slfritchie** [comment]
Mid-June issues review: ping @dahliamalkhi, are you still working on this?

The May 11 code in https://github.com/CorfuDB/CorfuDB/issues/596#issuecomment-300956758 (see https://gist.github.com/slfritchie/d3d67941364f9b3fe98c11596d2a668f for compilable class) will fail using today's `master` branch at commit cdcbdb338.
