### ISSUE TITLE
[Runtime] NetworkException handling for Transactions

### ISSUE THREAD

**Issue by annym** [CorfuDB/CorfuDB#600]
Corfu Runtime does not handle NetworkException failures, therefore, when the single corfu node dies, ongoing transactions are never aborted (removed from the context stack of a WriteSetSMRStream). This leads to the accumulation of transaction contexts during the time of network disconnection (whenever a client retries upon failure).

**Comment by Maithem** [comment]
@annym  Btw, can other exception types cause this issue? For example, any uncaught runtime or unhandled type exception would actually cause this leak. Is this correct?

**Comment by annym** [comment]
@Maithem yes, currently the only exception that is being handled is TransactionAbortedException. I have a fix. As soon as I finish the Integration Test I'll push it.

**Comment by Maithem** [comment]
Addressed by #618
