### ISSUE TITLE
Layout populates "localhost" instead of IP address causing client connection redirect

### ISSUE THREAD

**Issue by kjames88** [CorfuDB/CorfuDB#605]
Setup:

Client IP A
Server IP B

Client connects to server and retrieves layout with log server as "localhost"
Client attempts to use log server at address A ("localhost") which has no server

Roger confirms the -a switch is required to populate the server's address, otherwise the layout fails.  Observed failure is that server at B does not write to its log file and client hangs, whereas if a second server is started at A then writes accumulate in A's log file despite the client connect address set to B.  If server at B is killed, server at A log file is not written.

**Comment by Maithem** [comment]
What does "never sees log size increase" mean? are you talking about the sequence number or log files size?

Also, -a tells the server which ip to bind to, so I'm not sure if this is really a bug. If you start the server on a single node that has two ips, how would it know which ip to bind to, if you dont specify it ?

Finally, if the server is started with -a, do you still observe the problem ?

**Comment by kjames88** [comment]
Returning "localhost" to a remote host is a bug.  Receiving "localhost" from another host should cause an error.  Whether or not there is more than one NIC, the address selected and used should be valid for the host.

**Comment by kjames88** [comment]
For the -a flag I'm going on Roger's comment.  I haven't verified it yet.

**Comment by Maithem** [comment]
There are three cases:
- Both client and the server are binded to local host (same machine)
- A client is binded to something other than localhost, but the server is running on localhost (same machine)
- Both client and server are run on two different machines

How would you determine a "remote" connection for all three cases mentioned above?

I think this is a degenerate case. Also, you didn't answer the first question. I'm not sure if you are reporting one or more problems.

**Comment by kjames88** [comment]
Localhost is not an IP address.  Don't send localhost to anyone as your IP address.  The degenerate case is having only one instance in a "distributed" system.  It's convenient to use localhost on the command line but it has to be translated into a real IP address.  If that can't be done then the address switch is not optional, and further "localhost" has to be an error case on the user input.

I already reworded the text to try to clarify the first question but it's really beside the point.

**Comment by slfritchie** [comment]
I've wrestled with this naming problem.  (One of the hardest problems in CS `^_^`)  In the Corfu runtime, the thing that drives all TCP connection establishment is the Layout.  Servers are identified in the layout by {hostname-or-IP-address, TCP port} tuples.  The Layout is an expression of administrator policy.  One implicit byproduct of that policy is that cross-machine communication should use only the IP addresses in the Layout itself or resolvable via local machine policy (DNS, /etc/hosts, Yellow Pages, ancient history...).  If an address isn't in the Layout, you're not supposed to use it.

If the Layout contains a hostname "localhost", then that's what the Layout means you to use.  If you cannot talk to that machine's loopback interface, then you have no business talking to that server.

If a Layout contains "localhost" but that wasn't intended policy, then the administrator should edit/replace the layout.  If the tooling to do that is not allowing an admin to use not-localhost hostnames, then I will definitely agree that there's a bug.

**Comment by Maithem** [comment]
Well, it doesn't have to be an ip, localhost is a valid address. Are you familiar with hostnames? This is just networking 101. Detecting whether an address is localhost and throwing an error is a hack and doesn't work for all the cases mentioned above.

@slfritchie that is my understanding too. Also, if you are starting a server in single node mode without specifying a layout or an address, it will bind to localhost, this is documented and I'm not sure why there's a  different expectation.

**Comment by kjames88** [comment]
Networking 101.
Nice.

**Comment by slfritchie** [comment]
I'd like to move focus to the layout being used.  How exactly is being it created?  And how exactly is the server being run?  With those specifics, then we can start figuring out what needs to change.  (It might be more than one change required: code, cluster setup procedure, and/or other.)

**Comment by kjames88** [comment]
The question of using FQDN has been raised.  It seems to me there were marketing reasons for being able to run on an L2 network rather than requiring L3, and I've previously found it to be painful to create a small hadoop deployment due to FQDN requirement.

As far as automatic translation, there would need to be some rules for selection.  In the past "eth0" usually worked on linux.  I ran this on a Mac, which uses "en0" instead.  Below is the list returned by my Mac.  IPv4 should probably be used but there are still multiple interfaces even though there is only one physical NIC (802.11).

Interface name:**awdl0 (awdl0)** has address /fe80:0:0:0:5c36:58ff:fe8e:a2e4%awdl0
Interface name:**vmnet8 (vmnet8)** has address /192.168.73.1
Interface name:**vmnet1 (vmnet1)** has address /172.16.198.1
Interface name:**en0 (en0)** has address /fe80:0:0:0:3e15:c2ff:fed1:b916%en0
Interface name:**en0 (en0)** has address /10.2.12.152
Interface name:**lo0 (lo0)** has address /fe80:0:0:0:0:0:0:1%lo0
Interface name:**lo0 (lo0)** has address /0:0:0:0:0:0:0:1
Interface name:**lo0 (lo0)** has address /127.0.0.1

**Comment by kjames88** [comment]
Scott,
The deployment is just a single server started with -s.  The default address used for -a is localhost and the comment says as much.  The problem is with trying to use this server with a client that is anywhere other than on the same box and container/vm.

**Comment by Maithem** [comment]
This problem is a side effect of incorrect configuration, but we can still "defensively code" against it. Patch #609 should address your concern. If this still doesn't address your main concern, please state why it doesn't.

Also note that localhost is not a FQDN.

**Comment by slfritchie** [comment]
Mid-June issues review:  @kjames88, has practice & code change over the last month been sufficient, or is there remaining work on this?

**Comment by Maithem** [comment]
Fixed.
