### ISSUE TITLE
Create forward pointers (first pass: in memory, not persisted)

### ISSUE THREAD

**Issue by kjames88** [CorfuDB/CorfuDB#619]
Upon processing backpointers, runtime will generate forward pointers and post to the log servers.  Stream forward pointer lists will be constructed and stored in memory.  A later phase may add persistence.

**Comment by slfritchie** [comment]
Mid-June issues review: design has been discussed during our weekly meetings.  Implementation has started with PRs #637 & #631 (still in review today).

**Comment by Maithem** [comment]
The performance benefit will be achieved through a different mechanism.
