### ISSUE TITLE
Cannot run Corfu: command not found

### ISSUE THREAD

**Issue by sdvohra** [CorfuDB/CorfuDB#622]
Followed all the steps described in the README to set up Corfu. Running "corfu_server -ms 9000" yields "corfu_server: command not found." See screenshot below:
![screen shot 2017-05-18 at 9 47 04 am](https://cloud.githubusercontent.com/assets/22339093/26213767/09961ca2-3baf-11e7-87a4-e7462450b20a.png)
I think I may have overlooked something - what could I be missing? Thanks in advance for all the help.

**Comment by Maithem** [comment]
corfu_server is located inside the bin directory. After you cd into your CorfuDB directory, you can run
./bin/corfu_server -ms 9000

**Comment by Maithem** [comment]
addressed by #623
