### ISSUE TITLE
Transaction Aborted Exception - Cause: Conflict Key (single thread)

### ISSUE THREAD

**Issue by annym** [CorfuDB/CorfuDB#636]
I've come across the case where (randomly) I get a TransactionAbortedException (abortCause: conflict / conflict key) even when not in a multi-threaded scenario. I'll write a test to try to reproduce this scenario.

**Comment by slfritchie** [comment]
Mid-June issues review: @annym, do you have a test case to reproduce this error?

**Comment by annym** [comment]
@slfritchie I made several attempts but wasn't able to reproduce this error

**Comment by slfritchie** [comment]
Thanks, Anny, I'll close this then.  Please reopen if you hit it again.
