### ISSUE TITLE
Snapshot transaction default log address should not be -1

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#653]
During the discussion of PR #641, Dahlia and I had an email discussion.

    Me: [... I made a change to create a] snapshot txn with the
    current global log address.

    Dahlia: Well, I think this should be the default behavior for
    snapshot TX, not just for checkpoint purposes. The TXBuilder
    allows to override and specify a concrete snapshot; I suspect
    this will rarely be used. I think it got lost in refactoring
    at some point.

To make things concrete, if test code creates a snapshot transaction without specifying a log address/snapshot location:

            getDefaultRuntime().getObjectsView().TXBuild()
                    .setType(TransactionType.SNAPSHOT)
                    .begin();

... then today's code will use address -1.  No data is readable at that address, which (arguably) isn't useful.

**Comment by slfritchie** [comment]
Mid-June issues review: checkpoint & trim are implemented but still under test.  Let's return to this small change request when this month's testing is finished and we're happy with the API & behavior?

**Comment by Maithem** [comment]
To be addressed in #1323
