### ISSUE TITLE
Add full enumeration of checkpoint record addresses in END entry metadata

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#663]
This is a sanity check recommended by @Maithem during the review of #648 and #662.

"Also, I think we need a mechanism that checks the validity of a CP. For example,
if you read a CP-END record, it contains pointers to the CP-Start and CP-Continuation entries, then the backpointers stream view should make sure that all those entries have been evaluated for that checkpoint."

Also, while we're at it.  @dahliamalkhi made a review comment after #662 merged.  Fix up the comment as appropriate.

"In AbstractQueuedStreamView.java, looking at the comment at line 81 onward: I feel that the comment is too narrow. Any time there is a checkpoint and no updates, we would need to update the globalPointer, not only when there are two consecutive ckPoints, no?"

**Comment by Maithem** [comment]
Re-open if needed.
