### ISSUE TITLE
Investigate opening a new map scanning

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#707]
In some cases, it appears that opening a new map on a map that already contains elements takes up to 10s latency. Investigate the reasons for this.

**Comment by no2chem** [comment]
This may have been closed with #712. @annym @kjames88 @medhavidhawan does it appear that is the case?

**Comment by kjames88** [comment]
I'm not sure I understand the description, but this is probably covered by #712:  any runtime that follows backpointers on a stream will read back to the start of the log because the head of the stream is effectively unterminated without the patch.

**Comment by no2chem** [comment]
Fixed by #712.
