### ISSUE TITLE
Integration Test "testSingleNodeRecoveryTransactionalClient" Intermittent Failures

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#722]
I'm getting intermittent failures of this test on master:

testSingleNodeRecoveryTransactionalClient                   Start Corfu Server
SEED = -1155991940662229395
SEED = -7573786996776652310
SEED = 9016519772352804884
SEED = 8165685306803057039
Shutdown Corfu Server
SEED = -3953242588241241967
SEED = 3994629209529260699
SEED = 6207313804009282908
SEED = 333512813349645788
Restart Corfu Server
SEED = -8321431135250263724
[FAIL - ComparisonFailure:L217]

Also, can we print the seed as hex? It would make it a bit more readable.

**Comment by zalokhan** [comment]
I'll have a look at this.

**Comment by zalokhan** [comment]
@no2chem I haven't seen this failing in a long time. Can we close this?

**Comment by no2chem** [comment]
Sounds good to me. Closed.
