### ISSUE TITLE
Pass TRIMMED data instead of throwing an exception

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#745]
Currently, StreamLogFiles::read throws a TrimmedException which causes a bulk read to throw Trimmed, even if only a single address is trimmed. We need to add a new LogData.TRIMMED value instead of throwing an exception.

**Comment by Maithem** [comment]
Addressed by https://github.com/CorfuDB/CorfuDB/pull/756

**Comment by Maithem** [comment]
Second part, addressed by https://github.com/CorfuDB/CorfuDB/pull/760
