### ISSUE TITLE
Layout metadata is not persistent when running in-memory mode

### ISSUE THREAD

**Issue by bitmingw** [CorfuDB/CorfuDB#754]
The in-memory corfu server is designed to not persist data. However, it may need to persist some metadata like layout. In the current command-line interface, since `-m` is not compatible with `-l`, the layout metadata of in-memory corfu server is not saved in file system.

Is this possible to change this behavior and make metadata also available for in-memory corfu server?

**Comment by no2chem** [comment]
Is there a particular use case in which you would need to persist this data? It seems strange to want to persist the layout data when the log unit data will be lost on restart.

**Comment by Maithem** [comment]
@bitmingw do you still need this? You can get the layout easily, what other metadata are you trying to access and why?

**Comment by bitmingw** [comment]
@Maithem Right now in memory corfu usage case is not deployed, you can close this issue.
