### ISSUE TITLE
Quorum Read Trimmed Exception

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#763]
@kspirov I made a change so that reading a trimmed address doesn't throw an exception, so futures[i] = layout.getLogUnitClient(address, i).read(address); wont throw an exception if it reads trimmed addresses. But in some places we would like to throw an exception if the read response == DataType.Trimmed

I did this for now : https://github.com/CorfuDB/CorfuDB/pull/760/files

Do you know if this is the cleanest way to achieve this?

**Comment by kspirov** [comment]
Let me have 3 free hours and I will review this with pleasure.
ETA:This Sunday.

**Comment by Maithem** [comment]
outdated.
