### ISSUE TITLE
Logging file (not log data) is erased after restart corfu server

### ISSUE THREAD

**Issue by bitmingw** [CorfuDB/CorfuDB#773]
Corfu uses [logback](https://logback.qos.ch/) to manage the logging generated by application. Currently, the logging file is erased after each restart of corfu server, which makes the debugging process difficult.

The configuration of logback is defined in `runtime/src/main/resources/logback.xml`. From the [docs](https://logback.qos.ch/manual/appenders.html) of logback, when `STDOUT` is used as the appender, a default file will be opened (e.g. `/var/log/corfu.9000.log`) and there is no way to preserver the logging from last run. As a result, we will need to switch to `FILE` appender. This process, thereafter, brings up two questions.

First, there are a couple of places use `System.out.print` to log message. Those usages need to clean up when we switch to file appender.

Second, we need to think about a good way to name logging files when there are multiple instances of corfu servers.

**Comment by Maithem** [comment]
Most of the system.out.printl statements are in the sample code, they dont run on the server.
There are a couple of system out statements that are in CorfuServer.java that print the server options and logo, which should be easy to migrate to logging.

**Comment by bitmingw** [comment]
Resolved by #782
