### ISSUE TITLE
prefixTrim -1 should throw IllegalArgumentException

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#812]
PrefixTrime should ensure the trim is requested only for positive addresses.

**Comment by Maithem** [comment]
The code current ignores negative numbers, or repeated trims, would that suffice, or are you asking for an explicit error. Also, what's the point of throwing an explicit error? logging a warn seems to be fine.

**Comment by no2chem** [comment]
Well, it indicates a programming error and it would be better to catch that earlier rather than later.
