### ISSUE TITLE
Object Access

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#827]
Accessing an object after trim requires at least a single checkpoint for that stream to exist. In certain cases where the map is empty, a checkpoint is not generated and thus breaks the aforementioned assumption. One possible fix is to generate checkpoints even for empty maps.

**Comment by no2chem** [comment]
This is not just an issue with non-tx access - with tx access the object will incorrectly throw trim exception

**Comment by Maithem** [comment]
Addressed by https://github.com/CorfuDB/CorfuDB/pull/830
