### ISSUE TITLE
Never accept a Layout that has a smaller epoch than current

### ISSUE THREAD

**Issue by rogermichoud** [CorfuDB/CorfuDB#832]
There might be some corner cases where we will receive a Layout from a stale layout server (especially since we pick one layout server at random). This Layout received is in a previous epoch and currently it will be used for this runtime.

For sanity, let's ensure that we never accept a Layout that is in a previous epoch that the current one we have.

**Comment by rogermichoud** [comment]
#822

**Comment by Maithem** [comment]
Why would that happen if you are doing quorum reads?

**Comment by rogermichoud** [comment]
Not for quorum reads. The scenario happens for chain replication. Let's say we have 3 servers:

1. Seal (S1, S2, S3 are sealed)
2. Lose network connectivity to S3
3. Propose and commit a new Layout via Paxos (S1, S2 respond, we have majority, new layout accepted).
4. Client (or other client) lose network connectivity to S1 and S2.
5. Client ask for the layout, it gets it from S3 that still have the previous layout. The client will go back to previous epoch. 

It doesn't even need 4 in order to expose this issue. Since we shuffle and pick at random a LayoutServer, if we happen to pick the wrong one, we will go back to the previous layout. This is dangerous, because the client could do reads from the wrong layout. The log units/sequencer of the previous layout might even respond and it will look fine from the client since they are in the same (deprecated) epoch.

**Comment by Maithem** [comment]
Right, I wasn't referring to the write replication protocol. I was saying that you wouldn't have this problem if you do a quorum read on the layout servers, so that you don't get a stale layout.

**Comment by rogermichoud** [comment]
Agree with you. If we do a quorum read, it will theoretically be safe. There might be other corner cases that we didn't think about yet. I think it doesn't hurt to be extra safe and just ensure we never accept a Layout that has a previous epoch.

I am in favor of doing a quorum read as well, but I would delay it to another PR. This would involve a complete change of the fetchLayout logic and might be (too?) risky at this time. 

I will open a lower priority issue to move fetchLayout to a quorum read.

**Comment by zalokhan** [comment]
The epoch is now removed from the router and the runtime layout no longer dictates the epoch with which these messages are stamped.
So marking this resolved by #1192
