### ISSUE TITLE
Reading own append fails if cache is disabled

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#856]
This basic test:

```java
    @InterfaceTest
    default void canReadOwnAppend(CorfuRuntime r, S s, E e) {
        s.append(e);
        assertThat(s.hasNext())
                .isTrue();
        assertThat(s.next().getPayload(r))
                .isEqualTo(e);
    }
```

Fails with:
```
org.junit.ComparisonFailure: expected:<[BackpointerStreamViewContractTest.LongWrapper(value=0])> but was:<[LogEntry(type=NOP])>
Expected :BackpointerStreamViewContractTest.LongWrapper(value=0)
Actual   :LogEntry(type=NOP)
```

If caching is disabled. For some reason if the cache is disabled a LogEntry (which this test never creates) is returned instead.

**Comment by slfritchie** [comment]
FWIW, the behavior of cache enabled vs. disabled changed at the commit below.  Prior to this, cache enabled vs. disabled behavior was the same: both return `LogEntry` instead of an `ICorfuSerializable` type.

    d3c858ae3028368c9e8a0aab780dd8f39cc42041 is the first bad commit
    commit d3c858ae3028368c9e8a0aab780dd8f39cc42041
    Author: Michael Wei <mwei@cs.ucsd.edu>
    Date:   Tue Mar 7 20:05:08 2017 -0800
    
        Richer stream seek interface and cleaned up version lock object

**Comment by no2chem** [comment]
This ended up being an issue in the serializer in the test suite I was using. I'm going to close this as invalid.
