### ISSUE TITLE
Metrics is causing possible race condition in CI

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#916]
This is appearing in CI logs, causing failed builds:

[INFO] --- clojure-maven-plugin:1.8.1:compile (compile) @ cmdlets ---
Compiling org.corfudb.shell to /tmp/classes72337861294533364.dir
01:05:15,665 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
01:05:15,665 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
01:05:15,665 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/home/travis/build/CorfuDB/CorfuDB/runtime/target/runtime-0.1-4385.jar!/logback.xml]
01:05:15,681 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@517d4a0d - URL [jar:file:/home/travis/build/CorfuDB/CorfuDB/runtime/target/runtime-0.1-4385.jar!/logback.xml] is not of type file
01:05:15,827 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
01:05:15,830 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
01:05:15,840 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [MetricsRollingFile]
01:05:15,880 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@7862f56 - No compression will be used
01:05:15,886 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
01:05:15,923 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[MetricsRollingFile] - Active log file name: /var/log/corfu-metrics.log
01:05:15,923 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[MetricsRollingFile] - File property is set to [/var/log/corfu-metrics.log]
01:05:15,925 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[MetricsRollingFile] - openFile(/var/log/corfu-metrics.log,true) call failed. java.io.FileNotFoundException: /var/log/corfu-metrics.log (Permission denied)
	at java.io.FileNotFoundException: /var/log/corfu-metrics.log (Permission denied)
	at 	at java.io.FileOutputStream.open0(Native Method)

**Comment by zalokhan** [comment]
Yes it seems travis does not allow access to Corfu to create a metrics file  /var/log/corfu-metrics.log.
I'll see if we can workaround this issue.

**Comment by Maithem** [comment]
also, this is not just a travis issue, i see it on my local machine.

**Comment by Maithem** [comment]
This has been fixed on the client, but not the server. Need to remove the log4j config on the server.
