### ISSUE TITLE
Address Segmentation NPE

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#937]
When reading/writing to an address that is not in an available segment and NPE is thrown. 
For example, read(10), or write(10)

{
  "layoutServers": [
    "localhost:9000"
  ],
  "sequencers": [
    "localhost:9000"
  ],
  "segments": [
    {
      "replicationMode": "CHAIN_REPLICATION",
      "start": 0,
      "end": 10,
      "stripes": [
        {
          "logServers": [
            "localhost:9000"
          ]
        }
      ]
    }
  ],
  "unresponsiveServers": [],
  "epoch": 0
}

**Comment by Maithem** [comment]
@zalokhan fyi there's a boundary that will affect you layout split segment patch.

**Comment by zalokhan** [comment]
Yes I've seen this. 
The start is inclusive and end is exclusive.
I split the segment and set the start and end pointers accordingly.

**Comment by Maithem** [comment]
Can you document these segment bounderies in #970 so that we can close this issue

**Comment by zalokhan** [comment]
Sure I'll document this
