### ISSUE TITLE
nettyServerClientPingable test case failed

### ISSUE THREAD

**Issue by ccding** [CorfuDB/CorfuDB#954]
```nettyServerClientPingable                                   [FAIL - IllegalStateException:L58]

java.lang.IllegalStateException: failed to create a child event loop
Caused by: io.netty.channel.ChannelException: failed to open a new selector
Caused by: java.io.IOException: Too many open files
```

Is there anything I misses? I use a newly installed Ubuntu 14.04 with Java 8 and Maven 3.3.9.

I have tried master head and v0.1 tag, neither works.

**Comment by Maithem** [comment]
It is possible that you have an fd leak on your system that is not related to CorfuDB, which is causing that unit test to fail. You can check your system with the following two commands:
1) cat /proc/sys/fs/file-max
2) lsof | wc -l

**Comment by Maithem** [comment]
Can't reproduce.
