### ISSUE TITLE
Mutator/Accessor are not added to the read set in transcations

### ISSUE THREAD

**Issue by rogermichoud** [CorfuDB/CorfuDB#958]
When we do a LogUpdate during transaction, we don't add the map/key to the readset. This means that an optimistic transaction, we won't detect conflict on map.put(). 

Because we don't conflict, we create the undoRecords based on the value we had when we started the transaction. Upon rollback, we will skip everything that happened between the beginning of the transaction and the end of it.

**Comment by no2chem** [comment]
read set insertion is done during getUpcallResult, which seems to be the correct place. logUpdate shouldn't be adding anything to the read set.
