### ISSUE TITLE
Can't Restart After Cold Reboot

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#966]
After suddenly pulling the power plug a couple of times the server cannot be restarted. A QuorumUnreachableException is thrown. It seems like the layout files are inconsistent.

**Comment by no2chem** [comment]
Is this bug still reproducible?

**Comment by Maithem** [comment]
@no2chem Don't now haven't tried recently.

**Comment by Maithem** [comment]
addressed by #1212
