### ISSUE TITLE
Error when building Corfu-YCSB Corfu Binding

### ISSUE THREAD

**Issue by jbernardo95** [CorfuDB/CorfuDB#980]
Hi !

When trying to compile the Corfu binding for YCSB I get the following warnings:

```
[WARNING] The POM for org.corfudb:corfu:pom:0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.corfudb:runtime:jar:0.1-SNAPSHOT is missing, no dependency information available
```

Which result later in:

```
[ERROR] Failed to execute goal on project corfu-binding: Could not resolve dependencies for project com.yahoo.ycsb:corfu-binding:jar:0.13.0-SNAPSHOT: The following artifacts could not be resolved: org.corfudb:corfu:pom:0.1-SNAPSHOT, org.corfudb:runtime:jar:0.1-SNAPSHOT: Could not find artifact org.corfudb:corfu:pom:0.1-SNAPSHOT -> [Help 1]
```

Any idea why this is happening ?

I get this when trying to `sudo bin/ycsb load corfu -p workloads/workloadb -P corfu.dat`

**Comment by jbernardo95** [comment]
I believe this is related with #567 and #585.

@slfritchie Any idea why this is not working ?

**Comment by Maithem** [comment]
Did you run mvn clean install on the CorfuDB first?

**Comment by Maithem** [comment]
Also, the workload file is specified with "P" and not "p"

**Comment by jbernardo95** [comment]
@Maithem I did run `mvn clean install` on the CorfuDB. And the -p was a typo.

I got around this by changing the `corfu/pom.xml` to match the instruction in the CorfuDB main repo.

I don't know if the current setup is just out of date and should be updated or if it should work.

I would be happy to open a PR to update the `pom.xml` if it makes sense to do so.

**Comment by Maithem** [comment]
I see, did you add the mvn repository? As far as a I know mvn install will create the CorfuDB artifacts in .m2 folder which the pom should check. Yes, please submit a PR.

**Comment by jbernardo95** [comment]
@Maithem [PR](https://github.com/CorfuDB/Corfu-YCSB/pull/1) is up, let me know what you think and if ir makes sense (because I am not very familiarised with maven).

**Comment by Maithem** [comment]
@jbernardo95 Merged. Thanks for the fix.
