### ISSUE TITLE
Config Robustness

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#991]
The runtime exposes a couple of setters to change different configurations that different runtime views rely on, therefore the views should only be initialized after the configurations have been set. If they interleave, then some configurations can be ignored. It might be a good idea to force an order.

**Comment by no2chem** [comment]
Probably should use the existing ```CorfuRuntimeParameters``` class, and set the parameters at initialization time by passing ```CorfuRuntimeParameters``` through the constructor, and deprecate all the setters that are exposed in the runtime.
